### ISSUE TITLE
access denied smb: for mount disk

### ISSUE THREAD

**Issue by Astate** [dianlight/hassio-addons#1]
Hi 
when want to create a directory or a file in smb share on external HD. I have "access denied smb: " error  
I have full access on sd card.
The hardisk is formated in Ntfs.

**Comment by dianlight** [comment]
Hi,
 NTFS for Linux is a “bad boy”. There is only read support in standard kernel. 
I suggest to switch to Linux friendly fs. I suggest you ext4.

I can try to insert a fuse ntfs fs to support rw operations but is not 100% affidabile for your data.

**Comment by Astate** [comment]
Hi,
I will switch to ext4, its was on ext4 before i switch to NTFS because i dont understand how "Mode protection" and disk label work.  Is it possible to use NFS on hassos? Samba it's a good thing if you want to use TimeMachine.

**Comment by dianlight** [comment]
I not understand what you mean for “Mode protection”.  
To use ext4 you need to create the partition, format with mk2fs an then label it with e2label. ( search on google, simple tutorial https://www.google.it/amp/s/www.cyberciti.biz/faq/linux-modify-partition-labels-command-to-change-diskname/amp/ )

Maybe you can use also NFS to share your disk but this is a SAMBA addon! ;)
NFS not work well if you share external drive and Timemachine targets ( AAPL is an extension of the SMB protocol).

For example in my config (the actual target reference platform )I have a dual drive extern usb3 enclosure with Hw raid1 connected to a rpi4 with 2 partition, one is used as timemachine target for 2 MacBooks and a Win10 notebook and the other with my  modified Plex addon as media library.

**Comment by Astate** [comment]
I understand now and everything works fine.

This is what i believed:
> I thought I could set the Option: moredisks to blank and that a disk scan would be done to search usb disk but for this i I was thinking the Protection Mode option need to be disabled
