### ISSUE TITLE
How to mount ExtFAT and NTFS drives?

### ISSUE THREAD

**Issue by felislynx-silae** [dianlight/hassio-addons#100]
Hi, i've 3 drives with lots of data on them which i wanted to share from SambaNAS. I don't want to format them. While trying to mount them i get:
```
FUSE exfat 1.3.0
WARN: volume was not unmounted cleanly.
fuse: device not found, try 'modprobe fuse' first
[10:22:49] WARNING: Fail to mount Empty!
mount: /mnt/bigdata2: unknown filesystem type 'ntfs'.
       dmesg(1) may have more information after failed mount system call.
```
I would like to ask for help, how to make it work without formatting to ext4 :)

**Comment by dianlight** [comment]
Sorry is not possible, please see the documentation:

Unsupported:
- All Fuse based FS like exFat, fat32, ntfs. Samba don't like fuse.
