### ISSUE TITLE
error in mds_init_ctx

### ISSUE THREAD

**Issue by my-machines** [dianlight/hassio-addons#105]
Hi. First of all thank you for this great add-on. 
I am on HA OS and want to mount a ext4 formatted ssd to my RPi4. 
At first the add-on mounts the drive, i can see it on the network but as soon as i want to access it, it crashes and i get this message:

`error in mds_init_ctx for: /drive_name
_mdssvc_open: Couldn't create policy handle for drive_name`

after that the external drive, all sd drives and all other usb devices (Zigbee 3.0 USB Dongle Plus) get lost and i have to restart the whole system for them to get recognized again.

System:
Home Assistant 2022.10.5
Supervisor 2022.10.0
Operating System 9.3
Frontend 20221010.0 - latest
Rpi 4 - 4gb

Thank you for your help.

**Comment by dianlight** [comment]
Hi, 
 this type of problem are often derived from insufficient power. 
Can you give me more information about hw config? 
- you use PD port to power your RPi? How many Amp? 
-  How many usb devices do you have?
-  Zigbee is attached on USB3 ( blue) or USB2 ports?  Also where is the SDD?
-  Do you have an extensions USB cables or dongle are direct to port?
Also do you have the Power Pi device on HA? Do you have history or allerts?


L.

**Comment by my-machines** [comment]
Thank you for your quick and very helpful reply.
I tried various different setups in the last days but without any luck. 
I usually have the zigbee stick connected with an extension cable via USB2. 
The ssd is connected via the USB3 port and the RPi gets its power over PD port and the official power supply without any alerts. 
I tried various other power supplies and with and without the zigbee stick connected. Apart from the ssd, the zigbee stick, power and a lan cable there is nothing else connected to my RPi.

**Comment by Gramboalain** [comment]
I’ve the same issue. First it works some hours and then suddenly, I got this message in the logs:
mdssvc_open: Couldn't create policy handle for TimeMachineHA
error in mds_init_ctx for: /mnt/TimeMachineHA

After that it’s impossible to restart the module and the mounted disk are not accessible.

**Comment by my-machines** [comment]
@dianlight is there anything else we could test or some additional data we can provide?

**Comment by dianlight** [comment]
Hi @my-machines and @Gramboalain 
I can't replicate the issue in my environment but I found tips on internet about the use incompatible SSD adapter on the USB3 on RPi4.

I suggest to try  to connect the SSD on the USB2 and see. Keep in mind that USB2 is much slower than USB3 but since it is accessed via the network it doesn't change much.

If USB2 work you can try to update the rpi-eeprom firmware for USB (https://github.com/raspberrypi/rpi-eeprom) o simpli continue to use the USB2.

@Gramboalain is your drive also an ext4 or you use another fs?

L.

**Comment by Gramboalain** [comment]
Hello

My disks are formatted with ext4 File System.
It's not SSD, but classical HD. I think that it's a USB3 connection. I can check it this evening if necessary.

Alain

**Comment by my-machines** [comment]
Thank you @dianlight for your support. I really appreciate your help. 
I tried everything you recommended, but still no luck. I tried a different SSD adapter (that is known to work with RPi4), I tried both USB 3 and 2 before and after I updated the eeprom firmware. I reformatted the drive several times.
But as soon as I click on the external drive in finder it crashes and this is what the add-on protocol provides:

> xxx,xxx:wsdd INFO(pid 360): deleted address xxx on xxx
Failed to fetch record!
pcap cache not loaded
Failed to fetch record!
pcap cache not loaded
error in mds_init_ctx for: /addons
_mdssvc_open: Couldn't create policy handle for addons
Failed to fetch record!
pcap cache not loaded
error in mds_init_ctx for: /backup
_mdssvc_open: Couldn't create policy handle for backup
Failed to fetch record!
pcap cache not loaded
error in mds_init_ctx for: /config
_mdssvc_open: Couldn't create policy handle for config
Failed to fetch record!
pcap cache not loaded
error in mds_init_ctx for: /media
_mdssvc_open: Couldn't create policy handle for media
Failed to fetch record!
pcap cache not loaded
error in mds_init_ctx for: /share
_mdssvc_open: Couldn't create policy handle for share
Failed to fetch record!
pcap cache not loaded
error in mds_init_ctx for: /ssl
_mdssvc_open: Couldn't create policy handle for ssl

**Comment by dianlight** [comment]
Hi @my-machines,
 the log you post are quite normal.   
Can change the log_level to `trace` in the addon config and retry?

The really strange thing in your case is that the whole USB subsitem crashes. It is unlikely that this is an error of the Addon which is in a Docker. It looks more like a hardware failure (low power, broken USB cable, unsupported USB-SSD controller etc etc) or a host level error.

You can do one last test. Just a USB stick. Try to format it in ext4 insert it in RPI4 (removing the SSD) and put it as the only `moredisk`. To see if the error happens.

**Comment by my-machines** [comment]
Hi @dianlight 
i moved from the raspberry to a thin client and there your add-on works flawlessly. I guess you were right about that the error was due to one of the hardware components.
Thank you for the add-on and your help troubleshooting it.
