### ISSUE TITLE
Can't run Samba NAS add-on

### ISSUE THREAD

**Issue by ivorco** [dianlight/hassio-addons#11]
This is what I get:
[cont-init.d] automount.sh: exited 0.
[cont-init.d] mqtt.sh: executing... 
[17:20:19] ERROR: Got unexpected response from the API: Service not enabled
[17:20:19] INFO: Sending MQTT autodiscovery...
Error: -h argument given but no host specified.

No explanation on what I should install or change to fix that
The config is almost exactly like the regular Samba add-on

**Comment by dianlight** [comment]
I need to know more about your environment.
Can you post the addon config and a short description of your ha installation?

L.

**Comment by ivorco** [comment]
![image](https://user-images.githubusercontent.com/2694823/96379812-1cc05500-1198-11eb-99d2-37597add7784.png)

HA installed on micro SD
Nothing special about it

**Comment by dianlight** [comment]
> ![image](https://user-images.githubusercontent.com/2694823/96379812-1cc05500-1198-11eb-99d2-37597add7784.png)

You don't insert a valid disk label. <Partition Label> is an ancor. 
If you use moredisks option you need to list the partitions labels of yours disks to mount.
Please read the documentation about how configure the addons.

L.

**Comment by ivorco** [comment]
I don't use the moredisks option

**Comment by dianlight** [comment]
> I don't use the moredisks option 

So remove the option. But why use my addons? You can use the official, moredisks option is the difference.

Btw I never try without mounted disk I don't know if works.

**Comment by ivorco** [comment]
That was confusing
It is listed as optional and that it doesn't work in protected mode

**Comment by ivorco** [comment]
Okay, got the drive working but there is still an issue

![image](https://user-images.githubusercontent.com/2694823/96419003-33989300-11fc-11eb-8ea2-d4bf3d90d352.png)

**Comment by dianlight** [comment]
Suspect you don't have a mqtt server in your installation right?

**Comment by ivorco** [comment]
Yepp, again, it was specified as optional
Tried again with mqtt and it works

However I also had issues when drive label has spaces in it

**Comment by ivorco** [comment]
Thanks!

**Comment by mu3hli** [comment]
Ok, nice that works. Thanks!!

But there is still an error in the log, what means that?

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 0.banner.sh: executing... 
---------------------------------------------------
 ____                  _           _   _           
/ ___|  __ _ _ __ ___ | |__   __ _| \ | | __ _ ___ 
\___ \ / _` | '_ ` _ \| '_ \ / _` |  \| |/ _` / __|
 ___) | (_| | | | | | | |_) | (_| | |\  | (_| \__ \
|____/ \__,_|_| |_| |_|_.__/ \__,_|_| \_|\__,_|___/
                                                   
                              Version 9.5.1-nas4
---------------------------------------------------
[cont-init.d] 0.banner.sh: exited 0.
[cont-init.d] automount.sh: executing... 
[19:54:38] INFO: Protection Mode is false
[19:54:38] INFO: MoreDisk option found!
[19:54:38] INFO: MediaLibrary option found!
Warning: Permanently added '[192.168.178.61]:22222' (ECDSA) to the list of known hosts.
Mon Feb 21 18:54:39 UTC 2022
[19:54:39] INFO: SSH connection to 192.168.178.61:22222 OK
[19:54:39] INFO: More Disks mounting.. Intenso
[19:54:39] INFO: Mount Intenso
[19:54:40] INFO: Success!
[cont-init.d] automount.sh: exited 0.
[cont-init.d] mqtt.sh: executing... 
[19:54:40] ERROR: Got unexpected response from the API: Service not enabled
[19:54:41] WARNING: No MQTT Server found. Homeassistant integration can't work!
[cont-init.d] mqtt.sh: exited 0.
[cont-init.d] samba.sh: executing... 
[19:54:42] INFO: Using hostname=homeassistant interface=eth0
tdbsam_open: Converting version 0.0 database to version 4.0.
tdbsam_convert_backup: updated /var/lib/samba/private/passdb.tdb file.
Added user muehli.
[cont-init.d] samba.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
nmbd version 4.13.8 started.
Copyright Andrew Tridgell and the Samba Team 1992-2020
[19:54:43] INFO: Starting the AVAHI daemon for homeassistant...
daemon_ready: daemon 'nmbd' finished starting up and ready to serve connections
Waiting for daemon ...
smbd version 4.13.8 started.
Copyright Andrew Tridgell and the Samba Team 1992-2020
INFO: Profiling support unavailable in this build.
[19:54:43] WARNING: No MQTT config.
daemon_ready: daemon 'smbd' finished starting up and ready to serve connections
```

**Comment by dianlight** [comment]
It is about the MQTT server. HA api reports is existence but the connection go in error.
Do you have a mosquito instance running? ( or you had and removed? ).
You can ignore the error if you don't need the sensor that report drivers space information.

L
