### ISSUE TITLE
Can't start the Add on. Canb you help me What's wrong?

### ISSUE THREAD

**Issue by Techposts** [dianlight/hassio-addons#111]
Here're the screenshots
![image](https://user-images.githubusercontent.com/28442414/209084261-19e752bb-95ae-4da6-b675-0b52b1a882fc.png)

My Configuration
![image](https://user-images.githubusercontent.com/28442414/209084315-e218c7bc-13a0-4f54-bee5-c30c5c994e21.png)

**Comment by dianlight** [comment]
What is your environment? Are you on an HASOS installation?

**Comment by a-mkh** [comment]
Same output, supervised ha on ubuntu

**Comment by dianlight** [comment]
The plug-in is only for hassos please read the DOC. In other environment don't work and is un useful. Simply install Ubuntu samba package.

L
