### ISSUE TITLE
Mount problem

### ISSUE THREAD

**Issue by kolik2976** [dianlight/hassio-addons#112]
Unable to mount ssd

[21:59:51] INFO: More Disks mounting.. id:scsi-0QEMU_QEMU_HARDDISK_drive-scsi1
[21:59:51] INFO: Disk scsi-0QEMU_QEMU_HARDDISK_drive-scsi1 is an ID
mount: /mnt/scsi-0QEMU_QEMU_HARDDISK_drive-scsi1: wrong fs type, bad option, bad superblock on /dev/sdb, missing codepage or helper program, or other error.
       dmesg(1) may have more information after failed mount system call.
[21:59:51] WARNING: Fail to mount scsi-0QEMU_QEMU_HARDDISK_drive-scsi1!

workgroup: WORKGROUP
username: kolik
password: "2907"
allow_hosts:
  - 10.0.0.0/8
  - 172.16.0.0/12
  - 192.168.0.1/100
  - fe80::/10
moredisks:
  - id:scsi-0QEMU_QEMU_HARDDISK_drive-scsi1
available_disks_log: true
medialibrary:
  enable: false
  ssh_private_key: <YOU SUPER SECRET PRIVATE KEY>
veto_files:
  - ._*
  - .DS_Store
  - Thumbs.db
  - icon?
  - .Trashes
compatibility_mode: false
wsdd2: false
autodiscovery: {}
other_users: []
acl: []
interfaces: []

Formatted as ext4 in proxmox

**Comment by dianlight** [comment]
Please set the log to 'trace' and restart. Also I need the full log from the start not only the error and post all log and config as Code Blocks so can be readeable.

L

**Comment by kolik2976** [comment]
<spoiler>s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/00-banner.sh
-----------------------------------------------------------
 ____                  _             _   _    _    ____  
/ ___|  __ _ _ __ ___ | |__   __ _  | \ | |  / \  / ___| 
\___ \ / _` | '_ ` _ \| '_ \ / _` | |  \| | / _ \ \___ \ 
 ___) | (_| | | | | | | |_) | (_| | | |\  |/ ___ \ ___) |
|____/ \__,_|_| |_| |_|_.__/ \__,_| |_| \_/_/   \_\____/ 
                                                         
 Expose Home Assistant disc with SMB/CIFS
-----------------------------------------------------------
 Add-on version: 10.0.0-nas3
 You are running the latest version of this add-on.
 System: Home Assistant OS 9.4  (amd64 / qemux86-64)
 Home Assistant Core: 2022.12.8
 Home Assistant Supervisor: 2022.11.2
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
cont-init: info: /etc/cont-init.d/00-banner.sh exited 0
cont-init: info: running /etc/cont-init.d/01-log-level.sh
cont-init: info: /etc/cont-init.d/01-log-level.sh exited 0
cont-init: info: running /etc/cont-init.d/automount.sh
[06:46:37] INFO: Protection Mode is false
[06:46:37] INFO: MoreDisk option found!
[06:46:37] INFO: MediaLibrary disabled in config. Disk are mounted only for this addon!
[06:46:37] INFO: Available Disk Labels:
 
[06:46:37] INFO: More Disks mounting.. id:scsi-0QEMU_QEMU_HARDDISK_drive-scsi1
[06:46:37] INFO: Disk scsi-0QEMU_QEMU_HARDDISK_drive-scsi1 is an ID
mount: /mnt/scsi-0QEMU_QEMU_HARDDISK_drive-scsi1: wrong fs type, bad option, bad superblock on /dev/sdb, missing codepage or helper program, or other error.
       dmesg(1) may have more information after failed mount system call.
[06:46:37] WARNING: Fail to mount scsi-0QEMU_QEMU_HARDDISK_drive-scsi1!
cont-init: info: /etc/cont-init.d/automount.sh exited 0
cont-init: info: running /etc/cont-init.d/mqtt.sh
cont-init: info: /etc/cont-init.d/mqtt.sh exited 0
cont-init: info: running /etc/cont-init.d/samba.sh
[06:46:38] INFO: Hostname: homeassistant
[06:46:38] INFO: Interfaces: enp0s18 
tdbsam_open: Converting version 0.0 database to version 4.0.
tdbsam_convert_backup: updated /var/lib/samba/private/passdb.tdb file.
Added user kolik.
[06:46:39] INFO: Exposed Disks Summary:
[06:46:39] INFO: [config]	path = /config
[06:46:39] INFO: [addons]	path = /addons
[06:46:39] INFO: [ssl]	path = /ssl
[06:46:39] INFO: [share]	path = /share
[06:46:39] INFO: [backup]	path = /backup
[06:46:39] INFO: [media]	path = /media
cont-init: info: /etc/cont-init.d/samba.sh exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun avahi-publish-service (no readiness notification)
services-up: info: copying legacy longrun mqtt-handler-service (no readiness notification)
services-up: info: copying legacy longrun nmbd (no readiness notification)
services-up: info: copying legacy longrun smbd (no readiness notification)
services-up: info: copying legacy longrun wsdd-publish-service (no readiness notification)
nmbd version 4.15.7 started.
Copyright Andrew Tridgell and the Samba Team 1992-2021
s6-rc: info: service legacy-services successfully started
[06:46:39] INFO: Starting the MQTT daemon for disks info...
smbd version 4.15.7 started.
Copyright Andrew Tridgell and the Samba Team 1992-2021
INFO: Profiling support unavailable in this build.
[06:46:39] INFO: Starting the AVAHI for homeassistant...
Waiting for daemon ...
[06:46:39] INFO: Starting the wsdd daemon for WORKGROUP/homeassistant...
[06:46:39] INFO: Interfaces: -i enp0s18 
[06:46:39] INFO: Sending MQTT autodiscovery...
2022-12-23 06:46:40,079:wsdd INFO(pid 351): using pre-defined UUID cb6a33a0-b841-531d-a34e-09ecec492eb1
2022-12-23 06:46:40,082:wsdd INFO(pid 351): joined multicast group ('239.255.255.250', 3702) on 192.168.0.100%enp0s18
2022-12-23 06:46:40,086:wsdd INFO(pid 351): scheduling Hello message via enp0s18 to ('239.255.255.250', 3702)
2022-12-23 06:46:40,183:wsdd INFO(pid 351): joined multicast group ('ff02::c', 3702, 22364, 2) on fe80::6578:2d15:5def:e8af%enp0s18
2022-12-23 06:46:40,185:wsdd INFO(pid 351): scheduling Hello message via enp0s18 to ('ff02::c', 3702, 22364, 2)
2022-12-23 06:46:40,224:wsdd INFO(pid 351): 192.168.0.2 - - "POST /cb6a33a0-b841-531d-a34e-09ecec492eb1 HTTP/1.1" 200 -
2022-12-23 06:46:40,232:wsdd INFO(pid 351): fe80::8d8d:dd2:676:2957 - - "POST /cb6a33a0-b841-531d-a34e-09ecec492eb1 HTTP/1.1" 200 -
*****
Samba name server HOMEASSISTANT is now a local master browser for workgroup WORKGROUP on subnet 192.168.0.100
*****
</spoiler>

**Comment by dianlight** [comment]
The log say that id:scsi-0QEMU_QEMU_HARDDISK_drive-scsi1 is /dev/sdb so the disk not the ext4 partition ( /dev/sdb1? ). I suggest you to set and reference by label os search for partition id. To find it you can see the hw config in homeassistant.
Please enable available_disks_log and log to trace and use code block for future post.

**Comment by kolik2976** [comment]
Where can I find the hw configuration in homeassistant? available_disks_log is enabled. I'm new at homeassistant.

**Comment by dianlight** [comment]
Settings-> System-> Hardware-> ( 3 dot menu ) All Hardware.

L.

**Comment by kolik2976** [comment]
https://i.imgur.com/GXTqS5Km.jpg

**Comment by dianlight** [comment]
This is a disk not a ext4 partition. In the image I don't see if after there is another device `sdb1`? that is the partition to mount. If not create a partition table on the disk, a partition and format ext4. You will see the `ID_FS_TYPE: ext4` property in the ha hw list. 

L

**Comment by kolik2976** [comment]
The disk to proxmox is mounted as /dev/sda1 in the /mnt/m2 folder and added already to ha. And it is issued all the same as /dev/sdb

**Comment by dianlight** [comment]
I can't read in your mind and I don't have any crystal ball!

What do you try to do? Please describe in a clear way.

For Linux sda...sdc ( without numbers ) are disk and for every disk sd*1...99 (with numbers ) are partitions on the disks. You can format and mount partitions not disk. 

The mounted partition in ha (sda1 you say) is on the sda disk in sambanas you try to mount sdb that is a disk and you can't! You can mount sdb1...99 only if you had created the partitions on the disk and formatted ext4... and you don't have already mounted on other vm.

L.

**Comment by kolik2976** [comment]
In Proxmox, it is defined as sda, it has an ext4 formatted sda1 partition. Sda1 is mounted in / mnt / m2, I want to forward it to ha, it is defined as sdb in ha. What else do I need to do to have sdb1, ha?

**Comment by dianlight** [comment]
I don't know Proxmox but I suppose you can't have the same partition mounted on different instance. So probably is hidden. Try to umount in Proxmox and see if is visible in ha. 
I suggest you to search help in Proxmox community, if the partition is not visible I can't help you.

L.
