### ISSUE TITLE
How do I edit this field?

### ISSUE THREAD

**Issue by Icesythe7** [dianlight/hassio-addons#113]
[https://ibb.co/4WHhKgJ](https://ibb.co/4WHhKgJ)

I see no way to edit this?

Home Assistant 2022.12.8
Supervisor 2022.11.2
Operating System 9.4
Frontend 20221213.1 - latest

latest nas addon version 
rasp pi 4 8gb
fresh install using
https://github.com/home-assistant/operating-system/releases/download/9.4/haos_rpi4-64-9.4.img.xz

**Comment by dianlight** [comment]
If you edit the add-on config via YAML it works as expected, same for all other addons; it is a bug in ha (unconfined, I'm working to find if it is a real bug or a change in addons configuration but all' addons seems affected).

L

**Comment by Icesythe7** [comment]
> If you edit the add-on config via YAML it works as expected, same for all other addons; it is a bug in ha (unconfined, I'm working to find if it is a real bug or a change in addons configuration but all' addons seems affected).
> 
> L

copy that thanks!
