### ISSUE TITLE
[sambanas] possibility to access external smb share in plex?

### ISSUE THREAD

**Issue by mrvnklm** [dianlight/hassio-addons#114]
I was wondering, if this addon could be used to access my NAS share in the plex addon container to mount my external media? It seems like your old Plex addon did this, but I can't think of a way how to achieve the same with the sambanas  addon which is the reason you deprecated the other?

**Comment by dianlight** [comment]
Simply use the `medialibrary` feature. Your external disk will be visible in ha media folder and also official Plex addon see the media folder.

**Comment by MartinKuhl** [comment]
@dianlight could you explain how the use the `medialibrary` function to share a network drive for plex. That is a usecase for a lot of unadvanced people.

**Comment by mrvnklm** [comment]
It is just not possible, as the host system, running busybox does not have `cifs-utils` installed, which is needed to mount smb shares. Here is my approach to solve the issue [mrvnklm/plex-docker-smb-mount](https://github.com/mrvnklm/plex-docker-smb-mount)

**Comment by MartinKuhl** [comment]
thanks a lot
