### ISSUE TITLE
MQTT error when mqtt disabled

### ISSUE THREAD

**Issue by dmoeyers** [dianlight/hassio-addons#116]
Hello,

I see following error in the log although mqtt_enable is set to false:

cont-init: info: running /etc/cont-init.d/mqtt.sh
[22:59:57] ERROR: Got unexpected response from the API: Service not enabled
[22:59:58] WARNING: No MQTT Server found. Homeassistant integration can't work!
cont-init: info: /etc/cont-init.d/mqtt.sh exited 0

Is this normal?

Thanks!

**Comment by dianlight** [comment]
yes if you don't have a MQTT server.
You can use `mqtt_enable` config option to disable.

**Comment by dmoeyers** [comment]
Yes but mqtt_enable was already set to false

**Comment by dianlight** [comment]
The error is the result of a change behavior in HA supervisor API. 
Is not a problem and you can continue the use with the error.

Will be corrected in the next version.

L.

**Comment by dmoeyers** [comment]
Thanks for your quick feedback!
