### ISSUE TITLE
Question: what file system to use for external hard drive

### ISSUE THREAD

**Issue by VentusGallus** [dianlight/hassio-addons#117]
Hi all - Apologies for asking a dumb question but I did not see this in the documentation. I am looking for the best file system to format an external USB hard drive to connect to Home Assistant (on Rasberry pi 4). I am also using Windows 10 so would prefer a file system that is compatible with both.

I tried exFAT but this resulted in problems when creating folders (and presumable files) through SambaNAS. I also tried ext4 but this is not supported by Windows 10. 

Any suggestions?

**Comment by dianlight** [comment]
Support for ExFAT and NTFS released in #120
