### ISSUE TITLE
Partition labels with blanks not supported

### ISSUE THREAD

**Issue by DonKracho** [dianlight/hassio-addons#118]
Maybe this is just an documentation issue?

I found a work around to mount partition labels with blanks. Just have a look with a SSH terminal at /dev/disks/by-label and use the name given there. You will find blanks exchanged by '\x20'. Use the same name in the configuration file (e.g. the label is "Seagate 500 GB" the use Seagate\x20500\x20GB in the config. At least for me this did work.

**Comment by dianlight** [comment]
Fix released in #120
