### ISSUE TITLE
[SambaNas] [10.0.0-nas6]  ID Mount unlabeled partition don't work anymore

### ISSUE THREAD

**Issue by dianlight** [dianlight/hassio-addons#123]
To even start 10.0.0-nas6 I had to disable both options

automount
available_disks_log

otherwise I got the s6-rc warning message.

**However I cannot mount by id with this version**. I've attached a drive as sdb (via SATA) with /dev/sdb1 as a partition which is currently unlabled

`[15:39:35] INFO: MoreDisks to mount:
	**id**:ata-Samsung_SSD_850_EVO_1TB_S3PLNB0J900510X-part1
---------------------------------------------------
[15:39:35] INFO: Mounting disks:
	ata-Samsung_SSD_850_EVO_1TB_S3PLNB0J900510X-part1
---------------------------------------------------
lsblk: /dev/disk/by-label/ata-Samsung_SSD_850_EVO_1TB_S3PLNB0J900510X-part1: not a block device
[15:39:35] INFO: Mounting ata-Samsung_SSD_850_EVO_1TB_S3PLNB0J900510X-part1 of type 
mount: /mnt/ata-Samsung_SSD_850_EVO_1TB_S3PLNB0J900510X-part1: special device /dev/disk/**by-label**/ata-Samsung_SSD_850_EVO_1TB_S3PLNB0J900510X-part1 does not exist.`

_Originally posted by @christophsteckelberg in https://github.com/dianlight/hassio-addons/issues/121#issuecomment-1413865121_

**Comment by comtel2000** [comment]
same here:

```console
[11:51:45] INFO: SSH connection to 192.168.178.108:22222 OK
[11:51:45] INFO: MoreDisks to mount:
	id:wwn-0x5001b448bcde8002-part1
---------------------------------------------------
[11:51:45] INFO: Mounting disks:
	wwn-0x5001b448bcde8002-part1
---------------------------------------------------
lsblk: /dev/disk/by-label/wwn-0x5001b448bcde8002-part1: not a block device
[11:51:45] INFO: Mounting wwn-0x5001b448bcde8002-part1 of type 
mount: /mnt/data/supervisor/media/wwn-0x5001b448bcde8002-part1: special device /dev/disk/by-label/wwn-0x5001b448bcde8002-part1 does not exist.
[11:51:45] WARNING: Host Mount wwn-0x5001b448bcde8002-part1[] Fail!
mount: /media/wwn-0x5001b448bcde8002-part1: special device /dev/disk/by-label/wwn-0x5001b448bcde8002-part1 does not exist.
       dmesg(1) may have more information after failed mount system call.
[11:51:45] WARNING: Fail to mount wwn-0x5001b448bcde8002-part1!
```
I guess "id:" should point to: `dev/disk/by-id/wwn-0x5001b448bcde8002-part1` not `dev/disk/by-label/wwn-0x5001b448bcde8002-part1`

```yaml
moredisks:
  -  id:wwn-0x5001b448bcde8002-part1
```

**Comment by comtel2000** [comment]
last working version is 10.0.0-nas3 (maybe nas4):

```console
-----------------------------------------------------------
 Add-on version: 10.0.0-nas3
 There is an update available for this add-on!
 Latest add-on version: 10.0.0-nas6
 Please consider upgrading as soon as possible.
 System: Home Assistant OS 9.5  (amd64 / generic-x86-64)
 Home Assistant Core: 2023.2.1
 Home Assistant Supervisor: 2023.01.1
-----------------------------------------------------------
..
[12:05:31] INFO: SSH connection to 192.168.178.108:22222 OK
[12:05:31] INFO: More Disks mounting.. id:wwn-0x5001b448bcde8002-part1
[12:05:31] INFO: Disk wwn-0x5001b448bcde8002-part1 is an ID
[12:05:31] INFO: Mount wwn-0x5001b448bcde8002-part1 Success!
[12:05:31] INFO: Success!
cont-init: info: /etc/cont-init.d/automount.sh exited 0

```

**Comment by christophsteckelberg** [comment]
@dianlight Thank you - 10.0.0-nas7 resolved my issue
