### ISSUE TITLE
Symbol % in mqtt sensor usepct 

### ISSUE THREAD

**Issue by thetux07** [dianlight/hassio-addons#126]
Hello 
It’s possible to delete % symbol in state sensor ? 
thank you

**Comment by gourdo1** [comment]
I noticed this also. Can't graph **_sensor.sambanas_fsuse_pct_*_** in a Lovelace graph either because the '%' sign is part of the tntity output so it's not recognized as a numeric value.

**Comment by dianlight** [comment]
Fixed in nas8 release
