### ISSUE TITLE
Samba share - access from another subnet

### ISSUE THREAD

**Issue by try4cou** [dianlight/hassio-addons#127]
Hey everyone,

I'd like to ask for your help to setup my config properly. I've got a samba share on my local network with the 192.168.2.6 IP address. I can access the share with no problem in 192.168.2.x subnet but I'd like to open it from my another subnet 192.168.1.x with no success. 
Please help me, how i can set it up?

Thanks in advance,
Drew

**Comment by dianlight** [comment]
Check the `allow_hosts` parameter. Also the ha network config need to know the gw for the 192.168.1.x network. ( to help you better I need to know your network topology with gw and routers ). 

If you connect from a window pc remember that only pro and enterprise win version supports inter networks shares and only within a domain controller.

The first test is: from the client on 1.x network you can ping your ha? If not you need to configure yours network first.

L.

**Comment by try4cou** [comment]
Hey dianlight,
so i've got a main router on the 192.168.1.1 that I got from the provider. I've got an android box in this subnet and my own router on the 192.168.2.1 with all my devices even HA in this subnet. I can't use the android box with my router so that's why that in the other subnet. On the android box I'd like to setup an access to my samba share on HA but I can't even ping the device. However I can ping android box from my 192.168.2.x subnet.
My HA network setup: 
IP: 192.168.2.6/24
GW: 192.168.2.1
DNS:  192.168.2.1

**Comment by dianlight** [comment]
If I understand correctly (below drawing) the addresses coming from the 2.x network are NATed to an address from the 1.x network made by your router and the provider's router doesn't know the 2.x network.

The alternatives are 2:
- You set up on the provider's router a static route for the 2.x network with GW to your router address on the 1.x network. Remove NAT.
- Leave NAT on your router and forward SMB, RPC ports to HA ( 192.168.2.6 ). From the android you will mount the disks pointing as server the external address of your router on the 1.x network

![image](https://user-images.githubusercontent.com/365884/217006629-386fa945-ffb0-4155-a55c-16a53698aae8.png)


Not to be rude but in any case this has nothing to do with the addon but it's network configuration.
L.

**Comment by try4cou** [comment]
Thank you dianlight! It's definitely not an addon issue i was just curious how I can solve my problem and needed some help. You helped me a lot, however I don't have any access to setup my routing on the router of the provider, not even a routing rule. Probably i need another device for using as NAS server in this case. 
Thank you once more for your help!
