### ISSUE TITLE
Significantly higher CPU load with "Samba NAS" addon running

### ISSUE THREAD

**Issue by christschnman** [dianlight/hassio-addons#128]
Hi, 

thx for your great work, running perfectly, but...

i noticed a slightly higher CPU load when running this addon in HA OS on Raspberry Pi 4.
Usually with 7 active addons i have an average cpu idle load of 3% and a temperature of about 38-39°C (passively cooled). When I run your addon, the CPU load increases to an average of 7-8% and the temperature to 40-41°.

Please don't get me wrong, that's not a problem in principle, but I'm wondering if there's a bug or if I configured something wrong. In comparison, the load on the Samba Share Addon remains within the normal range, which means that I can rule out that the Samba protocol is generally causing a higher load.

![Unbenannt](https://user-images.githubusercontent.com/118983402/217170189-5420403d-db47-4af6-b7f7-25a91a356851.png)

**Comment by dianlight** [comment]
The cpu is used by mqtt integration to report iostats every 2sec. If you don't need the sensors simply disable mqtt or use legacy mqtt mode without the last feature ( the update is x10 slower)

Original samba addon also don't has wsdd and other demons so the mem and cpu can be higher.

I noted to report this in documentation but I never done..

L.
