### ISSUE TITLE
moredisks option not detecting USB HDD formatted in NTFS

### ISSUE THREAD

**Issue by sthorley** [dianlight/hassio-addons#129]
Hi, I was trying to turn my HomeAssistant Raspberry pi4 into a budget NAS by sharing out an attached USB HDD using this addon.

I can see in the HassOS terminal that the disk is identifed by the host and labeled "Tank"
<img width="1139" alt="Screenshot 2023-02-08 at 1 37 35 pm" src="https://user-images.githubusercontent.com/6040168/217545538-1570afa4-373f-4de9-8450-a27850350879.png">

However the log file for SambaNAS says no disks were labeled.

```
`s6-rc: info: service init-automount: starting
[13:30:16] INFO: Protection Mode is true
[13:30:17] INFO: MoreDisk or Automount option found!
---------------------------------------------------
Supported fs: ext3 ext2 ext4 squashfs vfat msdos f2fs fuseblk ntfs3 exfat btrfs xfs
Supported fusefs: 
---------------------------------------------------
[13:30:17] INFO: MediaLibrary disabled in config. Disk are mounted only for this addon!
---------------------------------------------------
[13:30:17] INFO: No Disk with labels.
---------------------------------------------------
[13:30:17] INFO: No MoreDisks to mount
s6-rc: info: service init-automount successfully started
s6-rc: info: service init-samba: starting`
```

Is mounting an external NTFS drive supported on Raspberry Pi4 - Home Assistant OS 9.5?

Any ideas for how to get this to work?

**Comment by dianlight** [comment]
I need the full log to understand.
Meanwhile you can try to disable protection.

L.
