### ISSUE TITLE
SambaNAS to use my external HDD in HA

### ISSUE THREAD

**Issue by Jens-Wymeersch** [dianlight/hassio-addons#135]
I hoped that I didn't need to get ssh root access via this method, but it looks like I do...  And for the hell of me, I'm not able to get this working. Here is what i did 
1. create key on MacOS with ssh-keygen -t ed25519 -C "your_email@example.com"
2. cat is_rsa.pub to see public key - which looks something like `ssh-ed25519 KEYKEYKEY your_email@example.com`
3. copy KEYKEYKEY and save authorized_keys (encryption ISO 8859-1, LF and no extension) in SanDisk (titled CONFIG)
4. Plug the key in machine with homeassistant 
5. Go to the SSH Addon - type `ha os import`
6. Go to the mac terminal and us the following command `ssh root@homeassistant.local -p 22222 -i is_rsa `

I'm getting the following error : `Permission denied (publickey)`

**Comment by dianlight** [comment]
I didn't understand what you expect as an answer!

Why an Ed25519 key? But above all, do you know what an Ed25519 key is? And again are you sure HASSOS supports Ed25519?

I suggest you read the documentation before trying random commands found on the internet. Or at least try the commands you find on the official documentation.

[A good start!](https://github.com/dianlight/hassio-addons/blob/master/sambanas/DOCS.md#option-medialibrary-optional-exteprimental)

L.
