### ISSUE TITLE
can't skip update

### ISSUE THREAD

**Issue by Santanachia** [dianlight/hassio-addons#138]
I have an older version of HA installed and I can't install the Samba NAS update. Unfortunately, I can't skip it. Please allow me to skip the update (or perform the update).

![image](https://user-images.githubusercontent.com/4628507/223375592-a71ef6f7-3900-4165-a610-fedf82987fda.png)

**Comment by dianlight** [comment]
New versions of the addon use features that have been available since 2023.01.1. Hence the requirement.

I admit my ignorance but I don't think I can command from the addon configuration the possibility to skip or not the version.
