### ISSUE TITLE
trouble adding repository 

### ISSUE THREAD

**Issue by scooper1** [dianlight/hassio-addons#139]
when adding https://github.com/dianlight/hassio-addons
i get the error 

Cmd('git') failed due to: exit code(128) cmdline: git clone -v --recursive --depth=1 --shallow-submodules -- https://github.com/dianlight/hassio-addons/tree/master/sambanas /data/addons/git/8142c285 stderr: 'Cloning into '/data/addons/git/8142c285'... fatal: repository 'https://github.com/dianlight/hassio-addons/tree/master/sambanas/' not found '

**Comment by dianlight** [comment]
I need to know your environment to help you.
When adding where? Hassos version? Host system? Ha version? Etc.

**Comment by scooper1** [comment]
hassos 9.5
running on proxmox vm

**Comment by scooper1** [comment]
it added ok 
there was some reports of github having download problems this morning  so likely to be that so closing
