### ISSUE TITLE
Unable to add timeMachine: true to configuration

### ISSUE THREAD

**Issue by ashdwells** [dianlight/hassio-addons#140]
Hi

I am trying to add timemachine: true  to the configuration but there is no option under the UI and if I click 3 dots to edit in yaml it wont let me do anything. How else can I add it?

**Comment by dianlight** [comment]
Some version of HA has issue on UI config. Yaml config should work. Can you post your config?

**Comment by ashdwells** [comment]
The problem is I can’t access the yaml config to change it or share it and need to simple add timemachine: true to it but can’t do it on the yaml
