### ISSUE TITLE
[FR] Question: read only shares possible?

### ISSUE THREAD

**Issue by erkr** [dianlight/hassio-addons#141]
Hi, great to see a samba fork with much more options. Besides different users, I would like to make shares read only for particular users. Is that possible? Don’t see how to do that in the options / acl 
Best Eric

**Comment by codyrocco** [comment]
Readonly share/mount could be usefull, because - call me stupid, call me blind :) - i didn't find a way to safe unmount drives

**Comment by erkr** [comment]
Although I trust my user, randsomeware is what concerns me

**Comment by dianlight** [comment]
implemented

**Comment by erkr** [comment]
Thanks I will give it a try 🙏

**Comment by erkr** [comment]
Works great, thanks!!!
