### ISSUE TITLE
exFAT module not found in modules.dep

### ISSUE THREAD

**Issue by caraar12345** [dianlight/hassio-addons#142]
Hey! Samba NAS is exactly the kind of addon I've needed for a while.

Seems that the exFAT support doesn't want to work though: `modprobe: module exfat not found in modules.dep`.

Please let me know if any more information would be useful.

Any ideas?

```
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service base-addon-banner: starting
-----------------------------------------------------------
 Add-on: Samba NAS
 Expose Home Assistant disc with SMB/CIFS
-----------------------------------------------------------
 Add-on version: 10.0.0-nas8
 You are running the latest version of this add-on.
 System: Home Assistant OS 10.0.rc3  (amd64 / generic-x86-64)
 Home Assistant Core: 2023.4.0
 Home Assistant Supervisor: 2023.04.0
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-automount: starting
[11:11:31] INFO: Protection Mode is false
[11:11:31] INFO: MoreDisk or Automount option found!
modprobe: module ntfs3 not found in modules.dep
[11:11:31] WARNING: ntfs3 module not available!
modprobe: module exfat not found in modules.dep
[11:11:31] WARNING: exfat module not available!
modprobe: module xfs not found in modules.dep
[11:11:31] WARNING: xfs module not available!
---------------------------------------------------
Supported fs: ext3 ext2 ext4 squashfs vfat msdos iso9660 btrfs
---------------------------------------------------
[11:11:32] INFO: MediaLibrary disabled in config. Disk are mounted only for this addon!
---------------------------------------------------
[11:11:32] INFO: Available Disk Labels:
[11:11:32] INFO: 	Ventoy[exfat]
[11:11:32] INFO: 	VTOYEFI[vfat]
---------------------------------------------------
[11:11:32] INFO: No MoreDisks to mount
[11:11:32] INFO: Automount is Enabled!
---------------------------------------------------
[11:11:32] INFO: Mounting disks:
	VTOYEFI
	Ventoy
---------------------------------------------------
[11:11:32] WARNING: Your VTOYEFI is vfat. Permissions and ACL don't works and this is an EXPERIMENTAL support
[11:11:32] INFO: Mount VTOYEFI[vfat] Success!
[11:11:32] WARNING: Your Ventoy is exfat. Permissions and ACL don't works and this is an EXPERIMENTAL support
mount: /mnt/Ventoy: unknown filesystem type 'exfat'.
       dmesg(1) may have more information after failed mount system call.
[11:11:32] WARNING: Fail to mount Ventoy!
````

**Comment by caraar12345** [comment]
Hey - thanks! Will open an issue with them now. :)

**Comment by salvadornico** [comment]
> Hey - thanks! Will open an issue with them now. :)

Hi, do you mind linking to your issue on the HassOS repo? I'm having the same problem as well and would like to chime in, but can't find your issue there. Thanks!

**Comment by FritsOV** [comment]
Hello, I have exact the same problem. 
I have an fat32, a ntfs and they worked fine until recently
So it worked before my crash and reinstallation HAS and restore  add on from backup. 

I am running this on a Pi4 with 8 GB mem.

**Comment by dianlight** [comment]
> Hello, I have exact the same problem. 
> 
> I have an fat32, a ntfs and they worked fine until recently
> 
> So it worked before my crash and reinstallation HAS and restore  add on from backup. 
> 
> 
> 
> I am running this on a Pi4 with 8 GB mem. 
> 
> 
> 
> 
> 
> 

Can you post your log? The hassos has the modules in aarch64 versions.

**Comment by FritsOV** [comment]
> > Hello, I have exact the same problem.
> > I have an fat32, a ntfs and they worked fine until recently
> > So it worked before my crash and reinstallation HAS and restore  add on from backup.
> > I am running this on a Pi4 with 8 GB mem.
> 
> Can you post your log? The hassos has the modules in aarch64 versions.

Sure:
Have to change drives back to the pi 4 but have also a Lenovo thin with only HAS installed. i post a part from the log wich includes the warning errors. 



s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
Log level is set to WARNING
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-automount: starting
modprobe: module ntfs3 not found in modules.dep
[22:07:15] WARNING: ntfs3 module not available!
modprobe: module exfat not found in modules.dep
[22:07:15] WARNING: exfat module not available!
modprobe: module xfs not found in modules.dep
[22:07:15] WARNING: xfs module not available!
---------------------------------------------------
Supported fs: ext3 ext2 ext4 squashfs vfat msdos iso9660 btrfs
---------------------------------------------------
---------------------------------------------------
---------------------------------------------------
---------------------------------------------------
---------------------------------------------------
[22:07:19] WARNING: Your Elements is ntfs. This is an EXPERIMENTAL support
mount: /mnt/Elements: unknown filesystem type 'ntfs3'.
       dmesg(1) may have more information after failed mount system call.
[22:07:19] WARNING: Fail to mount Elements!
[22:07:19] WARNING: Your Maxtor 80GB is exfat. Permissions and ACL don't works and this is an EXPERIMENTAL support
mount: /mnt/Maxtor 80GB: unknown filesystem type 'exfat'.
       dmesg(1) may have more information after failed mount system call.
[22:07:19] WARNING: Fail to mount Maxtor 80GB!
s6-rc: info: service init-automount successfully started
s6-rc: info: service init-smartd: starting
s6-rc: info: service init-samba: starting
s6-rc: info: service hd-idle: starting
s6-rc: info: service hd-idle successfully started
smartctl 7.3 2022-02-28 r5338 [x86_64-linux-6.1.25] (local build)
Copyright (C) 2002-22, Bruce Allen, Christian Franke, www.smartmontools.org
=== START OF ENABLE/DISABLE COMMANDS SECTION ===
SMART Enabled.

**Comment by dianlight** [comment]
> Had some problems with the pi and had to reinstall and restore backup. now i see that the Pi is working fine with the nas and loads all the modules.

So the pi works?  

It is simple, the e intel/amd has no compiled modules for ntfs and exfat so this addon can't mount the disk. As I suggest open an issue on hassos repository I can't do anything.

L.

**Comment by FritsOV** [comment]
Till yesterday it did. But this morning all drives were not visible. 
after a reboot the exfat is visible and the ntfs drive is not. 

the logfile is:
Expose Home Assistant disc with SMB/CIFS
-----------------------------------------------------------
 Add-on version: 10.0.0-nas8
 You are running the latest version of this add-on.
 System: Home Assistant OS 10.1  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2023.5.3
 Home Assistant Supervisor: 2023.04.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
Log level is set to WARNING
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-automount: starting
---------------------------------------------------
Supported fs: ext3 ext2 ext4 squashfs vfat msdos f2fs fuseblk ntfs3 exfat btrfs xfs
Supported fusefs: 
---------------------------------------------------
---------------------------------------------------
---------------------------------------------------
---------------------------------------------------
---------------------------------------------------
[10:15:32] WARNING: Your Elements is ntfs. This is an EXPERIMENTAL support
mount: /mnt/Elements: wrong fs type, bad option, bad superblock on /dev/sdc1, missing codepage or helper program, or other error.
       dmesg(1) may have more information after failed mount system call.
[10:15:32] WARNING: Fail to mount Elements!
[10:15:32] WARNING: Your Maxtor 80GB is exfat. Permissions and ACL don't works and this is an EXPERIMENTAL support
s6-rc: info: service init-automount successfully started
s6-rc: info: service init-smartd: starting
s6-rc: info: service init-samba: starting
s6-rc: info: service hd-idle: starting

**Comment by dianlight** [comment]
> mount: /mnt/Elements: wrong fs type, bad option, bad superblock on /dev/sdc1, missing codepage or helper program, or other error.

Your disk had a superblock corruption, Try to attach to a Windows PC and check for bad blocks.

**Comment by FritsOV** [comment]
Wich disk are you refering to? is it the ntfs or the exfat disk?

and after a reboot :(

----------------------------------------------------------
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
Log level is set to WARNING
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-automount: starting
modprobe: module ntfs3 not found in modules.dep
[15:17:20] WARNING: ntfs3 module not available!
modprobe: module exfat not found in modules.dep
[15:17:20] WARNING: exfat module not available!
modprobe: module xfs not found in modules.dep
[15:17:20] WARNING: xfs module not available!

**Comment by dianlight** [comment]
> mount: /mnt/Elements: wrong fs type, bad option, bad superblock on /dev/sdc1, missing codepage or helper program, or  other error.

**Comment by codyrocco** [comment]
1. use these instructions in a linux enviroment: https://developers.home-assistant.io/docs/operating-system/getting-started/
