### ISSUE TITLE
Problems connecting with ssh key

### ISSUE THREAD

**Issue by ScorpSoul** [dianlight/hassio-addons#144]
Hi, I'm trying to setup samba nas and it's failing to connect to root

---------------------------------------------------
Supported fs: ext3 ext2 ext4 squashfs vfat msdos iso9660 btrfs
---------------------------------------------------
[09:47:45] INFO: MediaLibrary option found!
Warning: Permanently added '[192.168.31.200]:22222' (ED25519) to the list of known hosts.
Load key "/root/.ssh/id_rsa": error in libcrypto
root@192.168.31.200: Permission denied (publickey).
s6-rc: warning: unable to start service init-automount: command exited 128
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
/run/s6/basedir/scripts/rc.init: fatal: stopping the container.

I've tried to create the key manually, through ssh, I've set up SSH Terminal and that ssh configurator 22222, I can connect with putty but not with this addon.
Could you provide me some info on how to proceed? I followed your docs as best as I could but I could not get it to work. I'm using HA OS.

Thanks

**Comment by dianlight** [comment]
The error is about the impossibility to write in the config path. 
I need to have the full log to help you.  ( please add as attach not inline )

L.

**Comment by ScorpSoul** [comment]
`s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service base-addon-banner: starting
-----------------------------------------------------------
 Add-on: Samba NAS
 Expose Home Assistant disc with SMB/CIFS
-----------------------------------------------------------
 Add-on version: 10.0.0-nas8
 You are running the latest version of this add-on.
 System: Home Assistant OS 10.1  (amd64 / generic-x86-64)
 Home Assistant Core: 2023.4.6
 Home Assistant Supervisor: 2023.04.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-automount: starting
[10:08:55] INFO: Protection Mode is false
[10:08:55] INFO: MoreDisk or Automount option found!
modprobe: module ntfs3 not found in modules.dep
[10:08:55] WARNING: ntfs3 module not available!
modprobe: module exfat not found in modules.dep
[10:08:55] WARNING: exfat module not available!
modprobe: module xfs not found in modules.dep
[10:08:55] WARNING: xfs module not available!
---------------------------------------------------
Supported fs: ext3 ext2 ext4 squashfs vfat msdos iso9660 btrfs
---------------------------------------------------
[10:08:55] INFO: MediaLibrary option found!
Warning: Permanently added '[192.168.31.200]:22222' (ED25519) to the list of known hosts.
Load key "/root/.ssh/id_rsa": error in libcrypto
root@192.168.31.200: Permission denied (publickey).
s6-rc: warning: unable to start service init-automount: command exited 128
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
/run/s6/basedir/scripts/rc.init: fatal: stopping the container.
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service base-addon-log-level: stopping
s6-rc: info: service base-addon-log-level successfully stopped
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service base-addon-banner: stopping
s6-rc: info: service base-addon-banner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped`

**Comment by ScorpSoul** [comment]
I've managed to make it work, I've pasted the ssh key on VS and pasted it again on the configuration and it worked.. I have no idea if it was just a coincidence but it's working. Thanks for the great addon!
