### ISSUE TITLE
Cannot use medialibrary and timemachine

### ISSUE THREAD

**Issue by iBobik** [dianlight/hassio-addons#148]
Time machine can use only root of the share, not subfolders, but medialibrary option moved mount point of the disk in moredisks to the media share.

I know I can do symlinks to "move" all sparsebundles to the root directory, but this will require to do it always when new backup was created.

**Comment by dianlight** [comment]
I don't understand. 
Also with medialibrary option every disk hash his root shared; simply use the root not the media.
If you post your addon starting log I can help you better.

L.

**Comment by googanhiem** [comment]
Since recent updates I can't use timemachine. I'm still using the SSH key method, as removing the key stopped smb from working.
