### ISSUE TITLE
Share subfolders dissapearing

### ISSUE THREAD

**Issue by QbaF** [dianlight/hassio-addons#149]
From time to time (at least once per day) the share subfolders disappear (SSD via USBD 3.0). They exist but are not accessible nor visible. Restarting add-on make it visible again.

**Comment by dianlight** [comment]
Can you post your addon starting log? If you are on a Rpi installation monitor the power, sometime it can be a power issue.

L.

**Comment by QbaF** [comment]
This is SambaNAS starting log
https://pastebin.com/LaAVZuyj

HA is not on RPI, no powier problems, I guess.

**Comment by dianlight** [comment]
There is a problem on the mqtt report so the watchdog daemon are killed. I think is a sort of timeout on the internal shared process thread.
I need to know your environment to replicate and correct so I need all starting addon's logs not only the error part.

**Comment by QbaF** [comment]
Sorry, is it the part missing?:
```
[21:40:59] INFO: Enabling S.M.A.R.T for /dev/sdc
smartctl 7.3 2022-02-28 r5338 [x86_64-linux-6.1.29] (local build)
Copyright (C) 2002-22, Bruce Allen, Christian Franke, www.smartmontools.org
[21:40:59] INFO: Interfaces: enp0s25 
=== START OF ENABLE/DISABLE COMMANDS SECTION ===
SMART Enabled.
SMART Attribute Autosave Enabled.
```

**Comment by dianlight** [comment]
No I need all the log from the beginning. 
Restart the addon, wait for the full start and post all log from.

L.

**Comment by QbaF** [comment]
But this is exactly how the logs in SambaNAS work for me.  Every time I put logs from the beginning (after clearing).
After restarting firstly I do have a few info about stopping the addon, then the log is cleared, then this info (which does not always start from exactly this same point - it looks like clearing logs is not always at the same time.
At this restart my logs in SambaNAS start with this:
![image](https://github.com/dianlight/hassio-addons/assets/57077178/9c68e4c4-c990-421f-9c37-42902fc827e0)

**Comment by dianlight** [comment]
The log is missing the env enquirer and information part. Too bad post it manually form your system information panel in ha. I need to know your hassos + core version and architecture. Any other information on your env can be useful like usb hub, keys devices etc.

L

**Comment by QbaF** [comment]
Home Assistant 2023.6.2
Supervisor 2023.06.2
Operating System 10.3
Frontend 20230608.0 - latest
SambaNAS 10.0.2-nas1

smartctl 7.3 2022-02-28 r5338 [x86_64-linux-6.1.34] (local build)

But yesterday I've updated the add-on to the latest version 10.0.2-nas1 (as well as HA Core) and I just checked that 12+ hours the folders are in place...
In logs there were new problems
https://pastebin.com/RQz5t87s

But just after restarting, they were gone.

**Comment by dianlight** [comment]
They are not errors. You have a host 'Fujitsu' in network that send workgroup broadcast but the name is not in the dns on local domain so is not resolved. You can just ignore.

L.

**Comment by QbaF** [comment]
So it looks ok in the new version. No disappearing.

**Comment by QbaF** [comment]
Unfortunatelly I just found folder NAS Seagate empty again. Looks like previous test were too short.
Any additional data from me needed?

New for me in logs:
````
2023-06-23 01:00:09,797:wsdd INFO(pid 322): deleted address fe80::4c00:f0ff:fe7e:59a7%vethbf9efd1
sys_path_to_bdev() failed for path [.]!
sys_path_to_bdev() failed for path [.]!
sys_path_to_bdev() failed for path [.]!
sys_path_to_bdev() failed for path [.]!
```
It is exactly when Samba Backup add-on started. But it has priority "INFO"

[full add-on log I can see](https://pastebin.com/N9UNbcef)

**Comment by dianlight** [comment]
I don't know how Samba Backup add-on work but now you can add a network storage of type cifs direcly from ha.
Meanwhile can you start the backup manually and check if is the addon the cause or simply is the first access after the cause?

The problem is a block expire, it can be the disk spin-down. Do you have smart enable? Can you post the addon config?

L.

**Comment by QbaF** [comment]
I did add network storage in HA directly. But I think for storage connected vis USB still Samba NAS is necessary. The other way is for network storage.

Manually started backup do works. It worked as well in the previous Samba NAS version (when I made this issue). And do not cause the problem with vanishing subfolders. It works, as well, in auto mode (some problem with Samba Backup is the backup can not run longer than 180 mins).

Disk spin, if I understand, is only for HDD discs. I use SSD.

[my Samba NAS config](https://pastebin.com/sT85suis)

**Comment by dianlight** [comment]
You can try:
- disable smart -->  `enable_smart`:false
- disable legacy mqtt --> `mqtt_use_legacy_entities`:false

I see also many log errors in `mqtt_use_legacy_entities`, is working? ( I yes! Tty to check the sensors history when the error accour ).

L.
