### ISSUE TITLE
ERROR: Got unexpected response from the API: Service not enabled

### ISSUE THREAD

**Issue by gmbirk** [dianlight/hassio-addons#15]
Just installed Samba NAS and after I start it it shuts down.  Log is below

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] automount.sh: executing... 
[17:35:10] INFO: Protection Mode is false
[17:35:11] WARNING: MoreDisk option found!
[17:35:11] INFO: More Disks mounting.. ExternalHD
[17:35:11] INFO: Mount ExternalHD
[17:35:15] INFO: Success!
[cont-init.d] automount.sh: exited 0.
[cont-init.d] mqtt.sh: executing... 
[17:35:16] ERROR: Got unexpected response from the API: Service not enabled
[cont-init.d] mqtt.sh: exited 0.
[cont-init.d] samba.sh: executing... 
[17:35:20] INFO: Hostname: homeassistant
tdbsam_open: Converting version 0.0 database to version 4.0.
tdbsam_convert_backup: updated /var/lib/samba/private/passdb.tdb file.
Added user XXXX.
[cont-init.d] samba.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[17:35:24] INFO: Starting the MQTT daemon for disks info...
[17:35:24] INFO: Starting the AVAHI daemon for homeassistant...
nmbd version 4.12.7 started.
Copyright Andrew Tridgell and the Samba Team 1992-2020
Server version: avahi 0.7; Host name: homeassistant.local
daemon_ready: daemon 'nmbd' finished starting up and ready to serve connections
smbd version 4.12.7 started.
Copyright Andrew Tridgell and the Samba Team 1992-2020
INFO: Profiling support unavailable in this build.
daemon_ready: daemon 'smbd' finished starting up and ready to serve connections
Established under name 'homeassistant'
[17:35:26] INFO: Sending MQTT autodiscovery...
Error: -h argument given but no host specified.
Use 'mosquitto_pub --help' to see usage.
Got SIGTERM: going down...
Got SIGTERM, quitting.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] mqtt.sh: executing... 
[17:35:27] INFO: MQTT cleanup.
Error: -h argument given but no host specified.
Use 'mosquitto_sub --help' to see usage.
[cont-finish.d] mqtt.sh: exited 1.
[cont-finish.d] umount.sh: executing... 
[17:35:28] INFO: Unmount drivers.
umount: /dev: target is busy.
[cont-finish.d] umount.sh: exited 32.
[cont-finish.d] done.
[s6-finish] waiting for services.
s6-svwait: fatal: unable to subscribe to events for /var/run/s6/services/s6-fdholderd: Read-only file system
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.

**Comment by gmbirk** [comment]
I did not have Mosquitto broker add-in installed .  Once I added it, everything worked.

**Comment by dianlight** [comment]
Fixed in the _dev branch. Will be released in the next release.
