### ISSUE TITLE
10.0.2-nas mqtt

### ISSUE THREAD

**Issue by cokeman0** [dianlight/hassio-addons#151]
After upgrade to latest version.

Mqtt is populated with entity but no data.

All are filed with unknown

**Comment by dianlight** [comment]
sorry! :) A last commit with too manny optimizations! :).
 The correction is in the way.

**Comment by cokeman0** [comment]
Thanks

Med venlig hilsen

Michael Dahl

man. 19. jun. 2023 17.31 skrev Lucio Tarantino ***@***.***>:

**Comment by dianlight** [comment]
Fixed in 10.0.2-nas1
