### ISSUE TITLE
HA restart- 10.0.2-nas1 

### ISSUE THREAD

**Issue by cokeman0** [dianlight/hassio-addons#155]
Hi,

After a HA restart, all MQTT sensors are unknown, a reload of sambanas, fixes that....

perhaps you can detect a restart of HA, and repopulate MQTT?

**Comment by ScorpSoul** [comment]
Happening to me also

**Comment by cokeman0** [comment]
Sorry, but not fixed in ver2

**Comment by ScorpSoul** [comment]
I confirm


A sábado, 24/06/2023, 11:39, cokeman0 ***@***.***> escreveu:
