### ISSUE TITLE
❓ ntfs3 support

### ISSUE THREAD

**Issue by MarhxD** [dianlight/hassio-addons#160]
### Addon

SambaNAS

### Your request

Hi, 

i'm new to HA and have question about NTFS3 drives support

addon log shows that it cannot mount my drive, cause ntfs3 modules is not found
this means that my HASSOS does not support this filesystem?
is there any way that i can add driver or something?

here's log

-----------------------------------------------------------
 Add-on: Samba NAS
 Expose Home Assistant disc with SMB/CIFS
-----------------------------------------------------------
 Add-on version: 10.0.2-nas2
 You are running the latest version of this add-on.
 System: Home Assistant OS 10.3  (amd64 / generic-x86-64)
 Home Assistant Core: 2023.6.3
 Home Assistant Supervisor: 2023.06.4
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-automount: starting
[10:27:52] INFO: Protection Mode is false
[10:27:52] INFO: MoreDisk or Automount option found!
modprobe: module ntfs3 not found in modules.dep
[10:27:52] WARNING: ntfs3 module not available!
modprobe: module exfat not found in modules.dep
[10:27:52] WARNING: exfat module not available!
modprobe: module xfs not found in modules.dep
[10:27:52] WARNING: xfs module not available!
---------------------------------------------------
Supported fs: 	ext3	ext2	ext4	squashfs	vfat	msdos	iso9660	btrfs
---------------------------------------------------
[10:27:53] INFO: MediaLibrary option found!
---------------------------------------------------
[10:27:53] INFO: Available Disk Labels:
[10:27:53] INFO: 	CONFIG[vfat]
[10:27:53] INFO: 	Marh6TB[ntfs]
---------------------------------------------------
[10:27:54] INFO: No MoreDisks to mount
[10:27:54] INFO: Automount is Enabled!
---------------------------------------------------
[10:27:54] INFO: Mounting disks:
	CONFIG
	Marh6TB
---------------------------------------------------
[10:27:54] WARNING: Your CONFIG is vfat. Permissions and ACL don't works and this is an EXPERIMENTAL support
[10:27:54] INFO: Mount CONFIG[vfat] Success!
[10:27:54] WARNING: Your Marh6TB is ntfs. This is an EXPERIMENTAL support
mount: /mnt/Marh6TB: unknown filesystem type 'ntfs3'.
       dmesg(1) may have more information after failed mount system call.
[10:27:54] WARNING: Fail to mount Marh6TB!

**Comment by dianlight** [comment]
The x86_64 architecture don't has ntfs3 modules in the hassos image. I suggest you to search in operating system GitHub repository issue. 

L

**Comment by MarhxD** [comment]
thanks
