### ISSUE TITLE
❓ [Sambanas] Create separate addon for moredisks/medialibrary

### ISSUE THREAD

**Issue by ElVit** [dianlight/hassio-addons#164]
### Addon

SambaNAS

### Your request

Hi,
first thank you for this very nice addon "sambanas".
I like the new feature to mount existing partitions (e.g. hassos_data) or external drives and then show them in the medialibrary.
But I also want to use my custom samba server where I write my own smb.conf file.
For example I don't want to see the partition "hassos_data" as a smb share.

Would it maybe possible to create a separate addon where I can mount additional partitions or disks and then add them to the medialibrary?
(That means without creating the smb server)

Thanks.

**Comment by dianlight** [comment]
You can remove the exposed data partition with the acl disable command.

I'm working on a separate addon to managing only the mount/umount of usb disk but it depends on some experimental supervisor api not yet in the main stream that depends on operating system dbus mount system also not yet released.
I will release when can be used with released hassos.

L.

**Comment by ElVit** [comment]
Ok cool. That sounds great. Looking forward when the addon will be released.

**Comment by sorryusernameisalreadytaken** [comment]
> You can remove the exposed data partition with the acl disable command.
Can you explain this a bit more? What is the mentioned acl command?

> I'm working on a separate addon to managing only the mount/umount of usb disk but it depends on some experimental supervisor api not yet in the main stream that depends on operating system dbus mount system also not yet released. I will release when can be used with released hassos.
> 
> L.
That sound nice. Is the mentioned experimental supervisor api definitely comming to main stream? Did you know that. Did you habe some links for me?

**Comment by dianlight** [comment]
> > You can remove the exposed data partition with the acl disable command.
> 
> 
> 
> Can you explain this a bit more? What is the mentioned acl command?

Look the addon documentation. With acl configuration you can set not only the access rights for one share but also disable it.

> 
> 
> 
> > I'm working on a separate addon to managing only the mount/umount of usb disk but it depends on some experimental supervisor api not yet in the main stream that depends on operating system dbus mount system also not yet released. I will release when can be used with released hassos.
> 
> > 
> 
> > L.
> 
> 
> 
> That sound nice. Is the mentioned experimental supervisor api definitely comming to main stream? Did you know that. Did you have some links for me?

No sorry. The PR is not yet ready, in the lasts months I haven't time to work on it. 

L.

**Comment by ve6rah** [comment]
I don't know if this is the right place to track it or not, but I am seriously interested in the idea of the add-on that simply mounts USB drives. It is such a major oversight in the operating system that we have no way of mounting USB drives. Realistically, I don't actually have any need for the SMB part of this add-on. All I need is a way to mount USB drives, but this add-on seemed to be the only way to go.

**Comment by dianlight** [comment]
> I don't know if this is the right place to track it or not, but I am seriously interested in the idea of the add-on that simply mounts USB drives. It is such a major oversight in the operating system that we have no way of mounting USB drives. Realistically, I don't actually have any need for the SMB part of this add-on. All I need is a way to mount USB drives, but this add-on seemed to be the only way to go.

Is not so simple. At the moment the only supported mode to add external storage in HASOS is via network share. So an addon that only mount the disks is not useful because you can't have any access outside the addon itself.
We need a PR for HASOS that adds functionality on both the host and supervisor layers which cannot be done by an addon.

I started doing it but the requirements for a merge were too onerous and I don't have all the time necessary to dedicate to it.

L.
