### ISSUE TITLE
❓ [SambaNAS] macOS Error 100093 when copying files into the share

### ISSUE THREAD

**Issue by enslaved2die** [dianlight/hassio-addons#165]
I cant copy files into the samba share always getting error 100093.
Any ideas what options I should check to get it working?

**Comment by zephaone** [comment]
Seems to be a bug with MacOS. Having same issue, but works fine from windows in VM

**Comment by lead0r** [comment]
I don't really have a problem with macOS. What filesystem is the external drive using? macOS filesystem and ext4 are not really compatible for example, so it might be a problem with an incompatible character in the file name you are trying to copy?

**Comment by dianlight** [comment]
I use the addon in all Mac environment and I don't have any problem. I suggest you to reopen the issue with Bug type with all the needing information to find a resolution.

L.
