### ISSUE TITLE
✨ [SambaNAS] Option to Automatically fix NTFS errors

### ISSUE THREAD

**Issue by jasonheight** [dianlight/hassio-addons#169]
### Addon

SambaNAS

### Checked

- [X] I have searched in the discussions & issues that it was not already covered

### Is your feature request related to a problem? Please describe

Option to automatically run fsck/ntfsfix on external ntfs drives reboot

### Describe the solution you'd like

If the drive is detected as ntfs, and the mount command fails attempt to automatically fix (based on an option) the drive using fsck or ntfsfix and then re-attempt remount.

Currently the mount command will fail with the following output:
[18:25:18] WARNING: Your Seagate Expansion Drive is ntfs. This is an EXPERIMENTAL support
mount: /mnt/Seagate Expansion Drive: wrong fs type, bad option, bad superblock on /dev/sda2, missing codepage or helper program, or other error.

Unfortunately I have had a couple of times when my raspberry pi device has hung and i have needed to yank the power cable (I know) rather than shutdown safely.

WORKARROUND
Currently if the above occurs, i can connect the drive to a windows machine and it will correct the drive error.

**Comment by sebastiangebosz** [comment]
Does this work in the current version?  For me the disk does not mount.  For example, after a power failure at home.  I have to scan in Windows and connect again.
