### ISSUE TITLE
[Samba NAS] Support for other fs

### ISSUE THREAD

**Issue by gabrielboliveira** [dianlight/hassio-addons#17]
Hi mate!

Found your Samba NAS while searching how to mount external hard drives into Home Assistant. Nice work! For what I understood, I can use it to mount to /share/ folder and use it in other addons. My usage would be setting up Transmission + Plex to read from folders at external hard drives.

I see that it only supports ext3/4 and fat for the moment, and also you plan to support NTFS and others for the future. Did you start any work already? Willing to help 😉

**Comment by dianlight** [comment]
Hi,
 That's not how it works. The discs mounted inside a docker  shall be visible only within the same docker. Therefore, the addon sets up the discs and exposes them via samba. The other addons can be modified to mount the samba discs and then use them.

I have in my repository a Plex addons with the modify, to use Trasmission addons you need to modify to support network disks mount.

Ntfs and ExFat are fuse devices and there are many issue with samba, you can use its but are very slow ( samba documented issue) and don't works well with ACL.

Any help is accepted, fork my repository, patch and apply for a PR. The only requirement is the usefulness and the don't violate copyright.

L.

**Comment by dianlight** [comment]
Support for ExFAT and NTFS released in #120
