### ISSUE TITLE
🐛 [SambaNAS] <curl: (7) Failed to connect to supervisor port 80 after 0 ms: Couldn't connect to server>

### ISSUE THREAD

**Issue by userosos** [dianlight/hassio-addons#173]
### Addon

SambaNAS

### Description

s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service base-addon-banner: starting
curl: (7) Failed to connect to supervisor port 80 after 0 ms: Couldn't connect to server
[18:21:24] ERROR: Something went wrong contacting the API
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
curl: (7) Failed to connect to supervisor port 80 after 1 ms: Couldn't connect to server
[18:21:24] ERROR: Something went wrong contacting the API
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-automount: starting
curl: (7) Failed to connect to supervisor port 80 after 0 ms: Couldn't connect to server
[18:21:24] ERROR: Something went wrong contacting the API
[18:21:24] WARNING: Your operating system  is not supported! 
+------------------------------------------------------------------+
| THIS ADDON IS DESIGNED FOR HOME ASSISTANT OPERATING SYSTEM ONLY! |
| THIS ADDON IS DESIGNED FOR HOME ASSISTANT OPERATING SYSTEM ONLY! |
| THIS ADDON IS DESIGNED FOR HOME ASSISTANT OPERATING SYSTEM ONLY! |
| THIS ADDON IS DESIGNED FOR HOME ASSISTANT OPERATING SYSTEM ONLY! |
| THIS ADDON IS DESIGNED FOR HOME ASSISTANT OPERATING SYSTEM ONLY! |
+------------------------------------------------------------------+
[18:21:24] FATAL: You can force this addon to run only if you known the meaning of life!
s6-rc: warning: unable to start service init-automount: command exited 1
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
/run/s6/basedir/scripts/rc.init: fatal: stopping the container.
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service base-addon-log-level: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service base-addon-log-level successfully stopped
s6-rc: info: service base-addon-banner: stopping
s6-rc: info: service base-addon-banner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

### Reproduction steps

```bash
1. Go to http://ip:8123/hassio/addon/1a32f091_sambanas/info
2. Click on start
3. See error
```

### Addon Logs

```bash
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service base-addon-banner: starting
curl: (7) Failed to connect to supervisor port 80 after 0 ms: Couldn't connect to server
[18:21:24] ERROR: Something went wrong contacting the API
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
curl: (7) Failed to connect to supervisor port 80 after 1 ms: Couldn't connect to server
[18:21:24] ERROR: Something went wrong contacting the API
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-automount: starting
curl: (7) Failed to connect to supervisor port 80 after 0 ms: Couldn't connect to server
[18:21:24] ERROR: Something went wrong contacting the API
[18:21:24] WARNING: Your operating system  is not supported! 
+------------------------------------------------------------------+
| THIS ADDON IS DESIGNED FOR HOME ASSISTANT OPERATING SYSTEM ONLY! |
| THIS ADDON IS DESIGNED FOR HOME ASSISTANT OPERATING SYSTEM ONLY! |
| THIS ADDON IS DESIGNED FOR HOME ASSISTANT OPERATING SYSTEM ONLY! |
| THIS ADDON IS DESIGNED FOR HOME ASSISTANT OPERATING SYSTEM ONLY! |
| THIS ADDON IS DESIGNED FOR HOME ASSISTANT OPERATING SYSTEM ONLY! |
+------------------------------------------------------------------+
[18:21:24] FATAL: You can force this addon to run only if you known the meaning of life!
s6-rc: warning: unable to start service init-automount: command exited 1
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
/run/s6/basedir/scripts/rc.init: fatal: stopping the container.
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service base-addon-log-level: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service base-addon-log-level successfully stopped
s6-rc: info: service base-addon-banner: stopping
s6-rc: info: service base-addon-banner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

### Addon Config

```bash
workgroup: WORKGROUP
username: homeassistant
allow_hosts:
  - 10.0.0.0/8
  - 172.16.0.0/12
  - 192.168.0.0/16
  - 169.254.0.0/16
  - fe80::/10
  - fc00::/7
  - 10.8.0.0/24
  - 192.168.31.0/24
automount: true
moredisks:
  - id:wwn-0x5000c5009b2c9d2e-part2
available_disks_log: true
medialibrary:
  enable: true
veto_files:
  - ._*
  - .DS_Store
  - Thumbs.db
  - icon?
  - .Trashes
compatibility_mode: false
wsdd2: false
mqtt_use_legacy_entities: false
autodiscovery: {}
other_users: []
acl: []
interfaces: []
password: homeassistant
```

### Architecture

amd64

### OS

Docker

**Comment by dianlight** [comment]
The addon can't connect to the supervisor. Are you on an hassos installation? What version?

**Comment by userosos** [comment]
> The addon can't connect to the supervisor. Are you on an hassos installation? What version?
 Home Assistant 2023.10.1 Supervisor 2023.10.1.dev1201 User Interface 20231005.0 - latest

**Comment by dianlight** [comment]
> > The addon can't connect to the supervisor. Are you on an hassos installation? What version?
> 
>  
> 
> Home Assistant 2023.10.1 Supervisor 2023.10.1.dev1201 User Interface 20231005.0 - latest 

Your host? Which version?

**Comment by userosos** [comment]
> > > The addon can't connect to the supervisor. Are you on an hassos installation? What version?
> > 
> > 
> > Home Assistant 2023.10.1 Supervisor 2023.10.1.dev1201 User Interface 20231005.0 - latest
> 
> Your host? Which version?

 screenfetch
         _,met$$$$$gg.           user@debian
      ,g$$$$$$$$$$$$$$$P.        OS: Debian 12 bookworm
    ,g$$P""       """Y$$.".      Kernel: x86_64 Linux 6.1.0-13-amd64
   ,$$P'              `$$$.      Uptime: 15h 59m
  ',$$P       ,ggs.     `$$b:    Packages: 1676
  `d$$'     ,$P"'   .    $$$     Shell: bash
   $$P      d$'     ,    $$P     Disk: 899G / 1,2T (79%)
   $$:      $$.   -    ,d$$'     CPU: Intel Celeron J4125 @ 4x 2,7GHz [46.0°C]
   $$\;      Y$b._   _,d$P'      GPU: UHD Graphics 600
   Y$$.    `.`"Y$$$$P"'          RAM: 2173MiB / 7778MiB
   `$$b      "-.__
    `Y$$
     `Y$$.
       `$$b.
         `Y$$b.
            `"Y$b._
                `""""

**Comment by dianlight** [comment]
Please read the addon documentation (the important note at the beginning).
This addon is useful only in a hassos environment in your environment simply install samba at host level.

I suggest you also to check your installation because the supervisor/docker is not configured correctly and the interdocks communication don't works.

**Comment by userosos** [comment]
> I suggest you also to check your installation because the supervisor/docker is not configured correctly and the interdocks communication don't works.

How i can do it?

**Comment by userosos** [comment]
I have the latest installation. I installed it yesterday.
