### ISSUE TITLE
CIFS or NFS possible?✨ [REQUEST] Addon name

### ISSUE THREAD

**Issue by mega-hz** [dianlight/hassio-addons#177]
### Addon

SambaNAS

### Checked

- [X] I have searched in the discussions & issues that it was not already covered

### Is your feature request related to a problem? Please describe

Hello,

first a big thanx for this nice Feature for Samba Share in HA !!!

I wonder if it could be possible to add a CIFS or NFS mount?
I would like to use my BIG MP3 Collection for Media things .

Or is there another Integrations for this purpose?

### Describe the solution you'd like

CIFS or NFS Mount

**Comment by dianlight** [comment]
Ha already is able to mount external CFS or NFS drive. 
Go to Settings->System->Storage->Network Storage.

Or I don't understand the question! 🙃 

L.

**Comment by mega-hz** [comment]
![Screenshot (59)](https://github.com/dianlight/hassio-addons/assets/21139347/141ea5ed-5663-40d7-a307-75485b8b628a)

Sorry but i have no >Storage->Network Storage.

Where can i find this?

**Comment by mega-hz** [comment]
i must be blind... :-)
Found it!

Thank you for help!

**Comment by mega-hz** [comment]
Problem is:
On the PI4 running HAOS, Storage is there.
On My I3 PC with HA-Core there is no Storage Entry...

**Comment by dianlight** [comment]
Storage Entry is only for supervised installation that support mount.
