### ISSUE TITLE
✨ Expose folder "addon_configs"

### ISSUE THREAD

**Issue by naitsimp** [dianlight/hassio-addons#179]
### Addon

SambaNAS

### Checked

- [X] I have searched in the discussions & issues that it was not already covered

### Is your feature request related to a problem? Please describe

AppDaemon 0.15.2 moved the config into the folder "addon_configs" which isn't exposed in samba. 

### Describe the solution you'd like

Expose folder "addon_configs" over samba.

**Comment by dianlight** [comment]
If you intend the change in supervisor in last release [2023.11.3](https://github.com/home-assistant/supervisor/releases/tag/2023.11.3) is rolled back.
If I misunderstood please specify because the AppDaemon I know has not config change and the version is 4.x

L.

**Comment by naitsimp** [comment]
I am talking about that change: [https://github.com/hassio-addons/addon-appdaemon/releases/tag/v0.15.2](url)
This is also discussed here. [https://github.com/hassio-addons/addon-appdaemon/issues/287](url)

**Comment by dianlight** [comment]
done in the release 12.1.0-nas

**Comment by mycanaletto** [comment]
My problem is that the `/addon_configs` folder to which the update moved my files.
![image](https://github.com/dianlight/hassio-addons/assets/45459269/8b17a6b5-cd52-4ee0-b15d-4fdaee226f2e)
I restored it and added this line
`app_dir: /homeassistant/appdaemon/apps/`
After updating and restoring the files in the old folder, it works, but it will break during the next update.

The question is how to make the `/addon_configs folder` visible.

Thanks for your help
