### ISSUE TITLE
Unable to start 

### ISSUE THREAD

**Issue by zre717** [dianlight/hassio-addons#18]
Hi!
I'm running hassos on raspberry pi 4 4gb from an ssd drive and trying to connect another ext4 hdd for media and plex content.
I've tried samba share addon and it works fine for the config files, but doesn't show second drive.
Installed your addon and it won't start with either one or two drives - I get an error "500 Server Error: Internal Server Error ("error creating overlay mount to mnt/data/docker/overlay2/a0c502c5395b9367e77c8c44f99d56d36769b40a272430d28d5144ed287554e0-init/merged: too many levels of symbolic links")" starting an add-on. 
Is there any way to make it work with two drives?

**Comment by dianlight** [comment]
I think the problem is related to the external SSD boot u-boot system. 
Do you receive the error on install or on the first run?

**Comment by zre717** [comment]
On the first run

**Comment by dianlight** [comment]
Can you test the last version. With the change on core this issue must be resolved but I don't have the hw to test.

L.

**Comment by dianlight** [comment]
Any feeback?
