### ISSUE TITLE
✨ [REQUEST] Support for APFS formatted hard drives

### ISSUE THREAD

**Issue by piyushbhatia10** [dianlight/hassio-addons#184]
### Addon

SambaNAS

### Checked

- [X] I have searched in the discussions & issues that it was not already covered

### Is your feature request related to a problem? Please describe

Not exactly a problem but my hard drives are formatted in APFS. And it does have lot of data already.

Is it possible to add support for APFS in the add-on? As it will be a huge task to ask someone for spare drive and copy all the data to that drive. Then format the drive again and copy the data back to HDD.

### Describe the solution you'd like

Support for APFS file system in the add-on.

**Comment by dianlight** [comment]
The support of APFS in the Linux kernel is still unstable and only read only. There is also a fuse fs implementation also unstable e ro the only "working" implementation is by Paragon but is closed source and need to check the license if can be included without fee in the addon.

**Comment by piyushbhatia10** [comment]
Thank you. 

Found this online. Will this help?
https://linuxnewbieguide.org/how-to-mount-macos-apfs-disk-volumes-in-linux/

Awaiting an update from your end.

**Comment by dianlight** [comment]
Apfs-fuse is read-only! See limit in read me 

https://github.com/sgan81/apfs-fuse

L

**Comment by piyushbhatia10** [comment]
Saw that. If you can add the support, then at least for now, it will be good to read data from exisiting hard drives

And, later when further advancements are available, read-write functionality can be implemented.

If it will be too much of hassle, then it is fine. But, if you think, it is an easy add-on, then it will be really great and existing HDDs can be used to read data, photos, videos etc. for the time being. :)

**Comment by dianlight** [comment]
I can try but I can't promise anything right now. Stay tuned for  further updates.

This is also promising:
https://github.com/linux-apfs/linux-apfs-rw

L

**Comment by piyushbhatia10** [comment]
Thank you. Will await your updated plugin in HA. :)

**Comment by piyushbhatia10** [comment]
Hey mate,

Just wondering if you have any update on this issue, please.

**Comment by dianlight** [comment]
I have publish some  fix in the beta channel. 
Feel free to test it https://github.com/dianlight/hassio-addons-beta
