### ISSUE TITLE
🐛 [SambaNAS] Can't mount `moredisks` with label that contains a reserved word as substring

### ISSUE THREAD

**Issue by wjbuys** [dianlight/hassio-addons#188]
### Addon

SambaNAS

### Description

Since the 12.1.0 update, it's no longer possible to mount `moredisk` shares that contain a reserved name as a substring (e.g. something like `sharedrive`). This used to work, and I expect it to still work, but it doesn't.

### Reproduction steps

Configure a `moredisk` share with a label that contains a reserved word, e.g. `sharedrive`. This seems to strip the reserved word `share` from the name before mounting, resulting in a failure to mount the drive by the name `drive`.

### Addon Logs

```bash
[15:40:41] INFO: Available Disk Labels:
[15:40:41] INFO: 	sharedrive[ext4]
---------------------------------------------------
[15:40:42] INFO: MoreDisks to mount:

	sharedrive
[15:40:42] INFO: Automount is Enabled!
---------------------------------------------------
[15:40:42] INFO: Checking Mounting disks for reserved names:

	sharedrive
---------------------------------------------------
---------------------------------------------------
[15:40:42] INFO: Mounting disks:

	drive
---------------------------------------------------
[15:40:42] INFO: Disk drive not found! <SKIP>
```

### Addon Config

```bash
workgroup: WORKGROUP
automount: true
moredisks:
  - sharedrive
mountoptions:
  - nosuid
  - relatime
  - noexec
compatibility_mode: false
recyle_bin_enabled: false
wsdd2: false
mqtt_use_legacy_entities: false
autodiscovery: {}
mqtt_enable: true
```

### Architecture

amd64

### OS

HaOS

**Comment by wjbuys** [comment]
Pretty sure the bug is here:

https://github.com/dianlight/hassio-addons/blob/3223b18c58bb6e9fc0338c9d2bf8502863fe6345/sambanas/rootfs/etc/s6-overlay/s6-rc.d/init-automount/run#L52-L55

This should only clean the name in the original array if the disk name is a full match for the reserved name, not a substring match.

**Comment by golonac** [comment]
Hi! I seem to have this issue since updating Samba NAS as well - not sure what cleaning up mount names is for, but doing a full match would still fail in my case, since I have an external drive called "Media", sadly.

```
[17:49:25] INFO: Checking Mounting disks for reserved names:

	Media
	Photos
---------------------------------------------------
---------------------------------------------------
[17:49:25] INFO: Mounting disks:

	
	Photos
---------------------------------------------------
[17:49:25] INFO: Disk  not found! <SKIP>
```

**Comment by dianlight** [comment]
`Media` is a reserved word because a `media` share is already present in the default shares. 
CIFS is case-insensitive but case-preserving so if you expose two shares with the same name can be a problem for many clients type.

I suggest you to relabel `Media` with a different name like `Videos`

**Comment by golonac** [comment]
I configured the default shares off with acl settings so there's no clash, but the checker doesn't take that into account. This can be worked around by renaming the disk for sure, though I think "Media" could be a pretty popular name for a NAS disk so allowing that might be good. The old version allowed it. Thanks for the addon!

```
- share: addons
  disabled: true
- share: backup
  disabled: true
- share: config
  disabled: true
- share: addon_configs
  disabled: true
- share: media
  disabled: true
- share: share
  disabled: true
- share: ssl
  disabled: true
```

(I disabled the default shares for security, I think the default settings made config/secrets.yaml viewable within the network)

**Comment by dianlight** [comment]
I have publish the fix in the beta channel. 
Feel free to test it https://github.com/dianlight/hassio-addons-beta

**Comment by golonac** [comment]
Awesome, thanks! Tested and works 🙏

**Comment by dianlight** [comment]
#202  Relesed in 12.2.0-nas1

**Comment by Jantjuhhh** [comment]
How to mount 2 harddiscs is that possible in the addon?
