### ISSUE TITLE
Multiple Connections

### ISSUE THREAD

**Issue by jonathanicq** [dianlight/hassio-addons#19]
Hi @dianlight 
First of all, great job.. it's a very handy addon.

I've a improvement request, could you add the ability to allow more than 1 user under the authentication process.
As far I could understand, I'm only able to connect using 1 par of user/pwd.

**Comment by ElVit** [comment]
Hi, 
I'm also very interested in this feature.
Maybe you could use the existing users from HomeAssistant to allow authenticate your addon.
A similar behaviour is implemented in the [Mosquitto broker Add-on](https://github.com/home-assistant/addons/tree/master/mosquitto).
Would be very cool if this will be possible :smiley:

**Comment by dianlight** [comment]
To implement the only way is to write an auth adapter for samba. Is a big task. I try to see how is implemented in the mosquito addon if some code can be recycled.

**Comment by dianlight** [comment]
See release 9.7.0-nas1
