### ISSUE TITLE
Hassio-addons repository failed download in Hassbian

### ISSUE THREAD

**Issue by lesposit** [dianlight/hassio-addons#2]
Hi, searching for a way to add simply nas functionality to Hassbian, i tried, unsuccessfully, to download your addon "sambanas". I have no experience at all in this kind of things; here, the output from sistem log:

`20-04-20 08:28:15 ERROR (MainThread) [supervisor.store.git] Can't clone https://github.com/dianlight/hassio-addons repository: Cmd('git') failed due to: exit code(1)
  cmdline: git clone --depth=1 --recursive --shallow-submodules -v https://github.com/dianlight/hassio-addons /data/addons/git/1a32f091
  stderr: 'Cloning into '/data/addons/git/1a32f091'...
POST git-upload-pack (192 bytes)
POST git-upload-pack (201 bytes)
Submodule 'addon-plex' (https://github.com/dianlight/addon-plex) registered for path 'addon-plex'
Cloning into '/data/addons/git/1a32f091/addon-plex'...
fatal: remote error: upload-pack: not our ref 24175c1cd0cbae5ab83a4b1157c7fa1e8cb64daf
fatal: the remote end hung up unexpectedly
Fetched in submodule path 'addon-plex', but it did not contain 24175c1cd0cbae5ab83a4b1157c7fa1e8cb64daf. Direct fetching of that commit failed.
'.
20-04-20 08:28:15 ERROR (MainThread) [supervisor.store] Can't load from repository https://github.com/dianlight/hassio-addons`

**Comment by dianlight** [comment]
Can you retry? The submodule reference was outdate.

L.


Il giorno lun 20 apr 2020 alle ore 10:59 Luca Esposito <
notifications@github.com> ha scritto:

**Comment by lesposit** [comment]
Nevermind, tried later and it just worked. Thanks for your reply.
