### ISSUE TITLE
Help wanted plz

### ISSUE THREAD

**Issue by AvinashVK** [dianlight/hassio-addons#20]
[22:18:18] INFO: MQTT cleanup.
Error: -h argument given but no host specified.
Use 'mosquitto_sub --help' to see usage.
[cont-finish.d] mqtt.sh: exited 1.
[cont-finish.d] umount.sh: executing... 
[22:18:18] INFO: Unmount drivers.
umount: /dev: target is busy.
[cont-finish.d] umount.sh: exited 32.
[cont-finish.d] done.
[s6-finish] waiting for services.
s6-svwait: fatal: unable to subscribe to events for /var/run/s6/services/nmbd: Read-only file system
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.

What might be the issue

**Comment by dianlight** [comment]
For now the addon need an mqtt service so enable it in ha.
In dev branch there is a patch to work without I will release in a near future.

**Comment by AvinashVK** [comment]
Ok thanks buddy i will try it
