### ISSUE TITLE
🐛SAMBA NAS Can't update to 12.2.0-nas1

### ISSUE THREAD

**Issue by Zeunas** [dianlight/hassio-addons#203]
### Addon

SambaNAS

### Description

Can't update SAMBA NAS to latest version 12.2.0-nas1

### Reproduction steps

```bash
1. Go to 'addons'
2. Click on 'update SAMBA NAS'
3. See error

Can't install dianlight/armv7-addon-sambanas:12.2.0-nas1: 404 Client Error for http+docker://localhost/v1.43/images/create?tag=12.2.0-nas1&fromImage=dianlight%2Farmv7-addon-sambanas&platform=linux%2Farm%2Fv7: Not Found ("manifest for dianlight/armv7-addon-sambanas:12.2.0-nas1 not found: manifest unknown: manifest unknown")

4. Don't know how to check "Architecture", can someone help?
```

### Addon Logs

```bash
Home Assistant Core log:

Logger: homeassistant.components.hassio
Source: components/hassio/websocket_api.py:138
Integration: Home Assistant Supervisor (documentation, issues)
First occurred: 21:04:40 (1 occurrences)
Last logged: 21:04:40

Failed to to call /store/addons/1a32f091_sambanas/update - Can't install dianlight/armv7-addon-sambanas:12.2.0-nas1: 404 Client Error for http+docker://localhost/v1.43/images/create?tag=12.2.0-nas1&fromImage=dianlight%2Farmv7-addon-sambanas&platform=linux%2Farm%2Fv7: Not Found ("manifest for dianlight/armv7-addon-sambanas:12.2.0-nas1 not found: manifest unknown: manifest unknown")
```

### Addon Config

```bash
workgroup: WORKGROUP
username: xxxxx
allow_hosts:
  - 10.0.0.0/8
  - 172.16.0.0/12
  - 192.168.0.0/16
  - 169.254.0.0/16
  - fe80::/10
  - fc00::/7
automount: true
moredisks:
  - 1T Disk
mountoptions:
  - nosuid
  - relatime
  - noexec
available_disks_log: false
medialibrary:
  enable: false
veto_files:
  - ._*
  - .DS_Store
  - Thumbs.db
  - icon?
  - .Trashes
compatibility_mode: true
recyle_bin_enabled: false
wsdd2: false
mqtt_use_legacy_entities: false
autodiscovery: {}
other_users: []
acl: []
interfaces: []
password: xxxxx
mqtt_enable: true
mqtt_host: xxx.xxx.x.xx
mqtt_username: xxxxx
mqtt_password: xxxxx
mqtt_topic: disk
```

### Architecture

other

### OS

HaOS

**Comment by dincojazz** [comment]
Same here.
Installation log:
Can't install dianlight/armv7-addon-sambanas:12.2.0-nas1: 404 Client Error for http+docker://localhost/v1.43/images/create?tag=12.2.0-nas1&fromImage=dianlight%2Farmv7-addon-sambanas&platform=linux%2Farm%2Fv7: Not Found ("manifest for dianlight/armv7-addon-sambanas:12.2.0-nas1 not found: manifest unknown: manifest unknown")
[logs.bin.txt](https://github.com/dianlight/hassio-addons/files/14009727/logs.bin.txt)

**Comment by dianlight** [comment]
Uploaded the missing image/arch on dockerhub.

**Comment by Zeunas** [comment]
Thanks!

**Comment by dincojazz** [comment]
Thanks for your time.
Keep healthy!

**Comment by terrorsl** [comment]
Can't install dianlight/armv7-addon-sambanas:12.3.2-nas: 404 Client Error for http+docker://localhost/v1.47/images/create?tag=12.3.2-nas&fromImage=dianlight%2Farmv7-addon-sambanas&platform=linux%2Farm%2Fv7: Not Found ("manifest for dianlight/armv7-addon-sambanas:12.3.2-nas not found: manifest unknown: manifest unknown")

**Comment by dianlight** [comment]
> Can't install dianlight/armv7-addon-sambanas:12.3.2-nas: 404 Client Error for http+docker://localhost/v1.47/images/create?tag=12.3.2-nas&fromImage=dianlight%2Farmv7-addon-sambanas&platform=linux%2Farm%2Fv7: Not Found ("manifest for dianlight/armv7-addon-sambanas:12.3.2-nas not found: manifest unknown: manifest unknown")

Is not a great idea to write on a closed issue, I not miss it only for fate! Please open a new issue. 
Meantime I found  that there was a missed build error on a dependencie for the armv7 arch so no docker image is available. I'm unable to work on it so sorry but you need to wait for the next version, if you are on a old version please skip this update if you are on a new installation you need to wait; i will inform you on the new issue when a beta version for armv7 is available.

L.
