### ISSUE TITLE
🐛 [Samba NAS] Illegal character Error

### ISSUE THREAD

**Issue by lp55** [dianlight/hassio-addons#204]
### Addon

SambaNAS

### Description

Hi,

   I'm using the Samba NAS addon on my haos x86-64 machine and I keep getting this error:

Conversion error: illegal character [folder path]

   On several folders. This is due to the use of non ascii folder names such as Vídeo.
   I'm auto mounting an external drive (formated on FAT32). I've read that this is duo to the lack on unix charset option set to UTF-8. But I'm no sure if this is due to a Samba config or a mount config, as these folders also don't show up at HA media, when browsing thought the folders (I have the medialibrary option enabled). 

### Reproduction steps

```bash
1. Mount an fat32 external drive
2. Try to access folders with non ascii characters (like Vídeo)
3. They will not be avaliable
```

### Addon Logs

```bash
Conversion error: illegal character: Stuff/17. �vora
```

### Addon Config

```bash
workgroup: WORKGROUP
username: ****
allow_hosts:
  - 10.0.0.0/8
  - 172.16.0.0/12
  - 192.168.0.0/16
  - 169.254.0.0/16
  - fe80::/10
  - fc00::/7
automount: true
moredisks:
  - /dev/sdb1
mountoptions:
  - nosuid
  - relatime
  - noexec
available_disks_log: true
medialibrary:
  enable: true
veto_files:
  - ._*
  - .DS_Store
  - Thumbs.db
  - icon?
  - .Trashes
compatibility_mode: false
recyle_bin_enabled: false
wsdd2: false
mqtt_nexgen_entities: false
autodiscovery: {}
other_users: []
acl: []
interfaces: []
mqtt_use_legacy_entities: false
password: ****
```

### Architecture

amd64

### OS

HaOS

**Comment by dianlight** [comment]
Fixed in 12.2.0-nas2.beta68 [Beta Repository](https://github.com/dianlight/hassio-addons-beta)
