### ISSUE TITLE
❓ [addon] SambaNAS mounted USB drive shows different used space.

### ISSUE THREAD

**Issue by JBakers** [dianlight/hassio-addons#205]
### Addon

SambaNAS

### Your request

Hello,

I have a 1TB USB drive mounted with SambaNAS to be used as data storage for Frigate.
The drive is formatted to EXT4 and empty.
But Frigate reports 46GB already in use.

![Schermafbeelding 2024-01-25 211254](https://github.com/dianlight/hassio-addons/assets/13487054/8e7afbed-7854-4f84-a15e-62df59acfeb4)

du -sh shows the actual size of the data (around 5mb)
df -h shows wrong data already in use (46G)

Any idea what is causing this, because Frigate also displays the 46G where the video data size is shown.

**Comment by dianlight** [comment]
This is the 5% space reserved to root/superuser. It is a default for ext4 fs.

Ref:[archlinux wiki](
https://wiki.archlinux.org/title/ext4#:~:text=By%20default%2C%205%25%20of%20the,from%20mke2fs(8)) )

**Comment by JBakers** [comment]
Thank you, I understand how.
