### ISSUE TITLE
❓ SMB Version and Port

### ISSUE THREAD

**Issue by Jogiarea** [dianlight/hassio-addons#209]
### Addon

SambaNAS

### Your request

Hello,

Thanks for your great project, I have set everything up and can also access the folders from Linux MX and Windows 11.
Unfortunately I have no access via samba with my surveillance cameras Lupus LE201 and LE202, these unfortunately only support SMB 1.0. which versions are supported by the addon?

Which SMB port is used for data transfer?
139 or 445

Many greetings

**Comment by dianlight** [comment]
From the smb specs:
```

(Old system)

Port 137 – UDP NetBIOS name service (WINS)
Port 138 – UDP NetBIOS datagram
Port 139 – TCP NetBIOS Session (TCP), Windows File and Printer Sharing (this is the most insecure port)

(Active Directory)

Port 445 - Microsoft-DS Active Directory, Windows shares (TCP)
Port 445 - Microsoft-DS SMB file sharing (UDP)
```


From this addon's doc: 
```
Option: compatibility_mode (optional)

Setting this option to true will enable old legacy Samba protocols on the Samba add-on. This might solve issues with some clients that cannot handle the newer protocols, however, it lowers security. Only use this when you absolutely need it and understand the possible consequences.

Defaults to false.
```

**Comment by Jogiarea** [comment]
Many thanks two Cams work but the oldest one do not connect.

i,ll try it with  FTP and your FTP addon.
