### ISSUE TITLE
❓ [addon] title

### ISSUE THREAD

**Issue by Jantjuhhh** [dianlight/hassio-addons#216]
### Addon

SambaNAS

### Your request

Is it possible to add a second usb drive?

**Comment by dianlight** [comment]
Yes. You can add as many as your hardware supports.
In my running environment I have two discs but I the rest environment I made a test with six different usb devices.

**Comment by Jantjuhhh** [comment]
Thnx, i already saw it it was my fault ;) Did something wrong on my 2nd hard disk so the addon never saw the disk my bad.
