### ISSUE TITLE
Raspberry Pi 5 support ❓ [addon] title

### ISSUE THREAD

**Issue by mihaimdinca** [dianlight/hassio-addons#218]
### Addon

SambaNAS

### Your request

Is the SambaNAS addon compatible with Raspberry Pi 5? I am asking because i recently upgraded from RPi4B and the addon either does not find my SSD (connected by USB) or it does find it and mount it but i only see folders and they show as empty.

**Comment by dianlight** [comment]
I don't know. I haven't a rb5 to test but I aspect that should work. Open a issue with your config and logs maybe I can find some useful information.

**Comment by mihaimdinca** [comment]
The issue was not with the addon. The issue was with the ssd connected to the rpi 5 via usb not getting enough current and corrupting the drive. Without a PD power source able to provide 5V 5A, the usb current is limited to 800 mA.
