### ISSUE TITLE
[Samba NAS] Files lost after nearly filling up the drive?

### ISSUE THREAD

**Issue by rursache** [dianlight/hassio-addons#22]
Hey, this addon provides the exact functionality im looking for! Im currently using a rpi 4 and an external 2tb hdd (wd) formatted as ext4.

I managed to setup everything and i got the share working on windows, macos and ios (infuse). However, after i copied my files over and forgot about it for a few hours, now i can no longer see any file from any OS. i can see that the drive is 98% full but no files. 

Log from the addon:
```
Failed to fetch record!
pcap cache not loaded
np_open: 'ping.txt' is not a registered pipe!
np_open: 'ping.txt' is not a registered pipe!
np_open: 'ping.txt' is not a registered pipe!
reply_ulogoffX: ulogoff, vuser id 177 does not map to user.
np_open: 'ping.txt' is not a registered pipe!
Failed to fetch record!
pcap cache not loaded
error in mds_init_ctx for: /2TBPi
_mdssvc_open: Couldn't create policy handle for 2TBPi
reply_ulogoffX: ulogoff, vuser id 18629 does not map to user.
Failed to fetch record!
pcap cache not loaded
reply_ulogoffX: ulogoff, vuser id 21952 does not map to user.
np_open: 'ping.txt' is not a registered pipe!
Failed to fetch record!
pcap cache not loaded
reply_ulogoffX: ulogoff, vuser id 35508 does not map to user.
np_open: 'ping.txt' is not a registered pipe!
np_open: 'ping.txt' is not a registered pipe!
```

Current config (nothing changed since i set it up and worked):
```
workgroup: WORKGROUP
username: Radu
password: <pass>
interface: ''
allow_hosts:
  - 10.0.0.0/8
  - 172.16.0.0/12
  - 192.168.0.0/16
  - 'fe80::/10'
moredisks:
  - 2TBPi
veto_files:
  - ._*
  - .DS_Store
  - Thumbs.db
  - icon?
  - .Trashes
compatibility_mode: true
autodiscovery: {}
mqtt_enable: false
```

@dianlight any clue what's going on? 
thanks a ton!

**Comment by rursache** [comment]
here is the error windows throws when i try to copy/add/create a new file/folder (while the drive have 5gb free left but the content is empty) - https://imgur.com/a/vm02P0k

**Comment by dianlight** [comment]
Hi, 
 It looks like an hw issue. Do you have an external power supply for the disk? 
Can you describe more about your environment? ( rpi/nuc etc ). 
Do you have try to mount the disk on your pc/Mac?

L.

**Comment by rursache** [comment]
raspberry pi 4, homeassistant os. disk mount fine on pc/mac.

EDIT: it was indeed power related. i free'd up the other ports on the pi (usb speakers, a camera and a zigbee adapter) and now everything works as expected. looking to buy an powered usb hub asap.
thanks!
