### ISSUE TITLE
✨ [REQUEST] SambaNAS  Integration of "Remote Announce" Feature to Enhance SambaNAS Discovery in Complex Network Environments

### ISSUE THREAD

**Issue by FermedePommerieux** [dianlight/hassio-addons#220]
### Addon

SambaNAS

### Checked

- [X] I have searched in the discussions & issues that it was not already covered

### Is your feature request related to a problem? Please describe

Our network infrastructure is designed with strict segmentation to enhance security and manage different types of devices effectively. Specifically, our Home Assistant server, along with our IoT devices, resides on a separate subnet for security reasons and isolation. This setup presents a challenge for the automatic discovery of our SambaNas server located on another subnet.

### Describe the solution you'd like

We believe that integrating the remote announce option into the SambaNAS configuration interface would address this issue by allowing the Samba server to explicitly announce itself on another subnet, thus facilitating the server's discovery and accessibility for authorized clients.

**Comment by dianlight** [comment]
Currently you can configure Samba to expose itself on different interfaces and on each interface the service is announced. In your case how the subnets as seen by HA?

L.
