### ISSUE TITLE
medialibrary is mounting in upper case

### ISSUE THREAD

**Issue by J4yDubsHome** [dianlight/hassio-addons#230]
### Addon

SambaNAS

### Your request

First off, thanks for the very useful Addon.  I've been using it for a few months and it's working great.

I'm trying to setup Frigate and I want to use an external USB drive for the clips and recordings.  When I set medialibrary enable: true, SambaNAS properly mounts my USB external drive under media, but the name is upper case.  Is it possible to mount it as is, in lower case?

Frigate is looking for media/frigate, but since it's media/FRIGATE it's not finding it and creating a new directory call media/frigate.

Thanks for any help.

  /dev/disk/by-id/wwn-0x5000cca222f272ae-part1 /dev/disk/by-label/frigate

John

**Comment by J4yDubsHome** [comment]
Looked at the closed issues and found the solution.

1. Stop Frigate.
2. Delete or rename media/frigate.
3. Disable medialibrary in SambaNAS config. Restart SambaNAS.
4. Go to System/Storage/Add Network Storage.
5. Give it the name frigate, select media, Protocol Samba (use IP address for server), then the share name (FRIGATE in my case).
6. Start Frigate.

**Comment by juampick** [comment]
Thank you @J4yDubsHome that solved my issue. The trick was doing the mount manually. Thanks for your help!!!

**Comment by petebanham** [comment]
Sorry up dig up an old thread but @J4yDubsHome  does this persist after after a HAOS restart for you please?   I am finding that the  storage mount in HASO fails on restart, presumably because the OS is trying to mount it  before the add in has started and mad the CIF available.

**Comment by petebanham** [comment]
Actually correction, it does seem to mount eventually, it is jus the repair message in settings that does no clear itself
