### ISSUE TITLE
🐛 [SambaNAS] Can't install last update

### ISSUE THREAD

**Issue by Shiroe93** [dianlight/hassio-addons#232]
### Addon

SambaNAS

### Description

i can't istall the last add-on update i tried rebbot and even unistall the add-on now it won't let me install alltogether from HaOS giving me this error 

"Can't install dianlight/amd64-addon-sambanas:12.2.0-nas2: 404 Client Error for http+docker://localhost/v1.44/images/create?tag=12.2.0-nas2&fromImage=dianlight%2Famd64-addon-sambanas&platform=linux%2Famd64: Not Found ("manifest for dianlight/amd64-addon-sambanas:12.2.0-nas2 not found: manifest unknown: manifest unknown")"

EDIT:
tried install something else ad it worked with no problem so i don't think the problem is on my end

### Reproduction steps

```bash
1. Go to 'home assistant add-on page'
2. Click on 'SambaNAS'
3. Click on 'Install'
4. See error
```

### Addon Logs

```bash
no logs
```

### Addon Config

```bash
no config since is the problem is on install
```

### Architecture

amd64

### OS

HaOS

**Comment by paulus6789** [comment]
same problem with me too

**Comment by pcmaster4u** [comment]
with me too

**Comment by Foguet** [comment]
I have the same problem

**Comment by OGB1952** [comment]
Another one with the same issue.

**Comment by Jansen-AL** [comment]
Dito. can't install update.

**Comment by Patbonamy** [comment]
For me it was a Nginx proxy manager problem. I stop it and can update.

**Comment by WegnerDan** [comment]
> For me it was a Nginx proxy manager problem. I stop it and can update.

I don't have that installed and have the same issue

**Comment by dianlight** [comment]
Sorry, CI problem.
I have uploaded the docker images manually and now you can update.

L

**Comment by Patbonamy** [comment]
> > For me it was a Nginx proxy manager problem. I stop it and can update.
> 
> I don't have that installed and have the same issue

See if you have redirection in your router.

**Comment by Patbonamy** [comment]
> and

OK so it was not a Nginx proxy manager problem.
Thanks

**Comment by WegnerDan** [comment]
> Sorry, CI problem. I have uploaded the docker images manually and now you can update. 

Worked, thanks!

**Comment by pcmaster4u** [comment]
Thank you very much, everything works now

**Comment by paulus6789** [comment]
thank you, it works great again

**Comment by OGB1952** [comment]
Thanks, fixed for me, too!
