### ISSUE TITLE
Feature Request: Exposed Folders

### ISSUE THREAD

**Issue by glorifiedg** [dianlight/hassio-addons#24]
Would be awesome to custom choose which folders are exposed on the share. Personally I would like not to share /config. Also, it could be nice to have multiple users with different permissions like in the original samba for linux.

Great work!

**Comment by lullerboi** [comment]
Exactly my thoughts.

Example:
User "homeassistant" for the "default" shares
User "USB" for external drives

Another option might be to disable the default shares completely (-> you can start the default addon - only if needed) and using another hostname ONLY for USB drives. I'd even prefer this approach.

**Comment by tjxism** [comment]
This would be great! I use a overpowered NUC running HAOS and would love to use it as a true NAS (wife safe).

**Comment by dianlight** [comment]
See relese 9.7.0-nas1
