### ISSUE TITLE
Why automount add share with name in capital letters?

### ISSUE THREAD

**Issue by Mareckil** [dianlight/hassio-addons#243]
### Addon

SambaNAS

### Your request

Hi I need share name in lowercase letters, but SambaNAS create it in capitals, even if I manually deleted share and recreated it with name in lowercase letters, after reboot it comes up again with capitals preventing my manual definition from start. How to fix it?

**Comment by dianlight** [comment]
Cifs is not case sensitive is case preserving so upper or lower share name is the same.
Why do you need a lower share name? 
Keep in mind that smb protocol 1 e 2 supports only uppercase share name, lower case name is an aesthetic thing introduced in smb version 3.

L

**Comment by dianlight** [comment]
So is not the share name but the mount point name.
Your problem, correct me if I'm wrong, is with frigate addon.
I'm not in plan to implement a solution for frigate addon and I don't use it. In my opinion mount points need to preserve share names. 
In an old issue I found a solution with a change in the frigate configuration. 
I think you can find support on the frigate side.

L.

**Comment by juampick** [comment]
Hello, having the same issue here. My drive is `frigate` in lowercase, and Samba NAS is mounting it as FRIGATE. How Can I change that?

**Comment by juampick** [comment]
This is the solution: https://github.com/dianlight/hassio-addons/issues/230 just for reference. @Mareckil . The trick is actually disabling the automount and doing manually the mapping.
