### ISSUE TITLE
Error while mounting exFAT SSD

### ISSUE THREAD

**Issue by Blackspell01** [dianlight/hassio-addons#245]
### Addon

SambaNAS

### Your request

I was trying to expose an SSD to the local network using sambanas. It is formatted in exFAT, which is supported as experimental according to the documentation. When I start the add-on, it doesn't work though:

---------------------------------------------------
[19:55:48] INFO: Mounting disks:

	EFI
	SSD
---------------------------------------------------
[19:55:49] WARNING: Your EFI is vfat. Permissions and ACL don't works and this is an EXPERIMENTAL support
[19:55:49] INFO: Mount EFI[vfat] Success!
[19:55:49] WARNING: Your SSD is exfat. Permissions and ACL don't works and this is an EXPERIMENTAL support
mount: /mnt/SSD: unknown filesystem type 'exfat'.
       dmesg(1) may have more information after failed mount system call.
[19:55:49] WARNING: Fail to mount SSD nosuid,relatime,noexec !

Can someone help me to get the SSD working in HASSOS?

**Comment by dianlight** [comment]
Please add the full addon startup log.
Probably you are on architecture ( x86 ) where xfat is not included in the Linux kernel.

**Comment by Blackspell01** [comment]
Yes it's true, I'm on x86. Does this mean that exFAT is not possible? I'm sorry if I'm asking stupid questions. I guess the logs won't help you, but if you would want to take a look I can provide them though.

**Comment by dianlight** [comment]
On x86 hassos don't include ntfs and exfat kernel driver. I don't know why and sincerely is not in my interest to know.
I think there is already an issue about that on hassos repository.

At start up this addon check the available fs types and inform you in the log.

I always suggest user to change the fs and use ext4 or similar. The use with samba of native windows fs also raise slowness and permission problems on some unattended configuration.

L.

**Comment by Blackspell01** [comment]
Ok, thats unfortunate. It says: 
supported fs:	ext3	| ext2 | ext4 | squashfs | vfat | msdos | iso9660 | btrfs

I think non of them are compatible with macOS... My goal was to be able to plug the SSD into HomeassistantOS and into macOS..

Thank you anyway

**Comment by dianlight** [comment]
Starting from hassos 13.1 also x86 systems has exfat on kernel. 
You can try if it solve your issue.
