### ISSUE TITLE
Samba add-on: "Unable to subscribe to events: Read-only file system"

### ISSUE THREAD

**Issue by flochtililoch** [dianlight/hassio-addons#25]
I'm trying to run the Samba add-on but it appear to stop shortly after starting, with the error

```
s6-svwait: fatal: unable to subscribe to events for /var/run/s6/services/s6-fdholderd: Read-only file system
```

I'm running the latest HAOS (Home Assistant OS 5.10) on a Raspberry Pi 3B, and I moved the data partition to an external SSD (following [these instructions](https://github.com/home-assistant/operating-system/blob/d42f80c65e8506a6aec0c7f7f9e603107e163faf/Documentation/partition.md#using-datactl-to-move-the-data-partition)). I assume this might be related to the issue I'm seeing, as it's mentioned in the link above:

> this partition can be moved off of the SD card onto an externally connected drive, leaving the rest of the read-only system on the SD.

Here are the add-on logs:

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] automount.sh: executing... 
[11:32:17] INFO: Protection Mode is false
[cont-init.d] automount.sh: exited 0.
[cont-init.d] mqtt.sh: executing... 
[11:32:19] ERROR: Got unexpected response from the API: Service not enabled
/var/run/s6/etc/cont-init.d/mqtt.sh: line 22: bashio::log.warn: command not found
[cont-init.d] mqtt.sh: exited 127.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] mqtt.sh: executing... 
[11:32:21] INFO: MQTT cleanup.
Error: Connection refused
[cont-finish.d] mqtt.sh: exited 1.
[cont-finish.d] umount.sh: executing... 
[11:32:21] INFO: Unmount drivers.
umount: /dev: target is busy.
[cont-finish.d] umount.sh: exited 32.
[cont-finish.d] done.
[s6-finish] waiting for services.
s6-svwait: fatal: unable to subscribe to events for /var/run/s6/services/s6-fdholderd: Read-only file system
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```

and my config:

```
workgroup: WORKGROUP
username: myuser
password: mypassword
interface: ''
allow_hosts:
  - 10.0.0.0/8
  - 172.16.0.0/12
  - 192.168.0.0/16
  - 'fe80::/10'
moredisks: []
veto_files:
  - ._*
  - .DS_Store
  - Thumbs.db
  - icon?
  - .Trashes
compatibility_mode: false
autodiscovery: {}
```

**Comment by alexbelgium** [comment]
Confirmed. Updating from nas4 to nas5 broke the feature.
My log is exactly the same.

Config:
`workgroup: WORKGROUP
username: homeassistant
password: Bonjour01
interface: ''
allow_hosts:
  - 10.0.0.0/8
  - 172.16.0.0/12
  - 172.17.0.0/16
  - 172.30.32.0/16
  - 192.168.178.0/23
  - 172.30.33.0/23
  - 127.0.0.1
  - 'fe80::/10'
moredisks:
  - NAS
veto_files:
  - ._*
  - .DS_Store
  - Thumbs.db
  - icon?
  - .Trashes
  - Trash
compatibility_mode: false
autodiscovery: {}
mqtt_enable: false`

**Comment by dianlight** [comment]
In both the logs there is an error on connecting the Mqtt services. Can you confirm if you have or not the service in your environment?

**Comment by flochtililoch** [comment]
I did not install MQTT add-on

**Comment by alexbelgium** [comment]
I installed in the past the MQTT mosquito server, and configured Mqtt through integration. However, I have removed both months ago and MQTT is currently not installed. Could it be some residue? I'll provides my config yaml in a few hours. 

BTW, couldn't the flag of mqtt disabled in the addon config prevent to look for a running mqtt server?

**Comment by dianlight** [comment]
I think I have found the problem. In some cases (I suspect if it is uninstalled) HA tells the addon that the MQTT service is present but it passes an incorrect url for the connection.

I'm compiling and releasing version 9.3.0-nas6 will be available later this evening.

**Comment by alexbelgium** [comment]
Thanks! V6 is working perfectly :)

BTW, thanks very much for this addon that I use everyday. I've also borrowed some of your code that I reused (with crediting you) in my own Emby addon. It's like Plex but I've found to require less transcoding and it's working better on my rpi3b+. So, many thanks to you!

**Comment by basnijholt** [comment]
I also had this issue with the latest version (9.3.0-nas6).

After I added `mqtt_enable: false` to my config (the `mqtt_enable` option wasn't present yet) the problem was fixed.
