### ISSUE TITLE
Is there any way to dismount the network drive during shutdown?

### ISSUE THREAD

**Issue by zsozso83** [dianlight/hassio-addons#252]
### Addon

SambaNAS

### Your request

Hi!
I have a problem with HassOS restarting, because it saves the last network mount, and after every startup i get an error message, because the OS try to mount the drive sooner, then the addon is started. If i stop the addons (Frigate, SambaNAS) and dismount the drive and let the addon to mount the drive again during start up, everything works perfectly. But if i restart the machine, i get always the network share is not available message. So my idea is to dismount this drive after every shutdown, and then let the addon to mount it again during starting. Or dismount it during OS start, then start the addon. I dont know. 
Thanks for any advice.
BR

**Comment by dianlight** [comment]
It is related to the #219 problem.
On system start and shutdown the supervisor don't wait for the addon's events.
In start the remount is sent before samba server is ready and on shutdown the umount is newer wait.
I have try a solution with an automation on core side but don't work for the startup problem. I will try to modify for the shutdown side if resolve.

A moment of patience that these days I don't have much time to dedicate to the project but if the solution goes I should release shortly.

L

**Comment by zsozso83** [comment]
Thank you for your answer. I will wait for the update. Thanks in advance!
Best regards,
Zsolt

A(z) iOS Outlook<https://aka.ms/o0ukef> appból küldve
________________________________
Feladó: Lucio Tarantino ***@***.***>
Elküldve: Saturday, September 14, 2024 6:49:01 AM
Címzett: dianlight/hassio-addons ***@***.***>
Másolatot kap: zsozso83 ***@***.***>; Author ***@***.***>
Tárgy: Re: [dianlight/hassio-addons] Is there any way to dismount the network drive during shutdown? (Issue #252)


It is related to the #219<https://github.com/dianlight/hassio-addons/issues/219> problem.
On system start and shutdown the supervisor don't wait for the addon's events.
In start the remount is sent before samba server is ready and on shutdown the umount is newer wait.
I have try a solution with an automation on core side but don't work for the startup problem. I will try to modify for the shutdown side if resolve.

A moment of patience that these days I don't have much time to dedicate to the project but if the solution goes I should release shortly.

L

**Comment by dianlight** [comment]
I release a fixed version in beta channel. Please try and give me a feedback if you issue is resolved
