### ISSUE TITLE
❓Samba NAS:  Your operating system  is not supported! 

### ISSUE THREAD

**Issue by Leopoll** [dianlight/hassio-addons#256]
### Addon

Samba NAS
Current version: 12.2.0-nas2

### Your request

So, I use HA Supervised with Docker. Is this the problem?
How I can "force this addon to run"?

`s6-rc: info: service s6rc-oneshot-runner: starting

s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service base-addon-banner: starting
curl: (7) Failed to connect to supervisor port 80 after 3 ms: Couldn't connect to server
[16:59:48] ERROR: Something went wrong contacting the API
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
curl: (7) Failed to connect to supervisor port 80 after 0 ms: Couldn't connect to server
[16:59:48] ERROR: Something went wrong contacting the API
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-automount: starting
curl: (7) Failed to connect to supervisor port 80 after 0 ms: Couldn't connect to server
[16:59:49] ERROR: Something went wrong contacting the API
[16:59:49] WARNING: Your operating system  is not supported! 
+------------------------------------------------------------------+
| THIS ADDON IS DESIGNED FOR HOME ASSISTANT OPERATING SYSTEM ONLY! |
| THIS ADDON IS DESIGNED FOR HOME ASSISTANT OPERATING SYSTEM ONLY! |
| THIS ADDON IS DESIGNED FOR HOME ASSISTANT OPERATING SYSTEM ONLY! |
| THIS ADDON IS DESIGNED FOR HOME ASSISTANT OPERATING SYSTEM ONLY! |
| THIS ADDON IS DESIGNED FOR HOME ASSISTANT OPERATING SYSTEM ONLY! |
+------------------------------------------------------------------+
[16:59:49] FATAL: You can force this addon to run only if you known the meaning of life!
s6-rc: warning: unable to start service init-automount: command exited 1
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
/run/s6/basedir/scripts/rc.init: fatal: stopping the container.
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service base-addon-log-level: stopping
s6-rc: info: service base-addon-log-level successfully stopped
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service base-addon-banner: stopping
s6-rc: info: service base-addon-banner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped`

**Comment by dianlight** [comment]
In a docker environment this addon  is not useful  and not tested. 

You can anyway use it with a minimal effort if you are in a minimal knowledge of how it works.

You opened this issue so I suggest you to not use this addon and use the standard samba package on your host that is more stable and better supported.
