### ISSUE TITLE
Sensor for remaining file space

### ISSUE THREAD

**Issue by FeikoJoosten** [dianlight/hassio-addons#26]
To my knowledge there's no way of knowing the remaining storage on the mounted disk. Would it be possible to add a sensor that could add support for this? This way I can prevent myself from accidentally filling up the storage of my external HDD.

**Comment by dianlight** [comment]
If you have a mqtt service in your ha installation sambanas for every disk iautomatically create a sensor with use, size and available.

**Comment by FeikoJoosten** [comment]
Perfect, that's more than enough!
