### ISSUE TITLE
✨ [REQUEST] SambaNAS: option to force mount dirty ntfs partition

### ISSUE THREAD

**Issue by codyrocco** [dianlight/hassio-addons#266]
### Addon

SambaNAS

### Checked

- [X] I have searched in the discussions & issues that it was not already covered

### Is your feature request related to a problem? Please describe

for example, having [by various motives, mostly unsafe removal]

```
[  616.678818] ntfs3: sda1: It is recommened to use chkdsk.
[  616.724143] ntfs3: sda1: volume is dirty and "force" flag is not set!
```
could be there an option to use "force"? like in windows... a warning, not an error leading to unmounting.

### Describe the solution you'd like

append "-o force" to mount command, when this option is selected in config
[optional] pray to HAOS gods to add ntfsfix in x86-64 builds

**Comment by dianlight** [comment]
Why not use the `mountoptions` config parameter?

```yaml
mountoptions: "force,nosuid,relatime,noexec"
```

**Comment by codyrocco** [comment]
stupid me, never thought at this :)) ... 
anyway, i tested the new version, is excellent!
