### ISSUE TITLE
Plex Media Server with NAS - "WARNING: Protection mode is ON. Unable to mount external drivers!"

### ISSUE THREAD

**Issue by LoganJFisher** [dianlight/hassio-addons#32]
When starting the Plex Media Server with NAS addon, my log gives the error: "WARNING: Protection mode is ON. Unable to mount external drivers!" despite having protection mode toggled off.

**Comment by dianlight** [comment]
I am not a wizard if you want help I need more information:
- The complete log of the addon startup
- Addon configuration. (hide the token)
- If the share is exposed by sambanas the configuration of sambanas ( hide user and password )

Then I need the result of the following actions/checks:
- Mounting the share from a PC do you see the content in r/w? The URL or URI used to connect from the PC ( \\<server>\<path> for windows or smb://<server>/<path> for Unix )

**Comment by LoganJFisher** [comment]
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Hass.io Add-on: Plex Media Server with NAS
 Recorded media, live TV, online news, and podcasts ready to stream.
-----------------------------------------------------------
 Add-on version: 2.4.2-dht2
 You are running the latest version of this add-on.
 System: Raspbian GNU/Linux 10 (buster)  (armv7 / raspberrypi4)
 Home Assistant Core: 2021.2.3
 Home Assistant Supervisor: 2021.02.6
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] plex.sh: executing... 
[21:14:44] INFO: First run! Initializing configuration files...
[cont-init.d] plex.sh: exited 0.
[cont-init.d] webtools.sh: executing... 
[21:14:45] INFO: Enabling WebTools plugin...
[cont-init.d] webtools.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[21:14:46] INFO: Starting the Plex Media Server...
[21:14:46] INFO: Network Disks mounting.. PlexDrive
[21:14:46] INFO: Mount PlexDrive
mount.cifs: bad UNC (PlexDrive)
[21:14:46] WARNING: Protection mode is ON. Unable to mount external drivers!

**Comment by LoganJFisher** [comment]
`[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Hass.io Add-on: Plex Media Server with NAS
 Recorded media, live TV, online news, and podcasts ready to stream.
-----------------------------------------------------------
 Add-on version: 2.4.2-dht2
 You are running the latest version of this add-on.
 System: Raspbian GNU/Linux 10 (buster)  (armv7 / raspberrypi4)
 Home Assistant Core: 2021.2.3
 Home Assistant Supervisor: 2021.02.6
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] plex.sh: executing... 
[21:14:44] INFO: First run! Initializing configuration files...
[cont-init.d] plex.sh: exited 0.
[cont-init.d] webtools.sh: executing... 
[21:14:45] INFO: Enabling WebTools plugin...
[cont-init.d] webtools.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[21:14:46] INFO: Starting the Plex Media Server...
[21:14:46] INFO: Network Disks mounting.. PlexDrive
[21:14:46] INFO: Mount PlexDrive
mount.cifs: bad UNC (PlexDrive)
[21:14:46] WARNING: Protection mode is ON. Unable to mount external drivers!`

**Comment by LoganJFisher** [comment]
> [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Hass.io Add-on: Plex Media Server with NAS
 Recorded media, live TV, online news, and podcasts ready to stream.
-----------------------------------------------------------
 Add-on version: 2.4.2-dht2
 You are running the latest version of this add-on.
 System: Raspbian GNU/Linux 10 (buster)  (armv7 / raspberrypi4)
 Home Assistant Core: 2021.2.3
 Home Assistant Supervisor: 2021.02.6
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] plex.sh: executing... 
[21:14:44] INFO: First run! Initializing configuration files...
[cont-init.d] plex.sh: exited 0.
[cont-init.d] webtools.sh: executing... 
[21:14:45] INFO: Enabling WebTools plugin...
[cont-init.d] webtools.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[21:14:46] INFO: Starting the Plex Media Server...
[21:14:46] INFO: Network Disks mounting.. PlexDrive
[21:14:46] INFO: Mount PlexDrive
mount.cifs: bad UNC (PlexDrive)
[21:14:46] WARNING: Protection mode is ON. Unable to mount external drivers!

**Comment by LoganJFisher** [comment]
> claim_code: claim-_________________________
webtools: true
networkdisks:
  - PlexDrive
cifsusername: <username>
cifspassword: <password>
cifsversion: '3.0'

**Comment by LoganJFisher** [comment]
workgroup: WORKGROUP
username: ____________
password: ____________
interface: ''
allow_hosts:
  - 10.0.0.0/8
  - 172.16.0.0/12
  - 192.168.0.0/16
  - 'fe80::/10'
moredisks:
  - PlexDrive
veto_files:
  - ._*
  - .DS_Store
  - Thumbs.db
  - icon?
  - .Trashes
compatibility_mode: false
autodiscovery: {}

**Comment by LoganJFisher** [comment]
I don't actually have any way to currently connect the drive to my computer. It's m.2 and I don't have any cords that would allow me to connect that to my laptop. It's connected to my RPi via the case it's in (Argon Forty).

Since I'm using Samba NAS, I'm accessing the drive via \\192.168.0.132

**Comment by LoganJFisher** [comment]
> claim_code: claim-_________________________
webtools: true
networkdisks:
>  \- PlexDrive
cifsusername: \<username>
cifspassword: \<password>
cifsversion: '3.0'

There are two spaces to the left of "- PlexDrive", but I couldn't get that to format correctly here.

**Comment by dianlight** [comment]
If you want a tip I would read how text formatting works on GitHub... it could be very useful in the future.

Regarding your problem the error is written quite clearly in the logs:

> mount.cifs: bad UNC (PlexDrive)

The moredisk parameter needs the UNC of the disk, not the name. If you look at the example configuration you will see:

```
networkdisks:
 - //serverip/share
```

In your case it should be:

```
networkdisks:
 - //192.168.0.132/PlexDrive
```

**Comment by LoganJFisher** [comment]
I've corrected this and restarted, but the error persists.

**Comment by LoganJFisher** [comment]
[08:52:17] INFO: Starting the Plex Media Server...
[08:52:17] INFO: Network Disks mounting.. //192.168.0.132/PlexDrive
[08:52:17] INFO: Mount //192.168.0.132/PlexDrive
mount error(13): Permission denied
Refer to the mount.cifs(8) manual page (e.g. man mount.cifs)
[08:52:17] WARNING: Protection mode is ON. Unable to mount external drivers!

**Comment by LoganJFisher** [comment]
So, any thoughts? I'm stumped.

**Comment by dianlight** [comment]
> mount error(13): Permission denied

Or you have set cfsusername/cfspassword wrong or the addon has protection mode on. 

Check this.

L.

**Comment by LoganJFisher** [comment]
What is a cfsusername/cfspassword and how do I get them? The documentation never mentions cfs, I've never heard of cfs, and Google isn't being much help.

**Comment by dianlight** [comment]
From Google:

First link: https://en.m.wikipedia.org/wiki/Server_Message_Block


From documentation:

...

Option: networkdisks PROTECTION MODE NEED TO DISABLED TO WORK

Is the list of networks share to mount at boot. The mounted driver is on /<SERVER>/<SHARE> directory.

Option: cifsusername

The username to use to mount the network shares

Option: cifspassword

The password used to mount the networks shares

Option: cifsversion

The version of cifs to use. Default 3.0. Valid values are 3.0, 2.1, 2.0, 1.0.

...

I can help you but please Read all documentation ( is only 3 pages ) before ask.

L.

**Comment by LoganJFisher** [comment]
I have read through the documentation. I'm just not understanding what a cifsusername and cifspassword is, or where to find or make them.

**Comment by LoganJFisher** [comment]
Nevermind, I figured it out. For anyone who reads this in the future: It's the username and password that you set up in Samba NAS.

**Comment by LoganJFisher** [comment]
Okay, nope. It was working for a while, but then last night I added Nginx to my Home Assistant, and now this isn't working again. Stumped on why.
