### ISSUE TITLE
SAMBANAS Error with core 2021.02.03

### ISSUE THREAD

**Issue by alexbelgium** [dianlight/hassio-addons#35]
Hi @Lucio_Tarantino, since upgrading to Core 2021.2.3, the mount by labels stops with an error. I am using Home Assistant OS on Rpi3b+ 32 bits with OS 5.11. 

I've double-checked the partition name with terminal and it is correct (Typing in portainerv "ls -l /dev/disk/by-label" shows: "NAS -> ../../sda1"). However, I can mount the disk manually using /dev/sda1 in my own addon (which uses a custom apparmor.txt). In your own addon, "mount /dev/sda1 /zzz" results in "cannot mount /dev/sda1 read-only". 

I confirm that by adding a apparmor.txt such as this one to your addon, mounting is done properly again https://raw.githubusercontent.com/alexbelgium/hassio-addons-1/master/sambanas/apparmor.txt 

I wonder if this pull from the official addon could be the cause  : https://github.com/home-assistant/addons/pull/1825

BTW, thanks very much for this addon!

Here is the log:
```
[cont-init.d] automount.sh: executing... 
[22:01:40] INFO: Protection Mode is false
[22:01:41] WARNING: MoreDisk option found!
mount: /dev_: cannot mount devtmpfs read-only.
[22:01:43] WARNING: Unable to mount external drivers!
[cont-init.d] automount.sh: exited 0.
```

Supervisor log is OK:
```
21-02-19 22:00:22 WARNING (SyncWorker_1) [supervisor.docker.addon] Samba NAS running with disabled protected mode!
21-02-19 22:00:24 INFO (SyncWorker_1) [supervisor.docker.addon] Starting Docker add-on dianlight/armv7-addon-sambanas with version 9.3.0-nas6
21-02-19 22:00:51 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state CoreState.RUNNING
21-02-19 22:00:51 INFO (MainThread) [supervisor.resolution.check] System checks complete
21-02-19 22:00:54 INFO (SyncWorker_6) [supervisor.docker.interface] Stopping addon_1a32f091_sambanas application
```

**Comment by dianlight** [comment]
@alexbelgium You have already done in your fork. Any reason for not open a PR?

Thx
L.

**Comment by alexbelgium** [comment]
I haven't because I haven't understood why it's working and don't want to mess up your addon... I hoped that it might allow you to understand the issue and find an optimal solution. However I'll do the PR and you'll see if you merge it or not

BTW my understanding is that by using apparmor we should be able to mount without privileged mode. I managed to make it work for mounting smb shares with the apparmor.txt, but couldn't find a way to mount a local drive without privilege 

Alex

**Comment by dianlight** [comment]
> BTW my understanding is that by using apparmor we should be able to mount without privileged mode. I managed to make it work for mounting smb shares with the apparmor.txt, but couldn't find a way to mount a local drive without privilege

From my test with your AppArmor and the new Supervisor the plugin is able to see all /dev/ directory so I can remove the /dev_ trick.

I was able to mount "not physical" disk (as devfs, tmpfs, gifs ...) but I can' mount /dev/sda1 ( USB disk ).

On your environment work also with physical disk?

L.

**Comment by alexbelgium** [comment]
Hi, no it also doesn't work in my environment... Even with the apparmor.txt I still need to disable protected mode. 

This site seems to say it is possible but I couldn't make it work  : https://www.google.com/amp/s/bestestredteam.com/2019/09/17/container-breakout/amp/
"SYS_ADMIN and AppArmor
Yet another escape involves using the --cap-add=SYS_ADMIN and --security-opt  apparmor=unconfirmed flags when launching the container. The significance of these flags is allowing us to use mount. Since even with SYS_ADMIN on, the default apparmor policy would prevent us from using it. "

Anyway, you addon is already great as it is! Thanks for creating and maintaining it! As it is working again ill close the issue if OK with you.
