### ISSUE TITLE
Percentage with Symbol

### ISSUE THREAD

**Issue by jonathanicq** [dianlight/hassio-addons#38]
Hi Man,
First of all, thanks for you plugin it's really handy

I've seen that your usage percentage is set with unit_of_measurement % but in the value of the sensor it cames with the symbol as well, that transform the result in a string blocking us to use it on graphics

I've by pass it by creating my own sensor, but I think that you could have a look on it.

Cheers !

![image](https://user-images.githubusercontent.com/67487968/108599582-ec790500-7389-11eb-939e-160e97fa4e6c.png)

**Comment by dianlight** [comment]
Fixed in  9.3.0-nas8
