### ISSUE TITLE
Backup option

### ISSUE THREAD

**Issue by cokeman0** [dianlight/hassio-addons#43]
Hi,

would it be possible to add an option to install a backup client (e.g. Jottacloud) into this fantastic add-on ? 

or an SSH access to the image, so we can install it ?

**Comment by cokeman0** [comment]
or better yet, Duplicati it backups to a lot of different backends

**Comment by dianlight** [comment]
I'll try to take a look at it but at first glance it doesn't seem like a great idea to put another software in the same docker. The target is always a low power cpu ( as Rpi2 ) so too many software can be a trouble.

I think is better to create a new add-on with backup capability and add the ability to backup samba share also.

Have you already check if there ae any add-on for backup?

L.

**Comment by cokeman0** [comment]
I have been looking for some backup software to put onto the HA (RPI4 here) so the NAS can be backed up, but I have not found any.

One guy have a duplicati addon, but it only works locally, so no SMB share supported. but. I like the idea of a Duplicati with SMB support.

but yes, the best solution would be a separate addon
