### ISSUE TITLE
Unable to mount usb drive

### ISSUE THREAD

**Issue by rywi** [dianlight/hassio-addons#44]
Unable to mount usb:

![image](https://user-images.githubusercontent.com/6751283/109415896-3b8aef80-79b3-11eb-88eb-11d79d4e1369.png)

![image](https://user-images.githubusercontent.com/6751283/109415932-5a898180-79b3-11eb-80ae-3956fcbf78c2.png)

**Comment by dianlight** [comment]
Your disk is label Andrzej not <Andrzej>. 

In the configuration example, the < and > symbols are just typographic to indicate that it is a parameter to be set.

**Comment by dianlight** [comment]
Any feedback?

**Comment by rywi** [comment]
Thank You 

[21:05:18] INFO: Protection Mode is false
[21:05:18] WARNING: MoreDisk option found!
[21:05:18] INFO: More Disks mounting.. Andrzej
[21:05:18] INFO: Mount Andrzej
[21:05:19] INFO: Success!
[cont-init.d] automount.sh: exited 0.
