### ISSUE TITLE
Can't use Time Machine

### ISSUE THREAD

**Issue by Luismm2311** [dianlight/hassio-addons#45]
I'm trying to backup my MacBook with an External HDD with the ext4 format connected to a Raspberry Pi 3B+ with Hassio OS.
I managed to install and start the SAMBA NAS add-on and I also my mac recognize successfully the HDD but wen I try to make the backup I get a message that says "Try again when homeassistant is available"
Moved a 387.4MB file to the disk and back via smb and verified the files with checksum and there was no problem
I have my raspberry pi connected to my router via cable.

Here is the log of the add-on

`[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] automount.sh: executing... 
[13:38:41] INFO: Protection Mode is false
[13:38:42] WARNING: MoreDisk option found!
[13:38:42] INFO: More Disks mounting.. TimeMachine
[13:38:42] INFO: Mount TimeMachine
[13:38:42] INFO: Success!
[cont-init.d] automount.sh: exited 0.
[cont-init.d] mqtt.sh: executing... 
[13:38:43] ERROR: Got unexpected response from the API: Service not enabled
[13:38:45] WARNING: No MQTT Server found. Homeassistant integration can't work!
[cont-init.d] mqtt.sh: exited 0.
[cont-init.d] samba.sh: executing... 
[13:38:47] INFO: Hostname: homeassistant
tdbsam_open: Converting version 0.0 database to version 4.0.
tdbsam_convert_backup: updated /var/lib/samba/private/passdb.tdb file.
Added user homeassistant.
[cont-init.d] samba.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
nmbd version 4.12.9 started.
Copyright Andrew Tridgell and the Samba Team 1992-2020
[services.d] done.
[13:38:48] INFO: Starting the AVAHI daemon for homeassistant...
daemon_ready: daemon 'nmbd' finished starting up and ready to serve connections
Waiting for daemon ...
smbd version 4.12.9 started.
Copyright Andrew Tridgell and the Samba Team 1992-2020
INFO: Profiling support unavailable in this build.
daemon_ready: daemon 'smbd' finished starting up and ready to serve connections
[13:38:49] WARNING: No MQTT config.
Failed to fetch record!
pcap cache not loaded
Failed to fetch record!
pcap cache not loaded
error in mds_init_ctx for: /TimeMachine
_mdssvc_open: Couldn't create policy handle for TimeMachine
*****
Samba name server HOMEASSISTANT is now a local master browser for workgroup WORKGROUP on subnet 172.17.0.1
*****
*****
Samba name server HOMEASSISTANT is now a local master browser for workgroup WORKGROUP on subnet 172.30.32.1
*****
*****
Samba name server HOMEASSISTANT is now a local master browser for workgroup WORKGROUP on subnet 192.168.0.105
*****
error in mds_init_ctx for: /TimeMachine
_mdssvc_open: Couldn't create policy handle for TimeMachine
fruit_pread_meta_stream: Removing [86ED7541-147C-5D9D-954B-81456388D056.sparsebundle:AFP_AfpInfo] after short read [0]
fruit_pread_meta_stream: Removing [86ED7541-147C-5D9D-954B-81456388D056.sparsebundle:AFP_AfpInfo] failed
Failed to fetch record!
pcap cache not loaded
Failed to fetch record!
pcap cache not loaded
[14:02:49] WARNING: No MQTT config.`

Here is my configuration:

`workgroup: WORKGROUP
username: homeassistant
password: 'xxxxxx'
interface: ''
allow_hosts:
  - 10.0.0.0/8
  - 172.16.0.0/12
  - 192.168.0.0/16
  - 'fe80::/10'
moredisks:
  - TimeMachine
veto_files:
  - ._*
  - .DS_Store
  - Thumbs.db
  - icon?
  - .Trashes
compatibility_mode: false
autodiscovery: {}`

Pelas help me, I don’t know what to do

**Comment by dianlight** [comment]
The error is truly strange.  
Usually that kind of error can occur if you try to make a TimeMachine backup via NFS without giving enough space for Policy metadata.

Can you tell me how you configured the Time Machine disk on the Mac side?  I expect you used tmutil command line right?

Try deleting the drive from the TM configuration and reconfigure it following the guide https://basilsalad.com/how-to/create-time-machine-backup-network-drive-lion/

L.

**Comment by timotoots** [comment]
I don't know if it would help with this specific issue. I am trying also to use this for Time Machine backup.

It might be that smb.conf would need some extra lines for that:
    vfs objects = catia fruit streams_xattr
    fruit:time machine = yes

https://mudge.name/2019/11/12/using-a-raspberry-pi-for-time-machine/

Could it be an option to be included in the plugin config?

**Comment by dianlight** [comment]
Take a look to sambanas/rootfs/tmp/moredisk.smb.conf 

vfs object and fruit are already set. 


L

**Comment by timotoots** [comment]
Oh yes, they really are.

It seems I had another problem. I had the volume name the same as another TM backup hard drive. Making name unique fixed it for me.

But actually if I check the logs, it show the same lines as the ones above. But it does work!

fruit_pread_meta_stream: Removing [C1FBBC44-AE0E-5D2C-B34E-8E98E2BAA66D.sparsebundle:AFP_AfpInfo] after short read [0]
fruit_pread_meta_stream: Removing [C1FBBC44-AE0E-5D2C-B34E-8E98E2BAA66D.sparsebundle:AFP_AfpInfo] failed
Failed to fetch record!
pcap cache not loaded
