### ISSUE TITLE
Access to files stored on NAS only with SMB 1 possible

### ISSUE THREAD

**Issue by Toffi32** [dianlight/hassio-addons#46]
Problem/Motivation

Access to files stored on NAS only with SMB 1 possible
With SMB 1 deactivated on NAS console reports “error opening file” … “stale file handle (116)”

Expected behavior
Use cifsversion according to setting in configuration - e.g. cifsversion: ‘3.0’

Actual behavior
Access to files on NAS only with SMB 1 activated on NAS possible.
Looks like Addon is set to SMB 1 permanently.

Steps to reproduce
see above

Proposed changes   (If you have a proposed change, workaround or fix, describe the rationale behind it)

My environment:
Add-on version: 2.4.2-dht3
You are running the latest version of this add-on.
System: Home Assistant OS 5.12  (armv7 / raspberrypi3)
Home Assistant Core: 2021.3.4
Home Assistant Supervisor: 2021.03.6
NAS: Firtzbox AVM 7490 latest firmware

**Comment by dianlight** [comment]
Can you post startups logs for addons?

**Comment by Toffi32** [comment]
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Hass.io Add-on: Plex Media Server with NAS
 Recorded media, live TV, online news, and podcasts ready to stream.
-----------------------------------------------------------
 Add-on version: 2.4.2-dht3
 You are running the latest version of this add-on.
 System: Home Assistant OS 5.12  (armv7 / raspberrypi3)
 Home Assistant Core: 2021.3.4
 Home Assistant Supervisor: 2021.03.6
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
Log level is set to DEBUG
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] plex.sh: executing... 
[cont-init.d] plex.sh: exited 0.
[cont-init.d] webtools.sh: executing... 
[cont-init.d] webtools.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[23:25:40] INFO: Starting the Plex Media Server...
[23:25:41] INFO: Network Disks mounting.. //192.168.178.1/Fritz-Home/TOSHIBA_EXT/Multimedia/Music/MP3
[23:25:41] INFO: Mount //192.168.178.1/Fritz-Home/TOSHIBA_EXT/Multimedia/Music/MP3
[23:25:41] INFO: Success!
