### ISSUE TITLE
Net dostupa k podklyuchennym (v konfige) direktoriyam 50 / 5000 Результаты перевода No access to connected (in config) directories 

### ISSUE THREAD

**Issue by GigaVik** [dianlight/hassio-addons#47]
The problem appeared about 2 months ago after some of the homeassistant updates.
There was no time to ask and I thought that during this time someone also had a similar problem ...
Protected mode disabled.

log:
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] automount.sh: executing... 
curl: (7) Couldn't connect to server
[20:53:15] ERROR: Something went wrong contacting the API
[20:53:15] INFO: Protection Mode is 
[20:53:15] WARNING: MoreDisk ignored because ADDON in Protected Mode!
[20:53:15] WARNING: 
[20:53:15] WARNING: A recommended add-on configuration option is not set.
[20:53:15] WARNING: 
[20:53:15] WARNING: The configuration key 'protected' seems to be empty.
[20:53:15] WARNING: 
[20:53:15] WARNING: 
[20:53:15] WARNING: Consider configuring this because:
[20:53:15] WARNING: moredisk only work when Protection mode is disabled
[20:53:15] WARNING: Check the add-on manual for more information.
[20:53:15] WARNING: 
[cont-init.d] automount.sh: exited 0.
[cont-init.d] mqtt.sh: executing... 
curl: (7) Couldn't connect to server
[20:53:15] ERROR: Something went wrong contacting the API
[20:53:17] WARNING: No MQTT Server found. Homeassistant integration can't work!
[cont-init.d] mqtt.sh: exited 0.
[cont-init.d] samba.sh: executing... 
curl: (7) Couldn't connect to server
[20:53:18] ERROR: Something went wrong contacting the API
[20:53:18] WARNING: Can't read hostname, using default.
[20:53:18] INFO: Hostname: hassio
tdbsam_open: Converting version 0.0 database to version 4.0.
tdbsam_convert_backup: updated /var/lib/samba/private/passdb.tdb file.
Added user homeassistant.
[cont-init.d] samba.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
nmbd version 4.12.9 started.
Copyright Andrew Tridgell and the Samba Team 1992-2020
open_socket_in(): socket() call failed: Permission denied
[20:53:19] INFO: Starting the AVAHI daemon for ...
Bad number of arguments
s6-svscanctl: fatal: unable to control /var/run/s6/services: supervisor not listening
[cont-finish.d] executing container finish scripts...
[cont-finish.d] mqtt.sh: executing... 
/usr/lib/bashio/config.sh: line 49: printf: write error: Broken pipe
[20:53:19] INFO: MQTT cleanup.
Error: Permission denied
[cont-finish.d] mqtt.sh: exited 1.
[cont-finish.d] umount.sh: executing... 
[20:53:19] INFO: Unmount drivers.
umount: /dev: target is busy.
[cont-finish.d] umount.sh: exited 32.
[cont-finish.d] done.
[s6-finish] waiting for services.
s6-svwait: fatal: unable to subscribe to events for /var/run/s6/services/s6-fdholderd: Read-only file system
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.

**Comment by dianlight** [comment]
The addon is unable to connect to the supervisor. 
Have you try to uninstall and reinstall the addon?
Can you post your host, supervisor and core version?

**Comment by GigaVik** [comment]
Yes, I tried reinstalling, completely uninstalling and reinstalling.  
My hass.io is installed in docker environment on ubuntu server x64 system.
I used your development because the official samba addon did not include any folders.  And your addon connected the section by part name.
I tried to find a solution myself based on the lines with errors but could not figure it out.
![Screenshot_20210328-061844_Home_Assistant](https://user-images.githubusercontent.com/25990377/112739426-c4368480-8f8d-11eb-8c9a-c3fe24426e86.png)
![IMG_20210328_062011](https://user-images.githubusercontent.com/25990377/112739427-c6004800-8f8d-11eb-905c-d0797ac03dfd.jpg)
![IMG_20210328_062035](https://user-images.githubusercontent.com/25990377/112739428-c6004800-8f8d-11eb-9b21-337ccfad7757.jpg)

**Comment by dianlight** [comment]
You don't need this addon if you are on Ubuntu. Configure the samba on your host outside the docker is a better solution and your able to mount disk at host level.

This addon need API from supervisor to access to operating systems but their are missing outside the standard config.

L.

**Comment by GigaVik** [comment]
Thank you very much for your advice :-) I was just too lazy to do it.  The addon is installed and configured in literally 3 clicks ... Until some of the HA updates, everything worked and it suited me.  I went to put the samba on the host ;-) 
Sorry for the "machine" English.
