### ISSUE TITLE
Unable to write ZIP file

### ISSUE THREAD

**Issue by tkupka** [dianlight/hassio-addons#48]
I have mounted USB disk with FAT32 FS.
`
workgroup: WORKGROUP
username: homeassistant
password: ***
interface: ''
allow_hosts:
  - XXX.XXX.0.0/24
moredisks:
  - KINGSTON
veto_files:
  - .DS_Store
  - '*.zip'
compatibility_mode: false
autodiscovery: {}
`

I can write into any folder shared by SMB, but no way to write `*.ZIP` file. Also there is a problem to write the file with national characters into `KINGSTON` share

**Comment by dianlight** [comment]
In your configuration you have set *.zip as veto files so *.zip can be created. 

I think it works as aspected! ;)

L.

**Comment by tkupka** [comment]
Sorry for that I was playing with config in between and copy wrong one. It behaves in same way if I remove the `*.zip` from veto_files:
`
workgroup: WORKGROUP
username: homeassistant
password: ***
interface: ''
allow_hosts:
  - X.X.0.0/24
moredisks:
  - KINGSTON
  - ADATA1
  - ADATA2
veto_files:
  - .DS_Store
  - '*.aa'
compatibility_mode: false
autodiscovery: {}
`
It behaves in following way:
* internal SD card no problem to copy zip file (content is real zip file)
* mounted external USB disk ( FAT32 and exFAT partitions)
* * unbale to write zip file - on fat32 partition file is copied but error happens. on exFAT nothing is written.
* * able to write exe file
* * rename exe file to zip file and this can be written
* * unable to delete the exe file when mounted drive is exFAT partition. On FAT32 it's fine
see 2 screnshots from copy on diffrent partition type and 1 from deleting

**Comment by dianlight** [comment]
ExtFat and Fat32 are fuse devices on the kernel used by haos. 
There are many issues on permission and performance. As you can see in the documentation the support is experimental ( =not supported ). I suggest you to use a native ext4 fs.

L

**Comment by tkupka** [comment]
OK ext4 is working fine.
