### ISSUE TITLE
[Samba NAS] Split MQTT integration device by shares/directories

### ISSUE THREAD

**Issue by ElVit** [dianlight/hassio-addons#50]
Hi @dianlight ,
first thanks for this nice addon.
At the moment all MQTT entities are shown in 1 device in HomeAssistant.
In my opinion it would be better if each share/directory will be displayed in a seperate device.

Also the default home assistant shares/directories (addons, backup, config, media, share, ssl) are probably always on the same disk.
So they will show always the same values.
Maybe it would be better to merge them to one device and also merge their sensors.

**Comment by dianlight** [comment]
Is a breaking charge for who has automations on ha based on actual sensor config. I will try to understand how implement this change in a compatible way.

**Comment by ElVit** [comment]
Thanks for the fast reply. 
To avoid a breaking change you could make an addon option for this feature and let the user decide how the mqtt messages will be added to Home Assistant.

**Comment by dianlight** [comment]
Relesed in #120
