### ISSUE TITLE
can't set up

### ISSUE THREAD

**Issue by Dilkins85** [dianlight/hassio-addons#51]
what am I doing unevenly? formatted the flash drive to ext4, put the usb label. but nothing appears either in the logs or on the network (((

**Comment by Dilkins85** [comment]
allow_hosts:
  - 10.0.0.0/8
  - 172.16.0.0/12
  - 192.168.0.0/16
  - fe80::/10
moredisks:
  - usb
  - <PARTITION LABEL>
veto_files:
  - ._*
  - .DS_Store
  - Thumbs.db
  - icon?
  - .Trashes
compatibility_mode: false
autodiscovery: {}

**Comment by dianlight** [comment]
```
moredisks:
  - USBLABEL
 ```
