### ISSUE TITLE
Issue: Latest update doesn't allow multiple mounts.

### ISSUE THREAD

**Issue by UnderclassAmigo** [dianlight/hassio-addons#58]
My config never changed and after updating the addon will only mount one drive, often mounting a drive under the wrong name.
According to the logs both mount successfully but only one ever shows and it's always the smaller drive. I am able to mount them both seperately but only one at a time, if I go to mount them both the small one claims the larger drives name and doesn't mount under it's own name. 
Example:
Library 4 tb and Internal 1 tb both mounted,
Both will mount successfully then only Library will be available but it will be the Internal disk labelled as 1 tb.

**Comment by dianlight** [comment]
Fixed in Release 9.5.1 nas3
