### ISSUE TITLE
[Samba NAS] Support for mount bind or just share a directory

### ISSUE THREAD

**Issue by tyjtyj** [dianlight/hassio-addons#6]
I try sharing a drive which already mount on the host system but getting error below 

[cont-init.d] automount.sh: executing... 
[00:59:43] WARNING: MoreDisk option found!
[00:59:44] INFO: More Disks mounting.. Seagate
[00:59:44] INFO: Mount Seagate
mount: /Seagate: /dev_/sdb1 already mounted or mount point busy.
[00:59:44] WARNING: Protection mode is ON. Unable to mount external drivers!

Anyway to support mount bind or just share the file system.

**Comment by dianlight** [comment]
Do you have turn off the "Protection mode"?

[image: image.png]

Il giorno ven 11 set 2020 alle ore 19:08 tyjtyj <notifications@github.com>
ha scritto:

**Comment by tyjtyj** [comment]
Yes protection is off. It says ON but it is OFF. 
To proof  the point i added another unmounted disk label

Seagate - mounted on debian host system
Backup Plus - unmounted

```
[04:08:17] WARNING: MoreDisk option found!
[04:08:17] INFO: More Disks mounting.. Seagate
Backup Plus
[04:08:17] INFO: Mount Seagate
mount: /Seagate: /dev_/sdb1 already mounted or mount point busy.
[04:08:17] INFO: Mount Backup Plus
FUSE exfat 1.3.0
[04:08:18] INFO: Success!
[cont-init.d] automount.sh: exited 0.
[cont-init.d] samba.sh: executing... 
[04:08:19] INFO: Hostname: raspberrypi
tdbsam_open: Converting version 0.0 database to version 4.0.
```

**Comment by dianlight** [comment]
> [04:08:17] INFO: Mount Backup Plus
> FUSE exfat 1.3.0

Sorry but I Don't understand, _Backup Plus_ is mounted according to the logs, why you say unmounted? 

What type of FS is _Segate_? 
Can you post your addon config?
On Debian host can you get the fstable of Segate (`fdisk -l <disk>` output )?

L.

**Comment by dianlight** [comment]
Sorry I only read now that the disk is already mounted on the host.
Multiplexed a disk block device is not supported on linux ( the only system I'know can is BeOS if you disable all buffers but it is a very dangerous thing with a filesystem.). 

To share a mounted disk you need to mount it in a subdirectory of `share` so is visible on the `share` exposed disk. Only a few directories on the host are visible from the addons.

L.

**Comment by tyjtyj** [comment]
Thanks for looking into this... Appreciate it. 

I tried mount bind in share directory but the directory shows empty in samba share. 

I will close this as this consider part of feature request and it is not possible with the restrain.
