### ISSUE TITLE
[Samba NAS] Mounting issue

### ISSUE THREAD

**Issue by pnstewart** [dianlight/hassio-addons#61]
Moved from [https://community.home-assistant.io/t/new-addon-samba-nas-mount-external-disk-and-share-it/172193/221?u=pnstewart]

Error message:
```
[cont-init.d] automount.sh: executing... 
[14:15:55] INFO: Protection Mode is false
[14:15:56] INFO: MoreDisk option found!
[14:15:56] INFO: MediaLibrary option found!
Warning: Permanently added '[192.168.100.2]:22222' (ECDSA) to the list of known hosts.
Tue Nov  2 14:15:57 CET 2021
[14:15:57] INFO: SSH connection to 192.168.100.2:22222 OK
[14:15:57] INFO: Available Disk Labels:
 External
[14:15:57] INFO: More Disks mounting.. External
[14:15:57] INFO: Mount External
mount: mounting /dev/disk/by-label/External on /mnt/data/supervisor/media/External failed: No such file or directory
[14:15:57] WARNING: Host Mount Fail!
[14:16:33] INFO: Success!
[cont-init.d] automount.sh: exited 0.
```
If the directory is manually created and permissions set to 777 then the error changes to "Permission denied"

Configuration:
```
workgroup: WORKGROUP
username: <removed>
password: <removed>
allow_hosts:
  - 192.168.100.0/16
moredisks:
  - External
medialibrary:
  enable: true
  ssh_private_key: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    
    -----END OPENSSH PRIVATE KEY-----
veto_files:
  - ._*
  - .DS_Store
  - Thumbs.db
compatibility_mode: false
autodiscovery: {}
```
This is running on a Pi4 with Hassos 6.6, Supervisor 2021.10.8, and Core 2021.10.7 (latest).
The disc is an SSD connected via USB3 to the Pi and formatted in ext4.

Any help would be greatly appreciated

**Comment by dianlight** [comment]
Can you connect with ssh and check the permission with `ls -al /mnt/data/supervisor/media/`

The result must be like
```
# ls -al /mnt/data/supervisor/media/
drwxr-xr-x    8 root     root          4096 Nov  1 14:16 .
drwxr-xr-x   12 root     root          4096 Nov  3 15:32 ..
drwxr-xr-x    3 root     root        131072 Nov  1 13:57 64GB
drwxr-xr-x    8 root     root          4096 Nov  3 16:18 LIBRARY
drwxr-xr-x    2 root     root           512 Jan  1  1970 usb-General_USB_Flash_Disk_0111607137301461-0:0-part1
#
```

The permission for  /mnt/data/supervisor/media/  need to be `drwxr-xr-x` and also for the mounting dir. ( External in you case ). Also the user and group need to be root:root.


If the user/group is root:root but permission differs try to change with the command:`chmod 0755 /mnt/data/supervisor/media` and  `chmod 0755 /mnt/data/supervisor/media/External`

**Comment by pnstewart** [comment]
There is nothing inside /mnt/
/mnt itself is drwxr-xr-r and root:root
I tried `mkdir -p /mnt/data/supervisor/media`, which created a directory with the permissions indicated.
Restarting the addon and the error changes to:
```
[22:50:14] INFO: Mount External
mount: mounting /dev/disk/by-label/External on /mnt/data/supervisor/media/External failed: Permission denied
[22:50:14] WARNING: Host Mount Fail!
[22:50:45] INFO: Success!
[cont-init.d] automount.sh: exited 0.
```

I did find an External directory under /media/ which has the same permissions. This feels like it might be a clue, but I have no idea what it means.

**Comment by dianlight** [comment]
You need to connect to host on 192.168.100.2:22222. 
If you don't see /mnt/data/supervisor/media/ mean you are connected to supervisor on standard port 22.

All your problem are on host side, if you don't need the "medialibrary" integration you can disable it and all should work.
```
...
medialibrary:
  enable: false
...
```

**Comment by pnstewart** [comment]
Thanks Lucio,
I was connecting with:
ssh -p 22222 ***@***.***
So it should have been on port 22222
Connecting with -p 22 does not work.

I can live without the medialibrary, so I disabled it as you suggested.

Great add-on, keep up the great work! :)

**Comment by felislynx-silae** [comment]
@dianlight i have same issue and i need medialibrary :)
i've connected via ssh port 22222, there was nothing in /mnt. So i've created those dirs, added chmod 0755 for all of them and now i have Permission denied while mounting.

**Comment by dianlight** [comment]
@felislynx-silae Please create a new issue with your environment,config, hassos version and addon logs.
