### ISSUE TITLE
query_name_response: Multiple (2) responses. Error's?

### ISSUE THREAD

**Issue by riddertommie** [dianlight/hassio-addons#63]
I'm getting lost off error's (at least i think they are) in my logfile.

_query_name_response: Multiple (2) responses received for a query on subnet 192.168.2.203 for name WORKGROUP<1d>.
This response was from IP 192.168.2.200, reporting an IP address of 192.168.2.200._

IP 192.168.2.203 is hassio
IP 192.168.2.200 is a PC with Ubuntu with als Samba on it

I even think that i makes the plugin stop

Are they error's or can i leave them? 

--edit--

sorry i missed a part

_daemon_ready: daemon 'smbd' finished starting up and ready to serve connections
query_name_response: Multiple (2) responses received for a query on subnet 192.168.2.203 for name WORKGROUP<1d>.
This response was from IP 192.168.2.200, reporting an IP address of 192.168.2.200.
Failed to fetch record!
pcap cache not loaded
Failed to fetch record!
pcap cache not loaded
Failed to fetch record!
pcap cache not loaded_

**Comment by dianlight** [comment]
Can be an error or not. It is the log for the handshake on the network for identify the master of the WORKGROUP cifs domain.

After the error the plugin should work as slave of the master identified. Do you have another evidence? Can you post the full log? Also the samba log on Ubuntu?

L.

**Comment by riddertommie** [comment]
Hassio:

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 0.banner.sh: executing... 
---------------------------------------------------_
 ____                  _           _   _           
/ ___|  __ _ _ __ ___ | |__   __ _| \ | | __ _ ___ 
\___ \ / _` | '_ ` _ \| '_ \ / _` |  \| |/ _` / __|
 ___) | (_| | | | | | | |_) | (_| | |\  | (_| \__ \
|____/ \__,_|_| |_| |_|_.__/ \__,_|_| \_|\__,_|___/
                                                   
                              _Version 9.5.1-nas4
---------------------------------------------------
[cont-init.d] 0.banner.sh: exited 0.
[cont-init.d] automount.sh: executing... 
[14:28:55] INFO: Protection Mode is false
[14:28:55] INFO: MoreDisk option found!
[14:28:55] INFO: MediaLibrary disabled in config. Disk are mounted only for this addon!
[14:28:56] INFO: More Disks mounting.. ToshTank
[14:28:56] INFO: Mount ToshTank
[14:28:56] INFO: Success!
[cont-init.d] automount.sh: exited 0.
[cont-init.d] mqtt.sh: executing... 
[cont-init.d] mqtt.sh: exited 0.
[cont-init.d] samba.sh: executing... 
[14:28:59] INFO: Using hostname=hassio interface=eth0
tdbsam_open: Converting version 0.0 database to version 4.0.
tdbsam_convert_backup: updated /var/lib/samba/private/passdb.tdb file.
Added user jarno.
[cont-init.d] samba.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[14:28:59] INFO: Starting the AVAHI daemon for hassio...
nmbd version 4.13.8 started.
Copyright Andrew Tridgell and the Samba Team 1992-2020
Waiting for daemon ...
daemon_ready: daemon 'nmbd' finished starting up and ready to serve connections
query_name_response: Multiple (2) responses received for a query on subnet 192.168.2.203 for name WORKGROUP<1d>.
This response was from IP 192.168.2.200, reporting an IP address of 192.168.2.200.
smbd version 4.13.8 started.
Copyright Andrew Tridgell and the Samba Team 1992-2020
INFO: Profiling support unavailable in this build.
daemon_ready: daemon 'smbd' finished starting up and ready to serve connections___

Tail part from ubuntu

  _Unable to find the Domain Master Browser name WORKGROUP<1b> for the workgroup WORKGROUP.
  Unable to sync browse lists in this workgroup.
[2021/11/04 14:12:09.354297,  0] ../../source3/nmbd/nmbd_browsesync.c:354(find_domain_master_name_query_fail)
  find_domain_master_name_query_fail:
  Unable to find the Domain Master Browser name WORKGROUP<1b> for the workgroup WORKGROUP.
  Unable to sync browse lists in this workgroup.
[2021/11/04 14:27:12.718366,  0] ../../source3/nmbd/nmbd_browsesync.c:354(find_domain_master_name_query_fail)
  find_domain_master_name_query_fail:
  Unable to find the Domain Master Browser name WORKGROUP<1b> for the workgroup WORKGROUP.
  Unable to sync browse lists in this workgroup.

Seems to be a corelation

**Comment by dianlight** [comment]
Samba is unable to identify the Domain Masert. It appends when you are in a multi network configuration. [LinuxTopia reference](https://www.linuxtopia.org/online_books/network_administration_guides/samba_reference_guide/17_NetworkBrowsing_11.html)

Despite the log all works right?

Is your Ubuntu Linux always on?  If yes set it as DM.  The parameters that you are looking for are:
```
local master = yes
perferred master = yes
```
These two should take care of your error messages concerning no master
browser. You may also want to consider using the following:
```
wins support = yes
```

**Comment by riddertommie** [comment]
> Despite the log all works right?

Sometimes the plugin stops working for no apparent reason, hence I am researching. 

I adapted the config on the Ubuntu server and the log is stable now. (i hope you ment "preferred master = Yes") :-D
But the plugin log is stil flooding with:

query_name_response: Multiple (2) responses received for a query on subnet 192.168.2.203 for name WORKGROUP<1d>.
This response was from IP 192.168.2.200, reporting an IP address of 192.168.2.200.

**Comment by dianlight** [comment]
Do you have multiple eth cards on Ubuntu? Or eth aliases? or wlan and eth active in same time?

L.

**Comment by riddertommie** [comment]
> Do you have multiple eth cards on Ubuntu? Or eth aliases? or wlan and eth active in same time?
> 
> L.

No, none off that.

I run Docker so i have multiple IP but that was not your question i think.

**Comment by dianlight** [comment]
The Ubuntu is the host or a Docker? Do you have any samba server running in a Docker?

**Comment by riddertommie** [comment]
Its a Ubuntu host with docker on it, but samba is not via docker but directly on the 'host' system.

So you get a lot off, container, IP I think they are called.  Range starting from 172. but only one real IP 192.168.2.200.

**Comment by dianlight** [comment]
The log is very strange there is a kind of echo in the network that makes multiply the broadcast wins for the detection of the Master.  
Do you have other PCs in the network? On hassio what other add-ons have you installed?

In any case it should not be a source of problems. You said it crashes after a while right? What happens you can't access the network drive anymore or it crashes hassio?

**Comment by riddertommie** [comment]
Bare with me.....

I have a Supervised (so no hassio but based on debian bullseye) installatie so that i can have acces to my USB harddisk. 
On hassio i run portainer with Urbackup (the reason that i want to access the HD) and Omada_controler for my wifi setup.

but sometimes the disk was 'gone' so urbackup writes to a unmounted mount point, the reason i start to investigate. (this i prevented with chattr +i /mountpoint). Downside of this that i don't know anymore if the disk is gone.

In hassio self i started a bare minumum of add-ons

file editor
log viewer
Mosquitto broker FYI, (i dont use mqtt in Samba NAS)
portainer Samba NAS
TasmAdmin

So its not that hassio that crashes but the drive is sometimes gone.

**Comment by dianlight** [comment]
> I have a Supervised (so no hassio but based on debian bullseye) installatie so that i can have acces to my USB harddisk.
> On hassio i run portainer with Urbackup (the reason that i want to access the HD) and Omada_controler for my wifi setup.

"hassio or no hassio this is the problem..."

Sorry for the digression but I didn't quite understand. If your installation is not based on HAssios ( HA Operating System ) as I understand, don't use sambaNas; simply mount samba on the host.
