### ISSUE TITLE
BUG: Repostitory structure for master is not compliant

### ISSUE THREAD

**Issue by anilkumarkatta204** [dianlight/hassio-addons#69]
When I am trying to import the customer repo into my home assistance it throwing "Repostitory structure for master is not compliant"

![image](https://user-images.githubusercontent.com/4068191/145681179-36e1c112-c982-4c4c-b085-dd77afe801ec.png)

**Comment by dianlight** [comment]
This is not an hacs repository. This is an addon repository only if you use hassos installation
