### ISSUE TITLE
Can't use of mqtt to send disk status data work:  Client mosq-eRKSkqOSg3iiBIO9av disconnected.

### ISSUE THREAD

**Issue by DenneyTang** [dianlight/hassio-addons#70]
**Mosquitto broker log**

> 1642250908: New client connected from 172.30.32.1 as mosq-Citoj0PkdQ6gywsxdF (p2, c1, k60, u'addons').
> 1642250908: Client mosq-Citoj0PkdQ6gywsxdF disconnected.
> 1642250968: New connection from 172.30.32.1 on port 1883.
> 1642250968: New client connected from 172.30.32.1 as mosq-eRKSkqOSg3iiBIO9av (p2, c1, k60, u'addons').
> 1642250968: Client mosq-eRKSkqOSg3iiBIO9av disconnected.
> 1642251029: New connection from 172.30.32.1 on port 1883.
> 1642251029: New client connected from 172.30.32.1 as mosq-tv68WzOejnE5LEj0m6 (p2, c1, k60, u'addons').
> 1642251029: Client mosq-tv68WzOejnE5LEj0m6 disconnected.
> 1642251089: New connection from 172.30.32.1 on port 1883.
> 1642251089: New client connected from 172.30.32.1 as mosq-iKSdWWELgDWcidLSi8 (p2, c1, k60, u'addons').
> 1642251089: Client mosq-iKSdWWELgDWcidLSi8 disconnected.
> 1642251149: New connection from 172.30.32.1 on port 1883.
> 1642251149: New client connected from 172.30.32.1 as mosq-chgrnJ3reMHzva7XzX (p2, c1, k60, u'addons').
> 1642251149: Client mosq-chgrnJ3reMHzva7XzX disconnected.
> 1642251209: New connection from 172.30.32.1 on port 1883.
> 1642251209: New client connected from 172.30.32.1 as mosq-xRNfAdKnyPHoUh73yW (p2, c1, k60, u'addons').
> 1642251209: Client mosq-xRNfAdKnyPHoUh73yW disconnected.
> 1642251269: New connection from 172.30.32.1 on port 1883.
> 1642251269: New client connected from 172.30.32.1 as mosq-4CgCSlTrfhZWAMnkQK (p2, c1, k60, u'addons').
> 1642251269: Client mosq-4CgCSlTrfhZWAMnkQK disconnected.
> 1642251329: New connection from 172.30.32.1 on port 1883.
> 1642251329: New client connected from 172.30.32.1 as mosq-kvYUbzETKgdSAaMVPz (p2, c1, k60, u'addons').
> 1642251329: Client mosq-kvYUbzETKgdSAaMVPz disconnected.
> 1642251389: New connection from 172.30.32.1 on port 1883.
> 1642251389: New client connected from 172.30.32.1 as mosq-JDk0kgkkKkGDaMYb5c (p2, c1, k60, u'addons').
> 1642251389: Client mosq-JDk0kgkkKkGDaMYb5c disconnected.
> 1642251450: New connection from 172.30.32.1 on port 1883.
> 1642251450: New client connected from 172.30.32.1 as mosq-TveNoaxXaVGmzA5DB3 (p2, c1, k60, u'addons').
> 1642251450: Client mosq-TveNoaxXaVGmzA5DB3 disconnected.
> 1642251510: New connection from 172.30.32.1 on port 1883.
> 1642251510: New client connected from 172.30.32.1 as mosq-mScFQthJN0AG6IVC9H (p2, c1, k60, u'addons').
> 1642251510: Client mosq-mScFQthJN0AG6IVC9H disconnected.
> 1642251570: New connection from 172.30.32.1 on port 1883.
> 1642251570: New client connected from 172.30.32.1 as mosq-KOVhPRMiz8fXsiV1Hb (p2, c1, k60, u'addons').
> 1642251570: Client mosq-KOVhPRMiz8fXsiV1Hb disconnected.
> 1642251630: New connection from 172.30.32.1 on port 1883.
> 1642251630: New client connected from 172.30.32.1 as mosq-GNLDDSoGTiVoLHHeTP (p2, c1, k60, u'addons').
> 1642251630: Client mosq-GNLDDSoGTiVoLHHeTP disconnected.
> 1642251690: New connection from 172.30.32.1 on port 1883.
> 1642251690: New client connected from 172.30.32.1 as mosq-klLPvbe6NQCcvtb1WD (p2, c1, k60, u'addons').
> 1642251690: Client mosq-klLPvbe6NQCcvtb1WD disconnected.
> 1642251750: New connection from 172.30.32.1 on port 1883.
> 1642251750: New client connected from 172.30.32.1 as mosq-qePyYqD5GLV2PtKNtS (p2, c1, k60, u'addons').
> 1642251750: Client mosq-qePyYqD5GLV2PtKNtS disconnected.
> 1642251810: New connection from 172.30.32.1 on port 1883.
> 1642251810: New client connected from 172.30.32.1 as mosq-Wt0Fd2bJEkpKKnYr9m (p2, c1, k60, u'addons').
> 1642251810: Client mosq-Wt0Fd2bJEkpKKnYr9m disconnected.
> 1642251871: New connection from 172.30.32.1 on port 1883.
> 1642251871: New client connected from 172.30.32.1 as mosq-asxcJyoOf1830BS6ci (p2, c1, k60, u'addons').
> 1642251871: Client mosq-asxcJyoOf1830BS6ci disconnected.
> 1642251931: New connection from 172.30.32.1 on port 1883.
> 1642251931: New client connected from 172.30.32.1 as mosq-bNbMqx26o2uNTmUzGs (p2, c1, k60, u'addons').
> 1642251931: Client mosq-bNbMqx26o2uNTmUzGs disconnected.
> 1642251936: Saving in-memory database to /data/mosquitto.db.
> 1642251991: New connection from 172.30.32.1 on port 1883.
> 1642251991: New client connected from 172.30.32.1 as mosq-Gdgo1JElnsizPykLA0 (p2, c1, k60, u'addons').
> 1642251991: Client mosq-Gdgo1JElnsizPykLA0 disconnected.
> 1642252051: New connection from 172.30.32.1 on port 1883.
> 1642252051: New client connected from 172.30.32.1 as mosq-GrcKL505x7NaeowZs1 (p2, c1, k60, u'addons').
> 1642252051: Client mosq-GrcKL505x7NaeowZs1 disconnected.
> 1642252111: New connection from 172.30.32.1 on port 1883.
> 1642252111: New client connected from 172.30.32.1 as mosq-UK39Juu5EdW2BdwBCV (p2, c1, k60, u'addons').
> 1642252111: Client mosq-UK39Juu5EdW2BdwBCV disconnected.
> 1642252171: New connection from 172.30.32.1 on port 1883.
> 1642252171: New client connected from 172.30.32.1 as mosq-cN5G1MaAQxZ6nqsKDD (p2, c1, k60, u'addons').
> 1642252171: Client mosq-cN5G1MaAQxZ6nqsKDD disconnected.
> 1642252231: New connection from 172.30.32.1 on port 1883.
> 1642252231: New client connected from 172.30.32.1 as mosq-X4SdsVPrAcMLeQKcuJ (p2, c1, k60, u'addons').
> 1642252231: Client mosq-X4SdsVPrAcMLeQKcuJ disconnected.
> 1642252292: New connection from 172.30.32.1 on port 1883.
> 1642252292: New client connected from 172.30.32.1 as mosq-64ymKuTkfA8cCt66Kx (p2, c1, k60, u'addons').
> 1642252292: Client mosq-64ymKuTkfA8cCt66Kx disconnected.
> 1642252352: New connection from 172.30.32.1 on port 1883.
> 1642252352: New client connected from 172.30.32.1 as mosq-LEAbA6DTu5O1r0AwPG (p2, c1, k60, u'addons').
> 1642252352: Client mosq-LEAbA6DTu5O1r0AwPG disconnected.
> 1642252412: New connection from 172.30.32.1 on port 1883.
> 1642252412: New client connected from 172.30.32.1 as mosq-MUmoCGiu9lCy5qtVBn (p2, c1, k60, u'addons').
> 1642252412: Client mosq-MUmoCGiu9lCy5qtVBn disconnected.
> 1642252423: Client hassmart_3key_module_AA4C16 has exceeded timeout, disconnecting.
> 1642252428: New connection from 10.10.10.216 on port 1883.
> {"result": "ok", "data": {}}1642252428: New client connected from 10.10.10.216 as hassmart_3key_module_AA4C16 (p2, c1, k15, u'mqtt').
> 1642252472: New connection from 172.30.32.1 on port 1883.
> 1642252472: New client connected from 172.30.32.1 as mosq-A3aeKnnKddDmMYVpZd (p2, c1, k60, u'addons').
> 1642252472: Client mosq-A3aeKnnKddDmMYVpZd disconnected.
> 1642252532: New connection from 172.30.32.1 on port 1883.
> 1642252532: New client connected from 172.30.32.1 as mosq-UA52EJdmkJCFa1vKSc (p2, c1, k60, u'addons').
> 1642252532: Client mosq-UA52EJdmkJCFa1vKSc disconnected.
> 1642252592: New connection from 172.30.32.1 on port 1883.
> 1642252592: New client connected from 172.30.32.1 as mosq-jdrpRX74744YitZv7K (p2, c1, k60, u'addons').
> 1642252592: Client mosq-jdrpRX74744YitZv7K disconnected.
> 1642252652: New connection from 172.30.32.1 on port 1883.
> 1642252652: New client connected from 172.30.32.1 as mosq-PHbtHMkDJlwSFbDuQD (p2, c1, k60, u'addons').
> 1642252652: Client mosq-PHbtHMkDJlwSFbDuQD disconnected.
> 1642252713: New connection from 172.30.32.1 on port 1883.
> 1642252713: New client connected from 172.30.32.1 as mosq-r1CATvxr7mdkrg9bi1 (p2, c1, k60, u'addons').
> 1642252713: Client mosq-r1CATvxr7mdkrg9bi1 disconnected.
> 1642252773: New connection from 172.30.32.1 on port 1883.
> 1642252773: New client connected from 172.30.32.1 as mosq-uW7MDmeevIeIQP609N (p2, c1, k60, u'addons').
> 1642252773: Client mosq-uW7MDmeevIeIQP609N disconnected.
> 1642252833: New connection from 172.30.32.1 on port 1883.

**### Mosquitto broker config**

> certfile: fullchain.pem
> customize:
>   active: false
>   folder: mosquitto
> keyfile: privkey.pem
> logins: []
> require_certificate: false
> anonymous: true

**### Samba NAS config**

> workgroup: WORKGROUP
> username: 
> password: 
> allow_hosts:
>   - 10.0.0.0/8
>   - 172.16.0.0/12
>   - 192.168.0.0/16
>   - fe80::/10
> moredisks:
>   - share
> available_disks_log: true
> medialibrary:
>   enable: true
>   ssh_private_key: |
>     -----BEGIN OPENSSH PRIVATE KEY-----
> 
>     -----END OPENSSH PRIVATE KEY-----
> veto_files:
>   - ._*
>   - .DS_Store
>   - Thumbs.db
>   - icon?
>   - .Trashes
> compatibility_mode: true
> autodiscovery: {}

**Comment by dianlight** [comment]
The mqtt log is normal. The client integration is not persistent. At every update: connect, send data, disconnect.

I don't see moredisks value in your config is correct?

Can you share also the NAS addon log?

L.

**Comment by DenneyTang** [comment]
> The mqtt log is normal. The client integration is not persistent. At every update: connect, send data, disconnect.
> 
> I don't see moredisks value in your config is correct?
> 
> Can you share also the NAS addon log?
> 
> L.

Thanks your reply and your great jobs !

My NAS addon log:

> [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
> [s6-init] ensuring user provided files have correct perms...exited 0.
> [fix-attrs.d] applying ownership & permissions fixes...
> [fix-attrs.d] done.
> [cont-init.d] executing container initialization scripts...
> [cont-init.d] 0.banner.sh: executing... 
> ---------------------------------------------------
>  ____                  _           _   _           
> / ___|  __ _ _ __ ___ | |__   __ _| \ | | __ _ ___ 
> \___ \ / _` | '_ ` _ \| '_ \ / _` |  \| |/ _` / __|
>  ___) | (_| | | | | | | |_) | (_| | |\  | (_| \__ \
> |____/ \__,_|_| |_| |_|_.__/ \__,_|_| \_|\__,_|___/
>                                                    
>                               Version 9.5.1-nas4
> ---------------------------------------------------
> [cont-init.d] 0.banner.sh: exited 0.
> [cont-init.d] automount.sh: executing... 
> [22:46:23] INFO: Protection Mode is false
> [22:46:23] INFO: MoreDisk option found!
> [22:46:24] INFO: MediaLibrary option found!
> Warning: Permanently added '[10.10.10.107]:22222' (ECDSA) to the list of known hosts.
> Mon Jan 17 14:46:27 UTC 2022
> [22:46:27] INFO: SSH connection to 10.10.10.107:22222 OK
> [22:46:28] INFO: Available Disk Labels:
>  share
> [22:46:28] INFO: More Disks mounting.. share
> [22:46:28] INFO: Mount share
> [22:46:29] INFO: Success!
> [cont-init.d] automount.sh: exited 0.
> [cont-init.d] mqtt.sh: executing... 
> [cont-init.d] mqtt.sh: exited 0.
> [cont-init.d] samba.sh: executing... 
> [22:46:37] INFO: Using hostname=homeassistant interface=eth0
> tdbsam_open: Converting version 0.0 database to version 4.0.
> tdbsam_convert_backup: updated /var/lib/samba/private/passdb.tdb file.
> Added user admin.
> [cont-init.d] samba.sh: exited 0.
> [cont-init.d] done.
> [services.d] starting services
> [services.d] done.
> [22:46:42] INFO: Starting the MQTT daemon for disks info...
> [22:46:42] INFO: Starting the AVAHI daemon for homeassistant...
> nmbd version 4.13.8 started.
> Copyright Andrew Tridgell and the Samba Team 1992-2020
> daemon_ready: daemon 'nmbd' finished starting up and ready to serve connections
> Waiting for daemon ...
> smbd version 4.13.8 started.
> Copyright Andrew Tridgell and the Samba Team 1992-2020
> INFO: Profiling support unavailable in this build.
> daemon_ready: daemon 'smbd' finished starting up and ready to serve connections
> [22:46:43] INFO: Sending MQTT autodiscovery...
> Failed to fetch record!
> pcap cache not loaded
> receive_smb_raw_talloc failed for client ipv4:10.10.10.168:35814 read error = NT_STATUS_CONNECTION_RESET.

**Comment by dianlight** [comment]
All seems ok. 
Con you use a client and connect to MQTT and check if the message are published?

You will see sambanas sensor in homeassistant/sensor/sambanas topic as follow:

![image](https://user-images.githubusercontent.com/365884/149807035-caf2b12d-c524-4cec-88b3-8815d0b3dcd7.png)


 ( if you don't know other clinet I suggest you http://mqtt-explorer.com/ that is very simple )

**Comment by DenneyTang** [comment]
i try MQTT Explorer , it's seems OK.

![image](https://user-images.githubusercontent.com/19922795/150047188-f8cf1a68-e8a8-4d58-90e2-f67194fdedde.png)



and, I found some strange logs in SAMBANAS。

>  [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
> [s6-init] ensuring user provided files have correct perms...exited 0.
> [fix-attrs.d] applying ownership & permissions fixes...
> [fix-attrs.d] done.
> [cont-init.d] executing container initialization scripts...
> [cont-init.d] 0.banner.sh: executing... 
> ---------------------------------------------------
>  ____                  _           _   _           
> / ___|  __ _ _ __ ___ | |__   __ _| \ | | __ _ ___ 
> \___ \ / _` | '_ ` _ \| '_ \ / _` |  \| |/ _` / __|
>  ___) | (_| | | | | | | |_) | (_| | |\  | (_| \__ \
> |____/ \__,_|_| |_| |_|_.__/ \__,_|_| \_|\__,_|___/
>                                                    
>                               Version 9.5.1-nas4
> ---------------------------------------------------
> [cont-init.d] 0.banner.sh: exited 0.
> [cont-init.d] automount.sh: executing... 
> [08:30:32] INFO: Protection Mode is false
> [08:30:32] INFO: MoreDisk option found!
> [08:30:33] INFO: MediaLibrary option found!
> Warning: Permanently added '[10.10.10.107]:22222' (ECDSA) to the list of known hosts.
> Tue Jan 18 00:30:36 UTC 2022
> [08:30:36] INFO: SSH connection to 10.10.10.107:22222 OK
> [08:30:37] INFO: Available Disk Labels:
>  share
> [08:30:37] INFO: More Disks mounting.. share
> [08:30:37] INFO: Mount share
> [08:30:38] INFO: Success!
> [cont-init.d] automount.sh: exited 0.
> [cont-init.d] mqtt.sh: executing... 
> [cont-init.d] mqtt.sh: exited 0.
> [cont-init.d] samba.sh: executing... 
> [08:30:45] INFO: Using hostname=homeassistant interface=eth0
> tdbsam_open: Converting version 0.0 database to version 4.0.
> tdbsam_convert_backup: updated /var/lib/samba/private/passdb.tdb file.
> Added user admin.
> [cont-init.d] samba.sh: exited 0.
> [cont-init.d] done.
> [services.d] starting services
> [services.d] done.
> [08:30:53] INFO: Starting the MQTT daemon for disks info...
> [08:30:53] INFO: Starting the AVAHI daemon for homeassistant...
> [08:31:10] INFO: Sending MQTT autodiscovery...
> Waiting for daemon ...
> nmbd version 4.13.8 started.
> Copyright Andrew Tridgell and the Samba Team 1992-2020
> daemon_ready: daemon 'nmbd' finished starting up and ready to serve connections
> smbd version 4.13.8 started.
> Copyright Andrew Tridgell and the Samba Team 1992-2020
> INFO: Profiling support unavailable in this build.
> daemon_ready: daemon 'smbd' finished starting up and ready to serve connections
> Failed to fetch record!
> pcap cache not loaded
> Got SIGTERM, quitting.
> Got SIGTERM: going down...
> [cont-finish.d] executing container finish scripts...
> [cont-finish.d] mqtt.sh: executing... 
> [08:31:27] INFO: MQTT cleanup.
> homeassistant/sensor/sambanas/a_size/config {"name": "sambanas Size /config", "unit_of_measurement": "Kb","unique_id":"sambanas_size_config","device":{"identifiers":["sambanas"],"name": "Samba Nas Sensors", "model": "Samba Version 4.13.8", "manufacturer": "@Dianlight"},"icon":"mdi:harddisk","value_template": "{{ value_json.size_config}}", "state_topic": "homeassistant/sensor/sambanas/state"}
> homeassistant/sensor/sambanas/a_used/config {"name": "sambanas Used /config", "unit_of_measurement": "Kb","unique_id":"sambanas_used_config","device":{"identifiers":["sambanas"],"name": "Samba Nas Sensors", "model": "Samba Version 4.13.8", "manufacturer": "@Dianlight"},"icon":"mdi:harddisk", "value_template": "{{ value_json.used_config}}", "state_topic": "homeassistant/sensor/sambanas/state"}
> homeassistant/sensor/sambanas/a_available/config {"name": "sambanas Available /config", "unit_of_measurement": "Kb","unique_id":"sambanas_available_config","device":{"identifiers":["sambanas"],"name": "Samba Nas Sensors", "model": "Samba Version 4.13.8", "manufacturer": "@Dianlight"},"icon":"mdi:harddisk", "value_template": "{{ value_json.available_config}}", "state_topic": "homeassistant/sensor/sambanas/state"}
> homeassistant/sensor/sambanas/a_use/config {"name": "sambanas Use% /config", "unit_of_measurement": "%","unique_id":"sambanas_use_config","device":{"identifiers":["sambanas"],"name": "Samba Nas Sensors", "model": "Samba Version 4.13.8", "manufacturer": "@Dianlight"},"icon":"mdi:harddisk", "value_template": "{{ value_json.use_config}}", "state_topic": "homeassistant/sensor/sambanas/state"}
> homeassistant/sensor/sambanas/b_size/config {"name": "sambanas Size /addons", "unit_of_measurement": "Kb","unique_id":"sambanas_size_addons","device":{"identifiers":["sambanas"],"name": "Samba Nas Sensors", "model": "Samba Version 4.13.8", "manufacturer": "@Dianlight"},"icon":"mdi:harddisk","value_template": "{{ value_json.size_addons}}", "state_topic": "homeassistant/sensor/sambanas/state"}
> homeassistant/sensor/sambanas/b_used/config {"name": "sambanas Used /addons", "unit_of_measurement": "Kb","unique_id":"sambanas_used_addons","device":{"identifiers":["sambanas"],"name": "Samba Nas Sensors", "model": "Samba Version 4.13.8", "manufacturer": "@Dianlight"},"icon":"mdi:harddisk", "value_template": "{{ value_json.used_addons}}", "state_topic": "homeassistant/sensor/sambanas/state"}
> homeassistant/sensor/sambanas/b_available/config {"name": "sambanas Available /addons", "unit_of_measurement": "Kb","unique_id":"sambanas_available_addons","device":{"identifiers":["sambanas"],"name": "Samba Nas Sensors", "model": "Samba Version 4.13.8", "manufacturer": "@Dianlight"},"icon":"mdi:harddisk", "value_template": "{{ value_json.available_addons}}", "state_topic": "homeassistant/sensor/sambanas/state"}
> homeassistant/sensor/sambanas/b_use/config {"name": "sambanas Use% /addons", "unit_of_measurement": "%","unique_id":"sambanas_use_addons","device":{"identifiers":["sambanas"],"name": "Samba Nas Sensors", "model": "Samba Version 4.13.8", "manufacturer": "@Dianlight"},"icon":"mdi:harddisk", "value_template": "{{ value_json.use_addons}}", "state_topic": "homeassistant/sensor/sambanas/state"}
> homeassistant/sensor/sambanas/c_size/config {"name": "sambanas Size /ssl", "unit_of_measurement": "Kb","unique_id":"sambanas_size_ssl","device":{"identifiers":["sambanas"],"name": "Samba Nas Sensors", "model": "Samba Version 4.13.8", "manufacturer": "@Dianlight"},"icon":"mdi:harddisk","value_template": "{{ value_json.size_ssl}}", "state_topic": "homeassistant/sensor/sambanas/state"}
> homeassistant/sensor/sambanas/c_used/config {"name": "sambanas Used /ssl", "unit_of_measurement": "Kb","unique_id":"sambanas_used_ssl","device":{"identifiers":["sambanas"],"name": "Samba Nas Sensors", "model": "Samba Version 4.13.8", "manufacturer": "@Dianlight"},"icon":"mdi:harddisk", "value_template": "{{ value_json.used_ssl}}", "state_topic": "homeassistant/sensor/sambanas/state"}
> homeassistant/sensor/sambanas/c_available/config {"name": "sambanas Available /ssl", "unit_of_measurement": "Kb","unique_id":"sambanas_available_ssl","device":{"identifiers":["sambanas"],"name": "Samba Nas Sensors", "model": "Samba Version 4.13.8", "manufacturer": "@Dianlight"},"icon":"mdi:harddisk", "value_template": "{{ value_json.available_ssl}}", "state_topic": "homeassistant/sensor/sambanas/state"}
> homeassistant/sensor/sambanas/c_use/config {"name": "sambanas Use% /ssl", "unit_of_measurement": "%","unique_id":"sambanas_use_ssl","device":{"identifiers":["sambanas"],"name": "Samba Nas Sensors", "model": "Samba Version 4.13.8", "manufacturer": "@Dianlight"},"icon":"mdi:harddisk", "value_template": "{{ value_json.use_ssl}}", "state_topic": "homeassistant/sensor/sambanas/state"}
> homeassistant/sensor/sambanas/d_size/config {"name": "sambanas Size /share", "unit_of_measurement": "Kb","unique_id":"sambanas_size_share","device":{"identifiers":["sambanas"],"name": "Samba Nas Sensors", "model": "Samba Version 4.13.8", "manufacturer": "@Dianlight"},"icon":"mdi:harddisk","value_template": "{{ value_json.size_share}}", "state_topic": "homeassistant/sensor/sambanas/state"}
> homeassistant/sensor/sambanas/d_used/config {"name": "sambanas Used /share", "unit_of_measurement": "Kb","unique_id":"sambanas_used_share","device":{"identifiers":["sambanas"],"name": "Samba Nas Sensors", "model": "Samba Version 4.13.8", "manufacturer": "@Dianlight"},"icon":"mdi:harddisk", "value_template": "{{ value_json.used_share}}", "state_topic": "homeassistant/sensor/sambanas/state"}
> homeassistant/sensor/sambanas/d_available/config {"name": "sambanas Available /share", "unit_of_measurement": "Kb","unique_id":"sambanas_available_share","device":{"identifiers":["sambanas"],"name": "Samba Nas Sensors", "model": "Samba Version 4.13.8", "manufacturer": "@Dianlight"},"icon":"mdi:harddisk", "value_template": "{{ value_json.available_share}}", "state_topic": "homeassistant/sensor/sambanas/state"}
> homeassistant/sensor/sambanas/d_use/config {"name": "sambanas Use% /share", "unit_of_measurement": "%","unique_id":"sambanas_use_share","device":{"identifiers":["sambanas"],"name": "Samba Nas Sensors", "model": "Samba Version 4.13.8", "manufacturer": "@Dianlight"},"icon":"mdi:harddisk", "value_template": "{{ value_json.use_share}}", "state_topic": "homeassistant/sensor/sambanas/state"}
> homeassistant/sensor/sambanas/e_size/config {"name": "sambanas Size /backup", "unit_of_measurement": "Kb","unique_id":"sambanas_size_backup","device":{"identifiers":["sambanas"],"name": "Samba Nas Sensors", "model": "Samba Version 4.13.8", "manufacturer": "@Dianlight"},"icon":"mdi:harddisk","value_template": "{{ value_json.size_backup}}", "state_topic": "homeassistant/sensor/sambanas/state"}
> homeassistant/sensor/sambanas/e_used/config {"name": "sambanas Used /backup", "unit_of_measurement": "Kb","unique_id":"sambanas_used_backup","device":{"identifiers":["sambanas"],"name": "Samba Nas Sensors", "model": "Samba Version 4.13.8", "manufacturer": "@Dianlight"},"icon":"mdi:harddisk", "value_template": "{{ value_json.used_backup}}", "state_topic": "homeassistant/sensor/sambanas/state"}
> homeassistant/sensor/sambanas/e_available/config {"name": "sambanas Available /backup", "unit_of_measurement": "Kb","unique_id":"sambanas_available_backup","device":{"identifiers":["sambanas"],"name": "Samba Nas Sensors", "model": "Samba Version 4.13.8", "manufacturer": "@Dianlight"},"icon":"mdi:harddisk", "value_template": "{{ value_json.available_backup}}", "state_topic": "homeassistant/sensor/sambanas/state"}
> homeassistant/sensor/sambanas/e_use/config {"name": "sambanas Use% /backup", "unit_of_measurement": "%","unique_id":"sambanas_use_backup","device":{"identifiers":["sambanas"],"name": "Samba Nas Sensors", "model": "Samba Version 4.13.8", "manufacturer": "@Dianlight"},"icon":"mdi:harddisk", "value_template": "{{ value_json.use_backup}}", "state_topic": "homeassistant/sensor/sambanas/state"}
> homeassistant/sensor/sambanas/f_size/config {"name": "sambanas Size /media", "unit_of_measurement": "Kb","unique_id":"sambanas_size_media","device":{"identifiers":["sambanas"],"name": "Samba Nas Sensors", "model": "Samba Version 4.13.8", "manufacturer": "@Dianlight"},"icon":"mdi:harddisk","value_template": "{{ value_json.size_media}}", "state_topic": "homeassistant/sensor/sambanas/state"}
> homeassistant/sensor/sambanas/f_used/config {"name": "sambanas Used /media", "unit_of_measurement": "Kb","unique_id":"sambanas_used_media","device":{"identifiers":["sambanas"],"name": "Samba Nas Sensors", "model": "Samba Version 4.13.8", "manufacturer": "@Dianlight"},"icon":"mdi:harddisk", "value_template": "{{ value_json.used_media}}", "state_topic": "homeassistant/sensor/sambanas/state"}
> homeassistant/sensor/sambanas/f_available/config {"name": "sambanas Available /media", "unit_of_measurement": "Kb","unique_id":"sambanas_available_media","device":{"identifiers":["sambanas"],"name": "Samba Nas Sensors", "model": "Samba Version 4.13.8", "manufacturer": "@Dianlight"},"icon":"mdi:harddisk", "value_template": "{{ value_json.available_media}}", "state_topic": "homeassistant/sensor/sambanas/state"}
> homeassistant/sensor/sambanas/f_use/config {"name": "sambanas Use% /media", "unit_of_measurement": "%","unique_id":"sambanas_use_media","device":{"identifiers":["sambanas"],"name": "Samba Nas Sensors", "model": "Samba Version 4.13.8", "manufacturer": "@Dianlight"},"icon":"mdi:harddisk", "value_template": "{{ value_json.use_media}}", "state_topic": "homeassistant/sensor/sambanas/state"}
> homeassistant/sensor/sambanas/g_size/config {"name": "sambanas Size /share", "unit_of_measurement": "Kb","unique_id":"sambanas_size_share","device":{"identifiers":["sambanas"],"name": "Samba Nas Sensors", "model": "Samba Version 4.13.8", "manufacturer": "@Dianlight"},"icon":"mdi:harddisk","value_template": "{{ value_json.size_share}}", "state_topic": "homeassistant/sensor/sambanas/state"}
> homeassistant/sensor/sambanas/g_used/config {"name": "sambanas Used /share", "unit_of_measurement": "Kb","unique_id":"sambanas_used_share","device":{"identifiers":["sambanas"],"name": "Samba Nas Sensors", "model": "Samba Version 4.13.8", "manufacturer": "@Dianlight"},"icon":"mdi:harddisk", "value_template": "{{ value_json.used_share}}", "state_topic": "homeassistant/sensor/sambanas/state"}
> homeassistant/sensor/sambanas/g_available/config {"name": "sambanas Available /share", "unit_of_measurement": "Kb","unique_id":"sambanas_available_share","device":{"identifiers":["sambanas"],"name": "Samba Nas Sensors", "model": "Samba Version 4.13.8", "manufacturer": "@Dianlight"},"icon":"mdi:harddisk", "value_template": "{{ value_json.available_share}}", "state_topic": "homeassistant/sensor/sambanas/state"}
> homeassistant/sensor/sambanas/g_use/config {"name": "sambanas Use% /share", "unit_of_measurement": "%","unique_id":"sambanas_use_share","device":{"identifiers":["sambanas"],"name": "Samba Nas Sensors", "model": "Samba Version 4.13.8", "manufacturer": "@Dianlight"},"icon":"mdi:harddisk", "value_template": "{{ value_json.use_share}}", "state_topic": "homeassistant/sensor/sambanas/state"}

**Comment by dianlight** [comment]
Yes is wrong.
Can you try to delete sambanas sensor in MQTT ( select sambanas and Trash icon on the left panel ) and restart the addon?

This right tree must be:

```homeassistant/sensor/sambanas/<a-z>_<size-used-available>``` for autodiscovery
```homeassistant/sensor/sambanas/state```  for actual sensors data

I suppose is an old autodiscovery and the actual implementation don't send any data to MQTT for some errors....

Do you have more than 1 MQTT server?

L.

**Comment by DenneyTang** [comment]
> Yes is wrong. Can you try to delete sambanas sensor in MQTT ( select sambanas and Trash icon on the left panel ) and restart the addon?
> 
> This right tree must be:
> 
> `homeassistant/sensor/sambanas/<a-z>_<size-used-available>` for autodiscovery `homeassistant/sensor/sambanas/state` for actual sensors data
> 
> I suppose is an old autodiscovery and the actual implementation don't send any data to MQTT for some errors....
> 
> Do you have more than 1 MQTT server?
> 
> L.

Thanks for your helps！I try delete  Mosquitto broker in integrations->menu->delete，then restart HA CORE , It worked like a champ！
