### ISSUE TITLE
Can't use by TimeMachine

### ISSUE THREAD

**Issue by unCleanCode** [dianlight/hassio-addons#71]
After I've configured the system with an attached ext4 external hard drive - TimeMachine doesn't see this disc as an option to backup itself to.

Not sure if that's related or not, but I also wasn't able to see homeassistant.local on Network page in macOS, up until I directly connected to it via smb://homeassistant.local. On official Samba add-on the homeassistant.local appeared in Network page automatically

My config file:

`workgroup: WORKGROUP
username: username
password: password
allow_hosts:
  - 10.0.0.0/8
  - 172.16.0.0/12
  - 192.168.0.0/16
  - fe80::/10
moredisks:
  - TIMEMACHINE
available_disks_log: false
medialibrary:
  enable: false
  ssh_private_key: <YOU SUPER SECRET PRIVATE KEY>
veto_files:
  - ._*
  - .DS_Store
  - Thumbs.db
  - icon?
  - .Trashes
  - addons
  - backup
  - config
  - share
  - ssl
compatibility_mode: false
autodiscovery: {}
mqtt_enable: false`

Logs:
`[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 0.banner.sh: executing... 
---------------------------------------------------
 ____                  _           _   _           
/ ___|  __ _ _ __ ___ | |__   __ _| \ | | __ _ ___ 
\___ \ / _` | '_ ` _ \| '_ \ / _` |  \| |/ _` / __|
 ___) | (_| | | | | | | |_) | (_| | |\  | (_| \__ \
|____/ \__,_|_| |_| |_|_.__/ \__,_|_| \_|\__,_|___/
                                                   
                              Version 9.5.1-nas4
---------------------------------------------------
[cont-init.d] 0.banner.sh: exited 0.
[cont-init.d] automount.sh: executing... 
[19:06:35] INFO: Protection Mode is false
[19:06:35] INFO: MoreDisk option found!
[19:06:35] INFO: MediaLibrary disabled in config. Disk are mounted only for this addon!
[19:06:35] INFO: More Disks mounting.. TIMEMACHINE
[19:06:36] INFO: Mount TIMEMACHINE
[19:06:36] INFO: Success!
[cont-init.d] automount.sh: exited 0.
[cont-init.d] mqtt.sh: executing... 
[19:06:36] ERROR: Got unexpected response from the API: Service not enabled
[19:06:37] WARNING: No MQTT Server found. Homeassistant integration can't work!
[cont-init.d] mqtt.sh: exited 0.
[cont-init.d] samba.sh: executing... 
[19:06:39] INFO: Using hostname=homeassistant interface=eth0
tdbsam_open: Converting version 0.0 database to version 4.0.
tdbsam_convert_backup: updated /var/lib/samba/private/passdb.tdb file.
Added user homeassistant.
[cont-init.d] samba.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
nmbd version 4.13.8 started.
Copyright Andrew Tridgell and the Samba Team 1992-2020
[services.d] done.
daemon_ready: daemon 'nmbd' finished starting up and ready to serve connections
[19:06:39] INFO: Starting the AVAHI daemon for homeassistant...
Waiting for daemon ...
smbd version 4.13.8 started.
Copyright Andrew Tridgell and the Samba Team 1992-2020
INFO: Profiling support unavailable in this build.
daemon_ready: daemon 'smbd' finished starting up and ready to serve connections
*****
Samba name server HOMEASSISTANT is now a local master browser for workgroup WORKGROUP on subnet 192.168.20.49
*****
Failed to fetch record!
pcap cache not loaded
error in mds_init_ctx for: /media/TIMEMACHINE
_mdssvc_open: Couldn't create policy handle for TIMEMACHINE
Failed to fetch record!
pcap cache not loaded
Failed to fetch record!
pcap cache not loaded
Failed to fetch record!
pcap cache not loaded
error in mds_init_ctx for: /ssl
_mdssvc_open: Couldn't create policy handle for ssl
Failed to fetch record!
pcap cache not loaded
error in mds_init_ctx for: /share
_mdssvc_open: Couldn't create policy handle for share
Failed to fetch record!
pcap cache not loaded`

**Comment by dianlight** [comment]
Follow the guide: https://manjaro.site/how-to-configure-time-machine-to-backup-to-samba-shared-folder/
