### ISSUE TITLE
I can't see my disk

### ISSUE THREAD

**Issue by mu3hli** [dianlight/hassio-addons#73]
Hey, thanks for the addon!
I have a problem with the configuration. After i set the config with the paramaters:

`
workgroup:` WORKGROUP
username: muehli
password: ***
allow_hosts:
  - 10.0.0.0/8
  - 172.16.0.0/12
  - 192.168.0.0/16
  - fe80::/10
moredisks:
  - Intenso
available_disks_log: true
medialibrary:
  enable: true
  ssh_private_key: |
    -----BEGIN RSA PRIVATE KEY-----
***
    -----END RSA PRIVATE KEY-----
veto_files:
  - ._*
  - .DS_Store
  - Thumbs.db
  - icon?
  - .Trashes
compatibility_mode: false
autodiscovery: {}
`

And start the addon, thats my protocol:

`
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 0.banner.sh: executing... 
---------------------------------------------------
 ____                  _           _   _           
/ ___|  __ _ _ __ ___ | |__   __ _| \ | | __ _ ___ 
\___ \ / _` | '_ ` _ \| '_ \ / _` |  \| |/ _` / __|
 ___) | (_| | | | | | | |_) | (_| | |\  | (_| \__ \
|____/ \__,_|_| |_| |_|_.__/ \__,_|_| \_|\__,_|___/
                                                   
                              Version 9.5.1-nas4
---------------------------------------------------
[cont-init.d] 0.banner.sh: exited 0.
[cont-init.d] automount.sh: executing... 
[18:40:35] INFO: Protection Mode is false
[18:40:35] INFO: MoreDisk option found!
[18:40:35] INFO: MediaLibrary option found!
ssh: connect to host 192.168.178.61 port 22222: Connection refused
[cont-init.d] automount.sh: exited 255.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] mqtt.sh: executing... 
[18:40:37] INFO: MQTT cleanup.
Error: Connection refused
[cont-finish.d] mqtt.sh: exited 1.
[cont-finish.d] umount.sh: executing... 
[18:40:37] INFO: Done.
[cont-finish.d] umount.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
`

I think the addon have now to work fine.. but i can't see my disk in the media browser. Since 3 days i try to fix this but i don't know whats the error is.  Can i help me?

Here i my hardware info 

`
DEVLINKS: /dev/disk/by-id/ata-HGST_HTS541010A9E680_JB100013J2V7ZA-part3 /dev/disk/by-id/wwn-0x5000cca6a0dd7a51-part3                                                                                     
      /dev/disk/by-label/Intenso /dev/disk/by-partuuid/27552bd3-61ab-4ada-91b2-0d515332d8f7                                                                                                                  
      /dev/disk/by-path/platform-fd500000.pcie-pci-0000:01:00.0-usb-0:1.2:1.0-scsi-0:0:0:0-part3                                                                                                             
      /dev/disk/by-uuid/26545b1a-2f12-324c-a2c6-b0dc37c25a1d                                                                                                                                                 
    DEVNAME: /dev/sda3                                                                                                                                                                                       
    DEVPATH: /devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb1/1-1/1-1.2/1-1.2:1.0/host0/target0:0:0/0:0:0:0/block/sda/sda3                                                      
    DEVTYPE: partition                                                                                                                                                                                       
    ID_ATA: "1"                                                                                                                                                                                              
    ID_ATA_DOWNLOAD_MICROCODE: "1"                                                                                                                                                                           
    ID_ATA_FEATURE_SET_APM: "1"                                                                                                                                                                              
    ID_ATA_FEATURE_SET_APM_CURRENT_VALUE: "128"                                                                                                                                                              
    ID_ATA_FEATURE_SET_APM_ENABLED: "1"                                                                                                                                                                      
    ID_ATA_FEATURE_SET_HPA: "1"                                                                                                                                                                              
    ID_ATA_FEATURE_SET_HPA_ENABLED: "1"                                                                                                                                                                      
    ID_ATA_FEATURE_SET_PM: "1"                                                                                                                                                                               
    ID_ATA_FEATURE_SET_PM_ENABLED: "1"                                                                                                                                                                       
    ID_ATA_FEATURE_SET_PUIS: "1"                                                                                                                                                                             
    ID_ATA_FEATURE_SET_PUIS_ENABLED: "0"                                                                                                                                                                     
    ID_ATA_FEATURE_SET_SECURITY: "1"                                                                                                                                                                         
    ID_ATA_FEATURE_SET_SECURITY_ENABLED: "0"                                                                                                                                                                 
    ID_ATA_FEATURE_SET_SECURITY_ENHANCED_ERASE_UNIT_MIN: "220"                                                                                                                                               
    ID_ATA_FEATURE_SET_SECURITY_ERASE_UNIT_MIN: "218"                                                                                                                                                        
    ID_ATA_FEATURE_SET_SMART: "1"                                                                                                                                                                            
    ID_ATA_FEATURE_SET_SMART_ENABLED: "1"                                                                                                                                                                    
    ID_ATA_ROTATION_RATE_RPM: "5400"                                                                                                                                                                         
    ID_ATA_SATA: "1"                                                                                                                                                                                         
    ID_ATA_SATA_SIGNAL_RATE_GEN1: "1"                                                                                                                                                                        
    ID_ATA_SATA_SIGNAL_RATE_GEN2: "1"                                                                                                                                                                        
    ID_ATA_WRITE_CACHE: "1"                                                                                                                                                                                  
    ID_ATA_WRITE_CACHE_ENABLED: "1"                                                                                                                                                                          
    ID_BUS: ata                                                                                                                                                                                              
    ID_FS_LABEL: Intenso                                                                                                                                                                                     
    ID_FS_LABEL_ENC: Intenso                                                                                                                                                                                 
    ID_FS_TYPE: ext4                                                                                                                                                                                         
    ID_FS_USAGE: filesystem                                                                                                                                                                                  
    ID_FS_UUID: 26545b1a-2f12-324c-a2c6-b0dc37c25a1d                                                                                                                                                         
    ID_FS_UUID_ENC: 26545b1a-2f12-324c-a2c6-b0dc37c25a1d                                                                                                                                                     
    ID_FS_VERSION: "1.0"                                                                                                                                                                                     
    ID_MODEL: HGST_HTS541010A9E680                                                                                                                                                                           
    ID_MODEL_ENC: HGST\x20HTS541010A9E680\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20                                                                                    
    ID_PART_ENTRY_DISK: "8:0"                                                                                                                                                                                
    ID_PART_ENTRY_NUMBER: "3"                                                                                                                                                                                
    ID_PART_ENTRY_OFFSET: "391296784"                                                                                                                                                                        
    ID_PART_ENTRY_SCHEME: gpt                                                                                                                                                                                
    ID_PART_ENTRY_SIZE: "1561966200"                                                                                                                                                                         
    ID_PART_ENTRY_TYPE: ebd0a0a2-b9e5-4433-87c0-68b6b72699c7                                                                                                                                                 
    ID_PART_ENTRY_UUID: 27552bd3-61ab-4ada-91b2-0d515332d8f7                                                                                                                                                 
    ID_PART_TABLE_TYPE: gpt                                                                                                                                                                                  
    ID_PART_TABLE_UUID: be14c9af-6e77-4a6b-9af5-999aee3b1541                                                                                                                                                 
    ID_PATH: platform-fd500000.pcie-pci-0000:01:00.0-usb-0:1.2:1.0-scsi-0:0:0:0                                                                                                                              
    ID_PATH_TAG: platform-fd500000_pcie-pci-0000_01_00_0-usb-0_1_2_1_0-scsi-0_0_0_0                                                                                                                          
    ID_REVISION: JA0OA560                                                                                                                                                                                    
    ID_SERIAL: HGST_HTS541010A9E680_JB100013J2V7ZA                                                                                                                                                           
    ID_SERIAL_SHORT: JB100013J2V7ZA                                                                                                                                                                          
    ID_TYPE: disk                                                                                                                                                                                            
    ID_WWN: "0x5000cca6a0dd7a51"                                                                                                                                                                             
    ID_WWN_WITH_EXTENSION: "0x5000cca6a0dd7a51"                                                                                                                                                              
    MAJOR: "8"                                                                                                                                                                                               
    MINOR: "3"                                                                                                                                                                                               
    PARTN: "3"                                                                                                                                                                                               
    SUBSYSTEM: block                                                                                                                                                                                         
    TAGS: ':systemd:'                                                                                                                                                                                        
    USEC_INITIALIZED: "5457428"                                                                                                                                                                              
  by_id: /dev/disk/by-id/ata-HGST_HTS541010A9E680_JB100013J2V7ZA-part3                                                                                                                                       
  dev_path: /dev/sda3                                                                                                                                                                                        
  name: sda3                                                                                                                                                                                                 
  subsystem: block                                                                                                                                                                                           
  sysfs: /sys/devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb1/1-1/1-1.2/1-1.2:1.0/host0/target0:0:0/0:0:0:0/block/sda/sda3
`

**Comment by dianlight** [comment]
What is your environment? HAOS on Rpi? or other type of installation?

Also  there are a lot of error/mis configurations.

> ssh: connect to host 192.168.178.61 port 22222: Connection refused

The addon is unable to contact the host on port 22222.  You can access to host via ssh on port 22222? Is the IP correct?

> NOTE2: It is necessary to enable the access to the SSH port 22222 of the host. Read the HassOS [Developers  Documentation](https://developers.home-assistant.io/docs/operating-system/debugging/#home-assistant-operating-system) or use the [Configutarion Addon](https://community.home-assistant.io/t/add-on-hassos-ssh-port-22222-configurator/264109).

> [18:40:37] INFO: MQTT cleanup.
> Error: Connection refused

Do you have an external MQTT server? If not remove ```autodiscovery``` feature.

```yaml
autodiscovery:
    disable_discovery: true
```

Also I suggest to repost your config with the back-ticks so I can see if the format:

````
```
<your config>
```
````

**Comment by mu3hli** [comment]
Yes, Haos in Rspi 4.

Thanks, i try to config the ssh Connections but i don't see the issues. At first i have to fix this in HassOS SSH port 22222 Configurator 
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
no vda1 config found
no sda1 config found
no sdb1 config found
already added this key to mmcblk0p1
no mmcblk1p1 config found
no nvme0n1p1 config found
This Configurator did it's job. Perform a hard-power-off now. This configurator only works once and is no longer needed.
```
 

Ah okay, here is the config with the right format:

```
workgroup: WORKGROUP
username: muehli
password: ***
allow_hosts:
  - 10.0.0.0/8
  - 172.16.0.0/12
  - 192.168.0.0/16
  - fe80::/10
moredisks:
  - Intenso
available_disks_log: true
medialibrary:
  enable: true
  ssh_private_key: |
    -----BEGIN RSA PRIVATE KEY-----
 ***
-----END RSA PRIVATE KEY-----
veto_files:
  - ._*
  - .DS_Store
  - Thumbs.db
  - icon?
  - .Trashes
compatibility_mode: false
autodiscovery: {}

```

**Comment by mu3hli** [comment]
So now i fixed the error with the port and disable the discovery in the config. The permission is still denied

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 0.banner.sh: executing... 
---------------------------------------------------
 ____                  _           _   _           
/ ___|  __ _ _ __ ___ | |__   __ _| \ | | __ _ ___ 
\___ \ / _` | '_ ` _ \| '_ \ / _` |  \| |/ _` / __|
 ___) | (_| | | | | | | |_) | (_| | |\  | (_| \__ \
|____/ \__,_|_| |_| |_|_.__/ \__,_|_| \_|\__,_|___/
                                                   
                              Version 9.5.1-nas4
---------------------------------------------------
[cont-init.d] 0.banner.sh: exited 0.
[cont-init.d] automount.sh: executing... 
[17:59:45] INFO: Protection Mode is false
[17:59:45] INFO: MoreDisk option found!
[17:59:45] INFO: MediaLibrary option found!
Warning: Permanently added '[192.168.178.61]:22222' (ECDSA) to the list of known hosts.
root@192.168.178.61: Permission denied (publickey).
[cont-init.d] automount.sh: exited 255.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] mqtt.sh: executing... 
[17:59:47] INFO: MQTT cleanup.
Error: Connection refused
[cont-finish.d] mqtt.sh: exited 1.
[cont-finish.d] umount.sh: executing... 
[17:59:47] INFO: Done.
[cont-finish.d] umount.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
```

**Comment by dianlight** [comment]
> root@192.168.178.61: Permission denied (publickey).

The provided ssh key is wrong. Please check, a common error is insert in config the public key but in the addon needs the private key not the public 

You can check also the key connecting with ssh from a pc.

**Comment by dianlight** [comment]
If you don't need more help please close the issue.
