### ISSUE TITLE
Few errors im getting

### ISSUE THREAD

**Issue by justfly1111** [dianlight/hassio-addons#78]
First it kept saying missing medialibrary sessioneven though it was enabled and provided with ssh key i turned protection off and still got same error so then i disabled  medialibrary got it to start then i edited it yaml in enabled the media library and provided ssh key and saved and restarted then tried to mount the smb shares on my freebsd system and i type the correct passsword and it says wrong password sorry try aagain even tho its correct and no typo i tried haviing the password without the quotes and within single quotes and sorry try again no matter what the passwpord is set to but the password workjs perfectly fine on all other addons incluiding the official samba addon  and also even when i thought i got around the recognizing the medialibrary section i noticed that it reverted itsself back to enable false so that wasnt successful my home assistant is home assist ant os on a odroid n2+ has anyone else had a ny of these issues that youre aware of

**Comment by dianlight** [comment]
I'm sorry but I didn't understand anything.
I suggest you use short sentences. Post the error, logs and also your configuration.
