### ISSUE TITLE
[Samba NAS] Hidden files

### ISSUE THREAD

**Issue by dimmuboy** [dianlight/hassio-addons#89]
I don't know if it's bug, my wrong configuration or feature only but...
When I edit any file in windows via Samba after save it disappear because attributes **Archive** and **Hidden** are set.

**Comment by dianlight** [comment]
I need more info to understand the problem.

Do you mean that the Hidden attribute is autoset without consent?
What is the  disk filesystem? 
What editor you use on windows? Do you try anoter?
If you remove the hidden flag the file become visible?
What type of file?

L.

**Comment by dimmuboy** [comment]
Okay thanks, it's probably only Sublime Text bug. Notepad on Windows works without issues.
Thanks for help
