### ISSUE TITLE
incorrect valid users for a share from moredisks in smb.conf

### ISSUE THREAD

**Issue by JiveOff** [dianlight/hassio-addons#98]
Hello there,

I've been having a kind of weird issue when setting up ACL on a share coming from moredisks.
I've tried investigating (and it was my first time digging into a HA addon!) and I tried re-running the GTPL inside the Docker container with an Outfile and the valid users for my share appeared but I missed a few "fruit" info at the end of the file.

For the following screenshots, usb_dev_sdb is the share that is in the moredisks array that I would like to configure with ACL.

That's what gets generated by tempio with the piped content on container startup:
![image](https://user-images.githubusercontent.com/24374817/191351884-f5811c97-fe6a-4112-b99d-2ffdb4902496.png)

This is what I have in the `/data/options.json` in the ACL part for the usb_dev_sdb share: 
![image](https://user-images.githubusercontent.com/24374817/191352294-89256816-3221-4272-8231-6add36e87418.png)
`antoine` is the main SMB user.

That's what I get when I re-run the GTPL myself using the `/data/options.json`:
![image](https://user-images.githubusercontent.com/24374817/191351761-5b43f36a-02a5-40f6-a02f-944440b1c95a.png)

The latter is exactly what I am looking for since the users I have listed in the ACL are correctly inserted in the valid users.

Here are some debug info:

Supervisor 2022.09.1
Debian 11 (running on Raspberry Pi 4)

Logs:
```
cont-init: info: /etc/cont-init.d/0.banner.sh exited 0
cont-init: info: running /etc/cont-init.d/automount.sh
[21:15:49] INFO: Protection Mode is false
[21:15:50] INFO: MoreDisk option found!
[21:15:50] INFO: MediaLibrary disabled in config. Disk are mounted only for this addon!
[21:15:50] INFO: More Disks mounting.. usb_dev_sdb
[21:15:50] INFO: Mount usb_dev_sdb Success!
[21:15:50] INFO: Success!
cont-init: info: /etc/cont-init.d/automount.sh exited 0
cont-init: info: running /etc/cont-init.d/mqtt.sh
cont-init: info: /etc/cont-init.d/mqtt.sh exited 0
cont-init: info: running /etc/cont-init.d/samba.sh
[21:15:52] INFO: Hostname: raspberrypi
[21:15:52] INFO: Interfaces: eth0 wlan0 
tdbsam_open: Converting version 0.0 database to version 4.0.
tdbsam_convert_backup: updated /var/lib/samba/private/passdb.tdb file.
Added user antoine.
Added user adrien.
Added user test.
[21:15:54] INFO: Exposed Disks Summary:    path = /config   path = /addons   path = /ssl   path = /share   path = /backup   path = /media   path = /mnt/usb_dev_sdb
cont-init: info: /etc/cont-init.d/samba.sh exited 0
```

My config (translated to JSON, comes from `/data/options.json` inside the container):
```json
{
  "workgroup": "WORKGROUP",
  "username": "antoine",
  "password": "this+is+not+a+password",
  "allow_hosts": [
    "10.0.0.0/8",
    "172.16.0.0/12",
    "192.168.0.0/16",
    "fe80::/10"
  ],
  "moredisks": [
    "usb_dev_sdb"
  ],
  "available_disks_log": false,
  "medialibrary": {
    "enable": false,
    "ssh_private_key": "<YOU SUPER SECRET PRIVATE KEY>"
  },
  "veto_files": [
    "._*",
    ".DS_Store",
    "Thumbs.db",
    "icon?",
    ".Trashes"
  ],
  "compatibility_mode": false,
  "wsdd2": false,
  "autodiscovery": {},
  "other_users": [
    {
      "username": "adrien",
      "password": "this+is+not+a+password"
    },
    {
      "username": "test",
      "password": "this+is+not+a+password"
    }
  ],
  "acl": [
    {
      "share": "usb_dev_sdb",
      "users": [
        "adrien",
        "test"
      ]
    },
    {
      "share": "config",
      "users": [
        "adrien",
        "test"
      ]
    }
  ],
  "interfaces": []
}
```

Apologies if this issue isn't complete, it is my first time reporting an issue for a HA addon. 😫

Thanks

**Comment by dianlight** [comment]
Fixed in 10.0.0-nas2
